### ISSUE TITLE
Misplaced orientation arrow

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1026]

**Comment by jaykayone** [comment]
in safari

**Comment by jaykayone** [comment]
![screen shot 2016-02-17 at 13 20 48](https://cloud.githubusercontent.com/assets/1518019/13109422/5b077286-d579-11e5-88a4-408c6e38dbfa.png)

**Comment by jaykayone** [comment]
dans v2 c'est mieux
