### ISSUE TITLE
Printing dotted line does not work

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1032]

**Comment by rmichaelis** [comment]
@sbrunner ngeo does  not forward the strokeDashstyle information to mapfish-print
How may I bypass this issue ?

**Comment by sbrunner** [comment]
It should probably added somewhere in this method:
https://github.com/camptocamp/ngeo/blob/master/src/services/print.js#L611-L623

**Comment by rmichaelis** [comment]
Yes, you are right, but as the method is marked as private, I can't subclass it.

**Comment by sbrunner** [comment]
Than I should be done in ngeo, a pullrequest is welcome :-)

**Comment by rmichaelis** [comment]
Ok I'll do that with pleasure :-)
