### ISSUE TITLE
Printing point with a symbol does not work

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1034]

**Comment by rmichaelis** [comment]
@sbrunner we can't print predifined symbols (such as square, cross, ...) because iIt seems that `ol.style.RegularShape` is not supported in ngeo : [Example here](https://github.com/camptocamp/ngeo/blob/master/src/services/print.js#L554)
and mapfishprint only supports ol2 version of styles.
Am I right ?

How do you think  we can print such things  ?

**Comment by ybolognini** [comment]
MapFish Print does not know about the custom symbols that were created with "ol.style.RegularShape", but because it uses SLD, these standard SLD symbols could be used instead: 

http://docs.geoserver.org/stable/en/user/styling/sld-extensions/pointsymbols.html#standard-symbols
