### ISSUE TITLE
Layer Manager drag element styling is ugly

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#1036]

**Comment by petzlux** [comment]
Dont see myself the issue anymore ?

**Comment by petzlux** [comment]
in firefox element has double height

**Comment by rmichaelis** [comment]
Do you have a screencopy ?

**Comment by geoportallux** [comment]
[cid:image001.png@01D29E47.3D074940]

Jeff Konnen  
Chargé d’études / Responsable du géoportail

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG 
Ministère des Finances  
Administration du cadastre et de la topographie 
Service géoportail  

54, avenue Gaston Diderich . L-1420 Luxembourg 
Tél. (+352) 44901-261 . Fax (+352) 44901-333 
E-mail: jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>  
www.act.public.lu<http://www.act.public.lu/>  www.geoportail.lu<http://www.geoportail.lu/>

[id:image001.jpg@01D26AA1.5EA0EF90]

**Comment by rmichaelis** [comment]
l'image est pas passée

**Comment by rmichaelis** [comment]
![image](https://cloud.githubusercontent.com/assets/5594996/23992003/a2cd84e6-0a3b-11e7-8a08-191105b433cc.png)

**Comment by fredj** [comment]
And the text is moved slightly on the left

**Comment by fredj** [comment]
And if the "options" panel is open, the style of the range input is incorrect:
![reorder_range](https://cloud.githubusercontent.com/assets/100959/24454941/1a9430d6-148e-11e7-9037-5a494f89989a.png)
