### ISSUE TITLE
getFeatureInfo MyMaps Layers - Select Point get all Points

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#1057]
seems to be a general problem with mymaps layers and multipoint geometries

**Comment by geoportallux** [comment]
thats's a nice one ;)

**Comment by jaykayone** [comment]
http://devv3.geoportail.lu/renaud/theme/tourisme?version=3&zoom=12&X=660230&Y=6365457&lang=fr&bgLayer=basemap_2015_global&layers=158&opacities=1&crosshair=false
