### ISSUE TITLE
ngeo compilation failure

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1066]
Hi @sbrunner, 

It seems that something causing the following error has been introduced in ngeo :
Could it be solved by an option in our project?

ERR! compile /var/www/vhosts/geoportailv3_mire/node_modules/ngeo/src/directives/btngroup.js:31: Parse error. illegal use of unknown JSDoc tag "htmlAttribute"; ignoring it
* @htmlAttribute {*} ngeo-btn-group-active Any property of the scope.

**Comment by sbrunner** [comment]
It failed on witch running command by make?

**Comment by rmichaelis** [comment]
It failed in our project by executing the build command.

**Comment by rmichaelis** [comment]
Ok I've found

This solves the issue : 
```
diff --git a/build.json b/build.json
index 7c20238..b9d14eb 100644
--- a/build.json
+++ b/build.json
@@ -81,7 +81,7 @@
       "missingRequire"
     ],
     "extra_annotation_name": [
-      "api", "observable", "ngdoc", "ngname"
+      "api", "observable", "ngdoc", "ngname", "htmlAttribute"
     ],
     "angular_pass": true,
     "compilation_level": "ADVANCED",
```

**Comment by sbrunner** [comment]
+1 :-)
