### ISSUE TITLE
Search improvement

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1080]
Recherche « Parzell.. » en allemand donne une liste SANS les « Katasterparzellen » à à voir si on peut changer la pondération

Recherche monochamp : pas encore assez parfaite et intuitive. Problème des 4 langues (devraient être considérées TOUTES), problème de logique de recherche (à partir de début au lieu de string à l’intérieur des textes : exemple cadastral à trouve PAS parcelles cadastrales, donc on doit savoir qu’on doit taper parcelles etc)

**Comment by jaykayone** [comment]
ceci est une régression, parce que dans le v2 on cherche aussi à l'intérieur du mot, à investiguer

**Comment by petzlux** [comment]
https://www.elastic.co/guide/en/elasticsearch/guide/current/ngrams-compound-words.html

**Comment by geoportallux** [comment]
looks great

**Comment by petzlux** [comment]
Ups nevermind,  layer search is at the moment not done in elasticsearch!  Done locally,  will need to check what is possible with fuse js search lib.

ES layersearch is a major refactoring 😃

**Comment by jaykayone** [comment]
at least it's not yak shaving

**Comment by petzlux** [comment]
@rmichaelis Can't reproduce the problem with Katasterparzellen ?  Its in position two after Flik Parzellen, but thats expected, as Parzellen one word is a better match. 

![screen shot 2016-03-14 at 09 30 48](https://cloud.githubusercontent.com/assets/2540428/13738770/7a72d5d6-e9c7-11e5-9b6d-db4b54d02cf2.png)

**Comment by petzlux** [comment]
We will have to define a weighting module to give preference to more commonly searched for layers ... this can be done in concert with migration to ES layer search. 

Closing for now.

**Comment by rmichaelis** [comment]
The result list depends on if you are connected or not.
