### ISSUE TITLE
Search in layers category

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1081]
Probl de retrouver les couches de l’inondation suite à recherche de mot clé « inondation », car les couches ont des noms techniques qui ne disent rien au public (HQ10)à on pourrait trouver une solution en montrant dans la recherche aussi les catégories de layers, ainsi que leurs sous-couche (contenu)

**Comment by jaykayone** [comment]
make metadata tags searchable

**Comment by petzlux** [comment]
duplicate of #1215
