### ISSUE TITLE
"add layer" button doesn't open catalog tab

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1089]
The following error happens:
```
Error: Syntax error, unrecognized expression: a[href=#catalog]
```

**Comment by rmichaelis** [comment]
This error should be already solved. 
Are you working with http://beta.geoportail.lu/ ?

**Comment by pgiraud** [comment]
Yes. Indeed. Sorry for the noise.

On Thu, Feb 25, 2016 at 5:05 PM, Renaud Michaëlis <notifications@github.com>
wrote:

> This error should be already solved.
> Are you working with http://beta.geoportail.lu/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/1089#issuecomment-188854895>
> .
>



-- 
Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com
