### ISSUE TITLE
Outil de reporting

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1106]
créer un outil de feedback des utilisateurs cf outil suisse

**Comment by jaykayone** [comment]
cf map.geo.admin.ch avec une proposition des personnes de contact en fonction des couches affichées

**Comment by jaykayone** [comment]
@fkaell this is set for end of september
assigned to @petzlux

**Comment by fkaell** [comment]
Muy bién

Francis Kaell
Ingénieur-géomètre officiel / responsable du géoportail
LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service géoportail
54, avenue Gaston Diderich . L- 1420 Luxembourg
Tél. (+352) 44901 - 244 Fax (+352) 44901 - 333
E-Mail: francis.kaell@act.etat.lu<mailto:francis.kaell@act.etat.lu>
www.act.public.lu<http://www.act.public.lu/>    www.geoportail.lu<http://www.geoportail.lu/>
