### ISSUE TITLE
marker images

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1108]
je peux définir une image (par exemple voiture rose) et elles est correctement imprimée, mais je ne la vois pas sur ma carte

http://beta.geoportail.lu/theme/main?version=3&zoom=17&X=680320&Y=6379108&lang=fr&bgLayer=topo_bw_jpeg&layers=151&opacities=1&features=Fl%28yfha-s4c6HnSK5_nB9C4-KtA~c*%2523364fe5%27e*5%27l*dashed%27n*LineString%25201%27o*0.2%27s*circle%27t*10%27r*true%29p%28dwha-w1c6H~n*Point%25202%27c*%2523ed1c24%27o*0.2%27e*1.25%27t*50%27l*plain%27s*triangle%29p%28wzha-b8c6H~symbolId*342%27n*Point%25203%27c*%2523ed1c24%27o*0.2%27e*1.25%27t*10%27a*3.141592653589793%27l*plain%29

**Comment by rmichaelis** [comment]
C'est un problème de taille de l'image.  L'image dans la carte est très petite.
Par contre le problème c'est que le print n'utilise pas la même taille d'image que dans  la carte.

**Comment by rmichaelis** [comment]
fixed by https://github.com/camptocamp/ngeo/pull/859
fixed by https://github.com/Geoportail-Luxembourg/geoportailv3/pull/1121
