### ISSUE TITLE
retina tiles for basemap

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1124]
cf http://apps.geoportail.lu/exemple_api/wmts_demo_ol3_retina.html

**Comment by rmichaelis** [comment]
Only for mobile ?

**Comment by jaykayone** [comment]
no, also for retina computers

**Comment by rmichaelis** [comment]
Yes of course. But I just would like to know, if we should use retina tiles only with retina devices, or if we could use retina tiles with all the devices.

**Comment by geoportallux** [comment]
We will have to check what the compressed difference in size is in order to know if normal resolution clients are not too much penalized by the 4x size of the images

**Comment by petzlux** [comment]
Hmm, not what I would have expected: 
Retina tile 84.5k
http://wmts1.geoportail.lu/mapproxy_4_v3/wmts/basemap_2015_global_hd/GLOBAL_WEBMERCATOR_4_V3_HD/16/33884/22335.png
Non Retina Tile 85.7k !!!!
http://wmts1.geoportail.lu/mapproxy_4_v3/wmts/basemap_2015_global/GLOBAL_WEBMERCATOR_4_V3/16/33884/22335.png

need to check for a sample of more than 1 , but encouraging!

**Comment by geoportallux** [comment]
retina tiles are 8bit, non retina not yet rendered in 8bit so still 32bit

**Comment by geoportallux** [comment]
will have to delete it first on fs before we can compare

**Comment by jaykayone** [comment]
32K Jan 13 10:20 44670.png (non retina, 32bit)
 15K Mar 10 22:35 44670.png (non retina, 8bit)
 36K Mar 10 15:18 44670.png (retina, 8 bit)

**Comment by petzlux** [comment]
also, if we use them, also use them for print ...

**Comment by jaykayone** [comment]
not necessary for print, as print is 128dpi. but we should detect device settings to bring it on mobile devices

**Comment by petzlux** [comment]
a useful method https://www.kirupa.com/html5/detecting_retina_high_dpi.htm

**Comment by petzlux** [comment]
@jaykayone Will you do retina tiles for new 2.5d basemap?

**Comment by jaykayone** [comment]
imagine it. done.
--> not seeding it right now though, as the disk is full
