### ISSUE TITLE
Scales are not properly ordered

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1134]
![image](https://cloud.githubusercontent.com/assets/5594996/13716922/5796f96a-e7de-11e5-884c-bcd863094d55.png)

**Comment by jaykayone** [comment]
don't show 200 an 300 when not available

**Comment by rmichaelis** [comment]
Order depends on this https://github.com/camptocamp/ngeo/commit/5c982dc85b388ec921dc81d85d2a38c9534e7833
