### ISSUE TITLE
columns are missing in alembic

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1140]

**Comment by jaykayone** [comment]
+ make an alter table geov3_static.shorturl ALTER COLUMN url TYPE CHARACTER VARYING(2500)

**Comment by geoportallux** [comment]
there are even new ones (has_profile) that are missing too

**Comment by rmichaelis** [comment]
ne pas oublier d'ajouter les dernières
