### ISSUE TITLE
build target

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1141]
I cannot disable the build target "print" only.

If i disable print and apache it works 
DISABLE_BUILD_TARGETS = apache print

If I disable print only (because I only want to build a webserver without print), it fails, it will try to copy the jar somewhere and stop and restart tomcat (which is obviously not installed)

@sbrunner any idea ?

**Comment by sbrunner** [comment]
Normally to disable the print you can just set the `PRINT_VERSION` to `NONE` (deferent than 2 or 3) :-)
