### ISSUE TITLE
background layer not stored in local storage?

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1220]
We had this link in the browser: http://map.geoportail.lu/theme/main?version=3&zoom=16&X=681906&Y=6393571&lang=fr&layers=360&opacities=0.75&bgLayer=topogr_global

after reopening we ended up with this:
http://map.geoportail.lu/theme/main?version=3&zoom=16&X=681906&Y=6393571&lang=fr&layers=360&opacities=0.75&bgLayer=basemap_2015_global

**Comment by rmichaelis** [comment]
Seems to work with chrome and ff. 
Which browser are you using ?

**Comment by jaykayone** [comment]
firefox at inap

**Comment by jaykayone** [comment]
so we reopened in another by only typing map.geoportail.lu
