### ISSUE TITLE
recherche: ne pas activer couche lorsqu'on est dans un certain thème

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1249]
ne pas activer la couche parcelle lors d'une recherche de parcelle quand on est dans le thème PAG ou le thème agriculture

**Comment by jaykayone** [comment]
@petzlux this one is quite important. could you please try to do this until mid august please?

we should talk about the details before starting.

**Comment by rmichaelis** [comment]
Only go to the parcel location. No highlight no new layer
