### ISSUE TITLE
Travis error

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1274]
Hi @sbrunner,

Since this morning we following error occurred :
```
Collecting dogpile.cache==0.5.6 (from -r CONST_versions.txt (line 7))
  Could not find a version that satisfies the requirement dogpile.cache==0.5.6 (from -r CONST_versions.txt (line 7)) (from versions: )
No matching distribution found for dogpile.cache==0.5.6 (from -r CONST_versions.txt (line 7))
```

Do you know why this library has disappeared ?

Thanks

**Comment by sbrunner** [comment]
She doen't disappeared we have an issue somewhere with the package that have a dot in the name... I will investigate for a solution...

**Comment by sbrunner** [comment]
It's the pip version it should be fixed here:
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/CONST_Makefile#L692

By the way you van also fix the setuptool version!

See also: https://github.com/camptocamp/c2cgeoportal/pull/2222

**Comment by rmichaelis** [comment]
Thanks @sbrunner to point out the solution and to @petzlux to have solved the issue.
