### ISSUE TITLE
Récursion dans le service de thème

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#129]
Le service themes de c2cgeoportal a un problème avec les hiérarchies à plusieurs niveaux. 
Voici par exemple ce qu'on devrait retrouver au premier niveau
![screen shot 2014-12-19 at 22 11 03](https://cloud.githubusercontent.com/assets/1518019/5511286/f644c1d8-87cb-11e4-9ecc-b6773b6d036d.png)

et ce qu'on trouve

![screen shot 2014-12-19 at 22 11 45](https://cloud.githubusercontent.com/assets/1518019/5511299/0ec25978-87cc-11e4-8b4a-603a7e816258.png)

**Comment by sbrunner** [comment]
Effectivement, je suis en train de regarder :-)
