### ISSUE TITLE
Show editable maps for admins even if they are not owned by user, but modifiable

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1291]
People who have admin rights in a category should see all the maps they can edit in the "Open a map" dialog

**Comment by rmichaelis** [comment]
Please check if it works as expected on dev.geoportail.lu/renaud

**Comment by rmichaelis** [comment]
Uses cases : 

- User is admin with role 1 (Super admin)
- [ ]  Maps filtered by default with the connected user (to have less results)
- [ ]  Can filter on categories associated with role 1
- [ ]  Can filter on users associated with categories
- [ ]  Selecting a category restrict the user list
- [ ]  Selecting a user restrict the category list

- User is admin with role other than 1
- [ ]  Maps not filtered by default (to have less results)
- [ ]  Can filter on categories associated with role 1
- [ ]  Selecting a category restrict the user list
- [ ]  Can filter on users associated with categories
- [ ]  Selecting a user restrict the category list

- User is simple user
- [ ]  No user filter
- [ ]  Category filter

**Comment by jaykayone** [comment]
yees
