### ISSUE TITLE
Track edits

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1292]
Track who edits a feature when (independently of who owns the map)

**Comment by rmichaelis** [comment]
@jaykayone Should each modification be tracked or only the last one ?

**Comment by jaykayone** [comment]
each is better

**Comment by rmichaelis** [comment]
New decision  :Only the last one

**Comment by rmichaelis** [comment]
Il faut planifier une soirée pour faire l'alter table sans cassé tout le geoportail
