### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1298]
Hi @sbrunner 

Do you have for now some troubles with pipy.camptocamp.net ?

Thanks,

![image](https://cloud.githubusercontent.com/assets/5594996/15534692/6d9ebd6c-226a-11e6-894c-4b9858c3dfd9.png)

**Comment by ybolognini** [comment]
Just had a look with @fredj as @sbrunner is at QGIS HackFest. 

We had the same error once... and then it worked. Could you check again please?  If you have the same error again, we'll have to investigate more closely.

**Comment by rmichaelis** [comment]
http://pypi.camptocamp.net/pypi/ seems to be now accessible. 
But Travis is still failing.

The error never occurs with the same library.

Here is the last error, I get : 

```
Collecting dogpile.cache==0.5.6 (from -r CONST_versions.txt (line 7))
  Downloading http://pypi.camptocamp.net/pypi/dogpile.cache/dogpile.cache-0.5.6.tar.gz (189kB)
    100% |████████████████████████████████| 192kB 1.0MB/s 
Collecting dogpile.core==0.4.1 (from -r CONST_versions.txt (line 8))
  DEPRECATION: Failed to find 'dogpile.core' at http://pypi.camptocamp.net/pypi/dogpile.core/. It is suggested to upgrade your index to support normalized names as the name in /simple/{name}.
  Downloading http://pypi.camptocamp.net/pypi/dogpile.core/dogpile.core-0.4.1.tar.gz (99kB)
    100% |████████████████████████████████| 102kB 1.0MB/s 
Collecting fa.jquery==0.9.5 (from -r CONST_versions.txt (line 9))
  Downloading http://pypi.camptocamp.net/pypi/fa.jquery/fa.jquery-0.9.5.zip (119kB)
    100% |████████████████████████████████| 122kB 412kB/s 
Collecting fanstatic==0.16 (from -r CONST_versions.txt (line 10))
  Could not find a version that satisfies the requirement fanstatic==0.16 (from -r CONST_versions.txt (line 10)) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external fanstatic to allow).
No matching distribution found for fanstatic==0.16 (from -r CONST_versions.txt (line 10))
make: *** [.build/requirements.timestamp] Error 1

```

**Comment by ger-benjamin** [comment]
I've not the solution to avoid error with pipy but you can avoid to use it.

If you got an error, you still can install a library with:
`.build/venv/bin/pip install <mylib>` example: `.build/venv/bin/pip install fanstatic==0.16`

You can also  avoid to use the proxy by removing the line `--index-url http://pypi.camptocamp.net/pypi` in files `CONST_dev_requirement.txt` and `CONST_requirement.txt`.

I Hope that helps.

**Comment by sbrunner** [comment]
@rmichaelis is it systematic? 
Can you put a Travis job URL with the error?

**Comment by rmichaelis** [comment]
Yes, it is.
Here it is : https://travis-ci.org/Geoportail-Luxembourg/geoportailv3/builds/132775006

**Comment by sbrunner** [comment]
And what about if you remove the 
`--index-url http://pypi.camptocamp.net/pypi`
in the `CONST_requirements.txt`, `CONST_dev-requirements.txt`, `CONST_Makefile` files?
We have do that in the version 2.0...

**Comment by rmichaelis** [comment]
Thanks @ger-benjamin and  @sbrunner 
Yes, it works fine without the c2c package index.

Why did you decide to don't use anymore that index-url in the version 2.0 ?

**Comment by sbrunner** [comment]
Because finally pypi is pypi.python.org is good enough, than we will have one less service to manage...
