### ISSUE TITLE
config://my_maps

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#131]
La valeur de prod pour config://my_maps est d'ailleurs http://ws.geoportail.lu/mymaps (pour tester par exemple la couche "env_sentiersnature"

**Comment by elemoine** [comment]
Je suis désolé mais je ne comprends pas cet issue. Quelqu'un peut m'éclairer ?

**Comment by jaykayone** [comment]
ici: http://luxembourg-geomapfish.dev.sig.cloud.camptocamp.net/pgiraud la couche "env_sentiersnature" ne marche pas parce que l'url my_maps dans la config est fausse

**Comment by elemoine** [comment]
Ok, merci pour la précision.
