### ISSUE TITLE
Position initiale de la carte

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1317]
Quel nom doit-on préférer pour la (les) propriété(s) qui détermine les coordonnées du centre de la carte ?
Options:
 - lon/lat,
 - easting/northing,
 - center.

Quel système de coordonnées doit être utilisé pour ces coordonnées ?
 - 4326,
 - spherical mercator,
 - système luxembourgeois.

**Comment by jaykayone** [comment]
easting/northing est le plus parlant et donc aussi le meilleur au niveau de la backwards-compatibility

système de coordonnées 2169 pour la backwards-compatibility

**Comment by jaykayone** [comment]
ici on a une contradiction avec #1324 , donner le choix est plus flexible tel que spécifié au #1324
