### ISSUE TITLE
Ajout de couches de type "overlay" à une carte existante.

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1321]
Méthode `addLayer`.

**Comment by pgiraud** [comment]
Nous pourrions aussi utiliser quelque chose comme geoadmin.
```
var layer = ga.layer.create('ch.swisstopo.pixelkarte-farbe');
map.addLayer(layer);
```

**Comment by jaykayone** [comment]
dans la v2 c'était addLayerToMap 
gardons ça

**Comment by jaykayone** [comment]
par contre, les identifiants des layers dans la v3 c'est un numéro, ça change donc un peu
je propose de rajouter évtl addLayerByName (à garder en backlog pour l'instant)

**Comment by pgiraud** [comment]
Discuté pendant le scrum : la liste des couches et des formats d'images associés seront retournés par un nouveau services (équivalent à celui des thèmes mais avec une structure à plat).
