### ISSUE TITLE
Ajout d'un marqueur

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1322]
Avec popup associée.

See http://wiki.geoportail.lu/doku.php?id=en:api:apireference#apishowmarker_options

**Comment by pgiraud** [comment]
La popup s'ouvre après un clic/tap sur le marqueur.
Doit-on prévoir un mécanisme pour pouvoir fermer la popup ?

Si oui, il existe plusieurs solutions :
 - demander aux intégrateur de rajouter eux-même un bouton (ou <a>) qui dispose d'un attribut particulier "data-dismiss" (par exemple) comme c'est fait pour les alertes bootstrap (http://getbootstrap.com/javascript/#alerts-usage),
 - rajouter dynamiquement le bouton ci-dessus dans le code qui affiche la popup. Ca laisse moins de liberté à l'intégrateur, mais c'est peut-être plus sûr sauf problème éventuel de positionnement,
 - fermer la popup automatiquement en cliquant ailleurs (cf. http://getbootstrap.com/javascript/#dismiss-on-next-click)

**Comment by rmichaelis** [comment]
Dans la V2 il y avait également la possibilité d'afficher la popup au hover.
http://wiki.geoportail.lu/doku.php?id=en:api:basictutorial

**Comment by jaykayone** [comment]
je pense que l'affichage dynamique du bouton est le plus sûr, tout en assurant qu'on puisse aussi choisir l'option hover pour le desktop

**Comment by pgiraud** [comment]
Fixed in #1327.

**Comment by pgiraud** [comment]
Il est malgré tout encore nécessaire de gérer le système de coordonnées.
