### ISSUE TITLE
Affichage des coordonnées de la souris

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1323]
Propriété `mouseposition` qui prend comme valeur l'identifiant de l'élément dans lequel les coordonnées s'afficheront.

Question : système de projection des coordonnées à définir.

**Comment by jaykayone** [comment]
laisser le choix entre 4326, 2169, 3857, utm

**Comment by pgiraud** [comment]
Ce choix est fait par l'intégrateur, n'est-ce pas ?

Note : dans la v2, c'était uniquement les coordonnées en LUREF qui était proposé.

**Comment by geoportallux** [comment]
Non, en fait on pouvait afficher les coordonnées dans les 3 systèmes, LUREF, WGS84 et UTM

Francis Kaell
Ingénieur-géomètre officiel / responsable du géoportail
LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service géoportail
54, avenue Gaston Diderich . L- 1420 Luxembourg
Tél. (+352) 44901 - 244 Fax (+352) 44901 - 333
E-Mail: francis.kaell@act.etat.lu<mailto:francis.kaell@act.etat.lu>
www.act.public.lu<http://www.act.public.lu/>    www.geoportail.lu<http://www.geoportail.lu/>

**Comment by geoportallux** [comment]
oui, choix par l'intégrateur.
dans l'api v2 il n'y avait que luref, c'est correct

Jeff Konnen

Chargé d'études - informaticien principal/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich<x-apple-data-detectors://1/0> . L-1420 Luxembourg
Tél. (+352) 44901-261<tel:(+352)%2044901-261> . Fax (+352) 44901-333<tel:(+352)%2044901-333>
E-mail: jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>

www.act.public.lu<http://www.act.public.lu/> www.geoportail.lu<http://www.geoportail.lu/>

On 13.06.2016, at 09:06, Pierre GIRAUD <notifications@github.com<mailto:notifications@github.com>> wrote:


Ce choix est fait par l'intégrateur, n'est-ce pas ?

Note : dans la v2, c'était uniquement les coordonnées en LUREF qui était proposé.

-

**Comment by pgiraud** [comment]
Fixed by #1331.

**Comment by pgiraud** [comment]
Configuration should use the following syntax:
```
position: {
  target: element,
  srs: 4326
}
```
