### ISSUE TITLE
Manipulation de coordonnées

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1324]
(Cette issue est transversale et concerne d'autres issues)

Comment les coordonnées qui servent à la configuration des différents composant doivent-elles être fournies ?

Options:
 - L'intégrateur doit convertir lui-même les coordonnées en utilisant ol.proj :
```
{
position: new ol.proj.transform([2, 3], 'EPSG:4326', 'EPSG:3857'),
}
```
 - L'intégrateur fourni la position ainsi que le système de référence (ou simplement le code) :
```
{
position: [2, 3],
positionSRS: 4326
}
```

 - le système détermine automatiquement le système de référence par analogie.

**Comment by jaykayone** [comment]
Je suis pour l'option 2

**Comment by pgiraud** [comment]
Pour le centre de la carte, il est noté que l'on utilise toujours 2169 et les propriétés easting et northing. Il faut que nous soyons cohérents

**Comment by jaykayone** [comment]
L'API doit être utilisable pour quelqu'un qui ne connaît pas OL3, donc 

```
{
position: [2, 3],
positionSRS: 4326
}
```
est la seule option pour moi

**Comment by pgiraud** [comment]
Pris en compte.
