### ISSUE TITLE
Propriétés de config

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1325]
(Cette issue est transversale et concerne d'autres issues)

Doit-on faire le maximum possible afin de garder les mêmes paramètres de configuration que dans l'API v2 ? Ou bien peut-on se permettre de choisir des noms de propriétés qui sont plus proches de la terminologie OL3 ?

**Comment by jaykayone** [comment]
c'est une bonne question ..
je pense qu'il faut voir au cas par cas.
pour le constructeur "minimal" ce serait bien d'être aussi proche que possible de la v2.

**Comment by jaykayone** [comment]
OK laissons de côté la backwards-compatibility, au besoin on rajoutera des wrappers "legacy"
