### ISSUE TITLE
Proxy for http wms when in https

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#1330]
when the site is loaded in https , any iFrame content that is http will not be loaded.

use case for example bus stops departure data.

**Comment by jaykayone** [comment]
we have to write a proxy

**Comment by jaykayone** [comment]
this proxy will have to proxy WMS, Legend and iframes

**Comment by rmichaelis** [comment]
This is really difficult to have something working fine with iframe.
I wrote a proxy, to test the specific case of bus stop.
In this proxy I rewrite each html attribute containing an url to use the proxy.

But the main issue, is that some urls are directly built in javascript.

That means, I have to parse each loaded javascript as well as each other resource, and replace each ur with the proxy.  An url could be absolute, relative, ... Thus this is really hard to be sure that a js variable contains an url. 

I'm not sure if the proxy is the best solution in this case. Shouldn't we ask the third party data providers to provide https urls ?

**Comment by jaykayone** [comment]
for iframes we will not be able to write a proxy, but for wms we will have to offer one

**Comment by jaykayone** [comment]
Conclusion:

it site in https:
  try if wms available in https
     if not:
        use proxy

in proxy make sure that we exclude to possibility to hack internal sites by using regexes

**Comment by jaykayone** [comment]
exclude: everything that contains geoportal.lu, geoportail.lu, ipranges from dmz

**Comment by rmichaelis** [comment]
We should maybe exclude everything. and just explicitly authorized servers in the config/db.
