### ISSUE TITLE
Composant recherche

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1336]
Full text search
Limité à la recherche d'adresses.

**Comment by pgiraud** [comment]
Pour ce composant, nous avons besoin de fonctionnalités avancées.  Or nous devons aussi limiter les conflits avec les librairies qui pourraient être utilisées dans la page. Réutiliser typeahead n'est de fait pas possible.
Ré-écrire un composant "from scratch" semble aussi difficile étant donné les nombreuses fonctions de navigation à prévoir.
Une autre option consiste à trouver une librairie "vanilla" (ou plain JS) qui ferait le travail sans nécessiter une librairie tierce (comme JQuery).
En faisant une recherche assez rapide, la lirairie suivante semble être une bonne candidate.
https://github.com/Pixabay/JavaScript-autoComplete

@jaykayone as-tu un avis sur les options ci-dessus ou d'autres options à proposer ?

**Comment by jaykayone** [comment]
@petzlux ?

**Comment by geoportallux** [comment]
Ceci semble OK pour nous. Nous n'avons pas d'autres librairie à proposer
