### ISSUE TITLE
Composant gestion des couches

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1337]
Componsant simple permetant de rendre les couches visibles/invisibles (avec des cases à cocher).

**Comment by pgiraud** [comment]
Le composant est prévu pour être très simple.
Où doit-on le placer ?
Peut-on imaginer un positionnement ala "OpenLayers 2" et son layer switcher ? C'est-à-dire avec un bouton qui ouvre/ferme un block dans un coin de la carte.

**Comment by geoportallux** [comment]
l'utilisateur spécifie un div
