### ISSUE TITLE
Interrogation

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1338]
Interrogation sur la carte + affichage d'un popover avec les attributs du/des features(s) sélectionné.

**Comment by pgiraud** [comment]
Dans le site principal, l'interrogation sur la carte déclenche une requête sur le service getfeatureinfo.
Celui-ci renvoie une réponse en JSON dans laquelle on retrouve notamment les features avec des attributs et un template.
http://maps.geoportail.lu/main/wsgi/getfeatureinfo?box1=76146.79758106123,72300.03952822842,76643.6173042745,72794.81198346699&box2=76382.79821536674,72535.05637882216,76407.63920152283,72559.79500158597&layers=359,199

Côté client, si j'ai bien compris le template est compilé avec angular via un ng-include.
Sans angular, le template perd un peu de son intérêt.
Il est envisageable d'imaginer un système qui viendrait parser le template et faire le même travail qu'angular car il s'agit de ng-repeat et quelques expressions à évaluer. Mais ça risque de représenter pas mal de travail.
Avez-vous d'autres idées ?
Merci.

**Comment by jaykayone** [comment]
@rmichaelis can we discuss this when you are back ?

this is quite important 
we should take a decision before pierre goes on

**Comment by jaykayone** [comment]
could it be an option to execute angular server-side and send back HTML if the integrator sets format=html ?

**Comment by pgiraud** [comment]
As discussed this morning, the chosen option is to serve HTML to the client using mako templating on the server. Templates will need to be duplicated.

**Comment by pgiraud** [comment]
Fixed in #1489.

**Comment by pgiraud** [comment]
The issue is only partially fixed. We have the tooltip generation. What's missing now is the ability to click on the map to retrieve the feature and display the tooltip.

**Comment by pgiraud** [comment]
@jaykayone que doit-il se passer lorsque l'on reçoit plusieurs résultats pour le point cliqué sur la carte ?

**Comment by jaykayone** [comment]
in the main app, we append all the results one after the other

**Comment by tonio** [comment]
Could this issue be moved to «Done» ?

**Comment by jaykayone** [comment]
yes
