### ISSUE TITLE
Sélection d'un objet par son identifiant

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1339]
`showFeatures` dans l'API de la v2

**Comment by pgiraud** [comment]
Cette méthode doit prendre deux arguments:
 - layer,
 - ids.

Existe-t'il un service dans geoportailv3 qui prends des paramètres de ce type et qui renvoie la géométrie des features ?
En v2, apparemment, on utilisait un service `bodfeature/geometry`.

J'ai noté qu'il existe le service suivant, mais il n'est probablement pas adapté.
http://maps.geoportail.lu/main/wsgi/getfeatureinfo?fid=152_130D00227006081_5907_5

**Comment by geoportallux** [comment]
il n'est pas exactement pareil, mais vous pouvez rajouter une méthode qui répond à vos besoins qui utilise le getfeatureinfo derrière
