### ISSUE TITLE
Couche "mes cartes"

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1340]
`addMyMapLayer` avec les fonctions suivantes :

 - popup,
 - profil altimétrique,
 - export GPX et KML.

Le profil altimétrique sera fait avec d3.js (comme dans l’application principale). Il devra

pouvoir être affiché dans un élément (div) en dehors de la carte.

**Comment by pgiraud** [comment]
J'ai commencé à intégrer le support pour le profil. Mais je me pose des questions.

L'affichage du profil est proposé si l'intégrateur fourni l'identifiant de l'élément div dans lequel le graphique doit s'afficher. J'ai un peu de mal à voir comment ça va pouvoir être utilisé dans la réalité, ie. comment la place disponible pour le graphique va être gardée à disposition.

Doit-on ajouter l'interaction entre le profil et la carte ? C'est à dire l'affichage dans la carte d'une bulle avec la distance et l'élévation lorsque l'on survole le graphique et inversement ? Ça va demander pas mal de travail de ré-intégrer tout ce code, d'une part. Et l'utilisation de cette fonctionnalité sera rendue compliquée par le fait que les informations sur le tracé sélectionné s'affiche dans une popup qui en général masque une grande partie de l'élément. Cf. capture ci-dessous.
Doit-on pouvoir continuer à utiliser le profil après avoir fermé la popup ?

<img width="789" alt="capture d ecran 2016-09-01 a 09 50 21" src="https://cloud.githubusercontent.com/assets/319774/18159733/5dc96816-702a-11e6-85e7-20c733680ec8.png">

Enfin, doit-on aussi ajouter les informations sur les delta ? l'export en CSV du graphique ?

**Comment by jaykayone** [comment]
on en parlera mardi, je suis encore en vacances

par contre tu peux regarder ici pour un cas d'utilisation plus ou moins reussi mais très réel ici:


http://www.visitluxembourg.com/en/place/walking/stage-trail-mullerthal-trail-route-1

**Comment by pgiraud** [comment]
J'ai commencé à mettre en place le système qui permet de gérer une callback.
J'ai maintenant un exemple qui montre comment afficher le profil au chargement de la carte.

Sauf que maintenant, j'ai des trucs bizarres au niveau de l'interaction. Que fait-on si l'intégrateur décide d'afficher le profil en reposant sur la callback qui est mise à sa disposition ? Doit-on malgré tout garder l'affichage de la popup au clic sur le feature ? Et que fait-on avec le lien "show profile" qui se trouve dans cette popup ?
Ça finit par se marcher un peu dessus.

**Comment by jaykayone** [comment]
nous avons décidé qu'il ne faut pas afficher le lien "show profile" quand le profile est déjà affiché (que ce soit par l'intégrateur ou par un premier clic)

**Comment by pgiraud** [comment]
L'export KML et GPX reste à faire. J'ai ouvert un nouveau ticket pour ça #1438.
