### ISSUE TITLE
ajout d’une couche vecteur externe (geo.map.addLayer)

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1341]
A redéfinir.

**Comment by pgiraud** [comment]
Les deux types de couches vectorielles que l'on doit pouvoir supporter sont KML et GPX.
Je propose donc de rajouter deux méthodes `addKML` et `addGPX` à l'objet Map de l'API.
Ces méthodes prennent en argument l'URL vers un fichier .kml ou .gpx.

**Comment by pgiraud** [comment]
Question : À propos de CORS. Doit-on prévoir que le fichier gpx ou kml ne se trouve pas sur le même domaine que la page sur laquelle est utilisée l'API ?
Il pourrait paraitre simple et sage de n'accepter que des fichiers hébergés sur le même serveur que la page.
Si on veut supporter n'importe quelle URL, je pense que la seule solution est de mettre en place un proxy sur le serveur du Geoportail qui récupère le fichier en question et le renvoie au client avec les bons headers CORS. Est-ce qu'un tel service proxy existe déjà ?

**Comment by jaykayone** [comment]
On peut commencer par l'hypothèse du même domaine, resp laisser à l'intégrateur la responsabilité de configurer son CORS correctement. 
Plus tard, on pourrait créer un tel proxy
