### ISSUE TITLE
Exclusions des couches

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1345]
Cela va de soi, mais @jaykayone, peux-tu confirmer que nous allons devoir gérer les exclusions de couches ?

**Comment by jaykayone** [comment]
oui

**Comment by pgiraud** [comment]
L'exclusion des couches ne semble pas aussi simple que prévu.

J'étais parti dans l'idée de ne pas laisser l'intégrateur ajouter des couches dont l'exclusion correspond aux couches (dont bg) déjà ajoutées.
Mais le cas où l'utilisateur peut changer le fond de plan va poser problème. Que devons nous faire dans ce cas ?
Dans l'application principale, si on change de background alors les couches qui rentrent en collision sont retirées.
Si on fait la même chose dans l'API, ça veut dire que la couche est supprimée et que l'utilisateur ne peut plus l'ajouter.

**Comment by jaykayone** [comment]
Bonne question, 
ne devrait-on pas alors créer une fonction qui vérifie les incompatibilités lors du switch de background et interdit le chgt?

Par exemple:

Parcelles a été rajouté par l'intégrateur, l'utilisateur n'est pas censé pouvoir l'enlever.
Si il choisit ortho comme fond, l'api lui dit "désolé, ce background est en contradiction avec la couche parcelles, vous ne pouvez pas le choisir".
c'est une idée pour l'instant ...

**Comment by jaykayone** [comment]
Après discussion, nous proposons de faire exactement la même implémentation que le map, quitte à tomber sur le cas que tu décris

**Comment by pgiraud** [comment]
Est-ce que l'on doit afficher des avertissements pour l'utilisateur final comme dans l'application principale ?

**Comment by rmichaelis** [comment]
Est-ce que ca ne devrait pas être un événement qui est envoyé et que l'intégrateur choisisse lui même sa stratégie ?

**Comment by jaykayone** [comment]
Bonne idée
