### ISSUE TITLE
Geocodage a partir d'une URL

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#1348]
exemple :directement ouvrir le portail cartographique en indiquant une adresse dans l'URL http://map.geoportail.lu/?lang=en&address=54%20avenue%20Gaston%20Diderich%201420%20Luxembourg :

**Comment by rmichaelis** [comment]
Faut il afficher un rond jaune à l'adresse sélectionnée.  Si oui comment fait-on disparaître le rond jaune ?
