### ISSUE TITLE
feature selection vs. query

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1350]
When clicking on a drawn feature on the map, there may be an interaction conflict if there are also queriable elements underneath the clicked point.
In this case, the feature is selected but the info panel is opened with the result of the query.

**Comment by pgiraud** [comment]
![geoportailv3_feature_vs_query](https://cloud.githubusercontent.com/assets/319774/16407811/eb9695da-3d15-11e6-9eea-fd8bd2a2c04d.gif)

**Comment by jaykayone** [comment]
duplicate #1333
