### ISSUE TITLE
import KML in EDGE under windows10

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#1361]
le KML est importé mais ne s'affiche pas sur la carte

**Comment by pgiraud** [comment]
See https://github.com/camptocamp/ngeo/issues/1776 and the associated pull request.

**Comment by pgiraud** [comment]
Sorry wrong issue.

**Comment by rmichaelis** [comment]
The results are not coming from webservice but from Edge's cache
