### ISSUE TITLE
Headers CORS manquants

### ISSUE THREAD

**Issue by tonio** [Geoportail-Luxembourg/geoportailv3#1364]
Les headers [CORS](https://developer.mozilla.org/fr/docs/HTTP/Access_control_CORS) manquent sur certaines resources nécéssaires pour l’API, pour l’instant :
 - les webfonts,
 - le fulltextsearch

Est-ce un choix ou juste un manque? On pourrais contourner pour le fulltextsearch avec jsonp, mais pas pour les webfont. Est-il envisageable de les ajouter?

**Comment by jaykayone** [comment]
@rmichaelis Sais-tu ce que nous devons faire ici?

**Comment by jaykayone** [comment]
Est-ce OK maintenant?

**Comment by tonio** [comment]
C'est bon pour moi pour les webfonts et la recherche, merci.
