### ISSUE TITLE
problem with print extent

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1367]
the extent chosen on the map does not match at all with the extent in the PDF.
There seems to be a factor 1.5

Observed on a macbook pro with retina display.
On windows it does not seem to be a problem, nor on a "normal" mac
<img width="646" alt="screen shot 2016-07-06 at 20 52 37" src="https://cloud.githubusercontent.com/assets/1518019/16630966/db3d622e-43bc-11e6-93ec-409d35c39590.png">

**Comment by jaykayone** [comment]
@rmichaelis this has been fixed in ngeo. can we make an update?

**Comment by rmichaelis** [comment]
@jaykayone Could you please test : http://devv3.geoportail.lu/renaud
