### ISSUE TITLE
The themes errors should be displayed [c2c]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#138]
In the integration environment the themes error should be displayed.

Actually with GeoMapFish it's the case in all environment.

**Comment by jaykayone** [comment]
que dois-je faire?

**Comment by sbrunner** [comment]
Je ne sais pas si c'est plutôt @elemoine ou @pgiraud qui doit le faire dans le composant de catalogue...

**Comment by sbrunner** [comment]
I hope that that will fix it: camptocamp/c2cgeoportal#1169

**Comment by jaykayone** [comment]
Maintenant c'est tilecloud qui demande nose ...

**Comment by sbrunner** [comment]
Hello,

Je viens de faire une version 0.2dev-20150115 qui doit corriger le problème.

CU et merci de la notif :-)

Stéph



2015-01-14 21:00 GMT+01:00 Jeff Konnen <notifications@github.com>:

> Maintenant c'est tilecloud qui demande nose ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/138#issuecomment-69981166>
> .
>



-- 
camptocamp.com
mapfish.org

**Comment by elemoine** [comment]
Now tracked by https://github.com/Geoportail-Luxembourg/geoportailv3/issues/220.
