### ISSUE TITLE
Propositions d'amélioration de la recherche

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1388]
Quelques remarques de Loubna concernant la nouvelle recherche: 
1. C'est un peu déroutant que certaines données ajoutent des couches et d'autres pas. Par exemple rechercher une adresse ajoute la couche adresse, ou rechercher une commune n'ajoute pas la couche commune. Je me suis posé la même question en recherchant après la Chiers
2. Si je recherche la commune de "Esch-sur-alzette", je dois taper au minimum "esch sur alz" avant d'avoir la proposition de la commune. Par contre on me propose bien avant Esch sur Sûre, alors que la commune 
   est plus petite et se trouve alphabétiquement parlant après.
3. Pouvoir chercher directement après un thème voir #703
4. Si on recherche extrait cadastral, on devrait avoir un résultat.

**Comment by petzlux** [comment]
Point 1 comme montre, c'est tres simple a definir les couches a ajouter.a discuter quand ca fait du sense ou quand pas.
Point 2 on devrait integrer un weighting des differents elements. ceci concerne non seulement les toponymes, mais aussi les couches ... a definir.
Point 4 , ca c'est juste une question de meta donnees, ie a ajouter des mots cles plus parlants aux couches ...

**Comment by jaykayone** [comment]
* bglayers multilingue et avec keywords
* dans cetains cas on trouve des couches qui ne sont dans aucune thème (cherchez hintergrundkarte p ex)

**Comment by petzlux** [comment]
Hintergrundkarte ? 

![screen shot 2016-07-22 at 12 13 39](https://cloud.githubusercontent.com/assets/2540428/17054132/c6f9f6b0-5005-11e6-82cc-9dff5a0b7698.png)

**Comment by jaykayone** [comment]
ok now that the are linked to a theme i see that it was a valid layer from PAG theme which is called that way

**Comment by petzlux** [comment]
If search results shown are only a subset of the results, show at least a text saying " 5 of 123 results "

**Comment by petzlux** [comment]
improve matching for bold results

**Comment by petzlux** [comment]
User Feedback:

```
Ech weess net ob et ubruecht ass dass ech Dir mol nach vun Problemer am Geoportail berichten, ma ech wollt just mol op desen Problem opmierksam maachen:
 
Ech wollt d’Parzell 1726 sichen.
Wann een daat ennert der Lupp agët, da kritt een e Lift mat Proposen vun Bascharage, Dalheim, Contern, Perlé Dippach déi och esou eng Parzell an hierer Gemeng hun.
 
Waat awer feelt, daat as d’Gemeng Monnerech! Wann een dann „1726 m“ uget, get se emmer nach net ugewisen, eréischt wann een „1726 mo“ aget, da get Monnerech och proposéiert.
 
As daat normal? Ech hoffe net….
```

**Comment by petzlux** [comment]
User Feedback:

```
Haut een aanere Problem : ech wollt ennert méngem Login a mat Hëllef vun der Lupp d’Parzell 1311/16738 zu Esch sichen.
 
Wann ech just „1311 / „ agin, da kréien ech zwar eng Parzell 1311/1811 zu Iechternach an der Lëscht proposéiert, awer keng zu Esch.
 
Wann ech „ 1311/1“, oder „1311/16“ oder souguer schon „1311/167“ „ agin, da kréien ech direkt schon an der Lëscht Parzellen aus dem Land ugewisen wou di Zuelen zwar dra virkommen, awer net méi  an der richteger Reihenfolleg, an souguer mat aaneren Haaptnummeren. Méng Parzell vun Esch, déi eigentlech d’Kritären vun den Zuelen an – en plus – vun der richteger Reihenfolleg erfëllt,  erschéngt awer emmer nach net.
 
Wann ech dann nach eng Zuel bäisetzen an „1311/1673“ agin, dann endlech erschéngt méng gesichten Parzell an der Lëscht vun de proposéierte Parzellen och.
```

**Comment by petzlux** [comment]
````
bei der Search Funktioun kommen heiandsdo nët déi Resultater, déi een erwaard: ech uelen mol un, eng vun den Haapt-Funktiounen ass, do eng Uertschaft anzetippen an dann dohinn ze sprangen. 
Dowéinst fannen ech dass d'Prioritéit vun den Uertschaften bei den Resultater net héich genuch ass. 
Du gesäiss dat zum Beispill bei folgenden Recherchen:
- Esch    
- Brouch
- Lasauv
..

Do kritt een oft ganz vill Adressen  an POIen , etc.., mee fir d'éischt mol net d'Uertschaft selwer. 

Ech froen mech och, fiirwaat d'Lëscht vun den Resultater net méi laang ass. Bei mir um Schierm wier meeschten Plaaz fiir en duebel esou laang Lescht. 

````
