### ISSUE TITLE
layer_external_wms -> wrong request parameters for "LAYERS" [c2c]

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#140]
Restant c2c 01/02/2015 0.25j

----

The WMS request that is issued is not correct:

eg for env_sentiers the following request is sent:

http://ws.geoportail.lu/mymaps?category_id=15&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=env_sentiersnature&CRS=EPSG%3A3857&STYLES=&WIDTH=1680&HEIGHT=892&BBOX=640024.3755957562%2C6361959.241609995%2C704231.4793553044%2C6396050.156225183

LAYERS should be taken from the database and its value is "category" in this case (DB is correct)

**Comment by sbrunner** [comment]
Related with camptocamp/c2cgeoportal#1168

**Comment by jaykayone** [comment]
The problem is still there after the latest update to c2cgeoportal

**Comment by elemoine** [comment]
This is a bug in the geoportailv3 client code:  `layers` rather than `name` should be used when creating a WMS layer.

**Comment by jaykayone** [comment]
on peut mettre une tête sur cette issue? @elemoine ?

**Comment by elemoine** [comment]
Yes.

**Comment by elemoine** [comment]
> on peut mettre une tête sur cette issue? @elemoine ?

C'est fait.

**Comment by elemoine** [comment]
@jaykayone est-ce que la couche env_sentiers est dans le thème principal qui est actuellement utilisé dans l'application. C'est pour tester. Merci.

**Comment by geoportallux** [comment]
oui, c’est dans le theme “emwelt” qui est utilisé par défaut à l’heure actuelle





Jeff Konnen
Chargé d’études – informaticien/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich . L-1420 Luxembourg
Tél. (+352) 44901-261 . Fax (+352) 44901-333
E-mail: jeff.konnen@act.etat.lu

www.act.public.lu www.geoportail.lu



De : Éric Lemoine <notifications@github.com<mailto:notifications@github.com>>
Répondre à : Geoportail-Luxembourg/geoportailv3 <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : Monday 2 March 2015 09:54
À : Geoportail-Luxembourg/geoportailv3 <geoportailv3@noreply.github.com<mailto:geoportailv3@noreply.github.com>>
Objet : Re: [geoportailv3] layer_external_wms -> wrong request parameters for "LAYERS" [c2c] (#140)


@jaykayone<https://github.com/jaykayone> est-ce que la couche env_sentiers est dans le thème principal qui est actuellement utilisé dans l'application. C'est pour tester. Merci.
