### ISSUE TITLE
Mouse projection

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#1403]
The coordinates showed are not the ones of the mouse position

**Comment by jaykayone** [comment]
can you elaborate?

**Comment by jaykayone** [comment]
<img width="1440" alt="screen shot 2016-08-04 at 15 33 10" src="https://cloud.githubusercontent.com/assets/1518019/17403604/d5677904-5a58-11e6-991d-1c34aed790a5.png">
here the mouse is positioned on the grid crossing and the shown coordinates do match

**Comment by geoportallux** [comment]
I just had a user on the phone with the issue

I asked to place the mouse on the parcel and she recived coordinates of another parcel

PC Win10 Browsers ( FF& EDGE)

**Comment by jaykayone** [comment]
look who's back:

this is the distorted map problem

**Comment by geoportallux** [comment]
Oh no

Francis Kaell
Ingénieur-géomètre officiel / responsable du géoportail
LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service géoportail
54, avenue Gaston Diderich . L- 1420 Luxembourg
Tél. (+352) 44901 - 244 Fax (+352) 44901 - 333
E-Mail: francis.kaell@act.etat.lu<mailto:francis.kaell@act.etat.lu>
www.act.public.lu<http://www.act.public.lu/>    www.geoportail.lu<http://www.geoportail.lu/>
