### ISSUE TITLE
Search Box Mouse focus fix

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#1405]
If user selects a search result, and search box looses focus, at the moment, the whole search result text is selected when the user clicks in the search box again. this is so that it is easy to erase last search result and start a new search. 

Problem is if the user wants to continue search, a second mouse click to deselect search text to continue typing still selects whole text. 

If the search result text is selected by click, on second click the search result text should be deselected and cursor jump to end to continue search.

**Comment by jaykayone** [comment]
doublon
