### ISSUE TITLE
message with changed layers coming as soon as i open map

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1412]
http://g-o.lu/3/e6A2

I open the map and the message comes ASAP

<img width="339" alt="screen shot 2016-08-16 at 07 24 30" src="https://cloud.githubusercontent.com/assets/1518019/17688761/81b6e8e8-6382-11e6-8c89-4affe1c34d30.png">

**Comment by jaykayone** [comment]
when logged

**Comment by rmichaelis** [comment]
@jaykayone it should be solved by #1613. Could you please check on prod?
