### ISSUE TITLE
JSAPI - Needs for more translations

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1418]
I'll put here the list of elements that need to be translated.
- [ ] Coordinates control

**Comment by jaykayone** [comment]
should we make a separate repo in transifex for the API or is it OK to use the same on than for the main app?

**Comment by petzlux** [comment]
If we stick with same repo, we need to create a separate resource file `*_api.po` . Transifex will still propose for similar strings existing translations.
