### ISSUE TITLE
print

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1424]
Salut @sbrunner , 

J'ai une question concernant le service d'impression dans notre solution geoportailV3.
Nos utilisateurs se plaignent de soucis de performance. 
Par exemple cette carte : http://g-o.lu/3/KBti
Lorsque tu imprimes en A0, après 2 minutes mapfishprint retourne un timeout. 
J'ai testé en augmentant le timeout à 29 minutes, mais le getstatus devient de plus en plus lent et après 29 minutes le fichier n'est toujours pas généré.

Dans notre mapV2, la même impression prenait au maximum une dizaine de secondes avec une qualité d'impression parfaite. 

Une des différences entre l'impression dans notre geoportail V2 et V3, c'est les DPI.
Pour avoir une qualité comparable à ce que nous avions dans le V2, nous devons utiliser le paramètre DPI à 300.

Aurais-tu une idée de ce que nous pourrions faire pour améiorer la vitesse d'impression et d'avoir des performances comme nous avions dans la V2? 
Est-ce que les dernières versions de mapfish print ne pourraient pas résoudre notre problème ?

D'avance merci,

Renaud

**Comment by sbrunner** [comment]
@rmichaelis Tu aurais un example de spec JSON?

**Comment by rmichaelis** [comment]
@sbrunner voici une toute simple avec 2 couches: 


{
	"attributes": {
		"map": {
			"dpi": 300,
			"center": [692984,
			6400961],
			"projection": "EPSG:3857",
			"rotation": 0,
			"scale": 3868.2398778391225,
			"layers": [{
				"baseURL": "http://wmts1.geoportail.lu/mapproxy_4_v3/wmts/topo_bw_jpeg/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.jpeg",
				"dimensions": [],
				"dimensionParams": {
					
				},
				"imageFormat": "image/jpeg",
				"layer": "topo_bw_jpeg",
				"matrices": [{
					"identifier": "18",
					"scaleDenominator": 2132.7295838500004,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [262144,
					262144]
				},
				{
					"identifier": "19",
					"scaleDenominator": 1066.3647919250002,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [524288,
					524288]
				},
				{
					"identifier": "20",
					"scaleDenominator": 533.1823959625001,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [1048576,
					1048576]
				},
				{
					"identifier": "21",
					"scaleDenominator": 266.59119798125005,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [2097152,
					2097152]
				}],
				"matrixSet": "GLOBAL_WEBMERCATOR_4_V3",
				"opacity": 1,
				"requestEncoding": "REST",
				"style": "default",
				"type": "WMTS",
				"version": "1.0.0"
			},
			{
				"baseURL": "http://wmts1.geoportail.lu/mapproxy_4_v3/wmts/topogr_global/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.png",
				"dimensions": [],
				"dimensionParams": {
					
				},
				"imageFormat": "image/png",
				"layer": "topogr_global",
				"matrices": [{
					"identifier": "18",
					"scaleDenominator": 2132.7295838500004,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [262144,
					262144]
				},
				{
					"identifier": "19",
					"scaleDenominator": 1066.3647919250002,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [524288,
					524288]
				},
				{
					"identifier": "20",
					"scaleDenominator": 533.1823959625001,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [1048576,
					1048576]
				},
				{
					"identifier": "21",
					"scaleDenominator": 266.59119798125005,
					"tileSize": [256,
					256],
					"topLeftCorner": [-20037508.3428,
					20037508.3428],
					"matrixSize": [2097152,
					2097152]
				}],
				"matrixSet": "GLOBAL_WEBMERCATOR_4_V3",
				"opacity": 1,
				"requestEncoding": "REST",
				"style": "default",
				"type": "WMTS",
				"version": "1.0.0"
			}]
		},
		"scale": 2500,
		"name": "",
		"url": "http://g-o.lu/3/IFL7",
		"qrimage": "http://map.geoportail.lu/main/wsgi/qr?url=http://g-o.lu/3/IFL7",
		"lang": "fr",
		"legend": null,
		"scalebar": {
			"geodetic": true
		}
	},
	"layout": "A0 portrait"
}

**Comment by sbrunner** [comment]
Thanks :-)

**Comment by pvalsecc** [comment]
J'ai fais le profiling d'une impression A0 300DPI dans votre config sur ma machine (du costaud d'il y a une année avec 16GB de RAM et un Xmx=4GB ).
les trois points qui blessent sont:

Dernière fonction dans MFP | Function appelée | temps réel par thread [s]	| nb appels
-----------------|--------------|------------|-----------
CreateMapProcessor.createLayerGraphics | ImageIO.write	|  66.576  | 2
SingleTileLoaderTask.compute | SocketInputStream.read | 66.651 | 1233
JasperReportPDFOutputFormat.doExport | ... | 25.928 | 1

Le temps de génération globale du PDF était de 1'49''.

Donc, on passe un énorme temps (67s) a construire la grosse image qui contient la carte (assemblage des tuiles et des couches entre elles). ImageIO pourrait être remplacé par quelque chose comme [PNGEncoder](http://objectplanet.com/pngencoder) qui prétend être 5-7x plus rapide. Comme cette tâche n'est pas parallélisable, le gains de temps lors de l'encodage de l'image se reporterait directement sur le temps total de génération du PDF.

Le deuxième point correspond au temps de chargement des tuiles. Il ne faut pas le prendre comme étant un problème. Je fais le test sur une machine éloignée des serveurs carto. De plus les nouvelles versions de MFP (>=3.6.0) on des meilleures possibilités de configuration pour downloader les tuiles en parallèle.

Le troisième point est la génération du PDF dans Jasper (26s). Il n'y a pas de point de le code de Jasper iText qui pose spécialement problème. On ne peut pas faire grand chose de ce coté.

Il faut dire que du A0 en 300DPI, c'est beaucoup de pixels à  avaler et re-cracher pour le print. Le V2 avait l'avantage de mettre les tuiles tel quels dans le PDF, sans vraiment les charger en RAM (streaming).

En résumé, les points qui peuvent être investigués pour la suite:

- Tester tout ça sur une machine chez vous qui a plus de RAM (>=8GB) avec un -Xmx >= 4GB.
- Comprendre pourquoi vous avez du augmenter les DPIs. Un doublage des DPI quadruple l'utilisation RAM et CPU.
- Tester avec MFP 3.6.0 et un bon tuning du download parallèle.
- Changer de librairie pour générer les PNGs passés à Jasper.

**Comment by jaykayone** [comment]
OK, je vais répondre à la question qui me concerne directement:

* Comprendre pourquoi vous avez du augmenter les DPIs. Un doublage des DPI quadruple l'utilisation RAM et CPU.

Pour avoir une qualité de rendu comparable entre v2 et v3, nous avons dû passer à une résolution de 300. Si on trouve une solution ou la qualité est comparable avec 128 DPI, on est preneurs. Taille de PDF, temps de génération etc sont des arguments non négligeables

**Comment by jaykayone** [comment]
Pour l'instant en prod, nous tournons à -Xmx1g
Nous avions fait un test à 4GB, ça n'avait pas fait de différence

**Comment by jaykayone** [comment]
Pour MFP 3.6.0, pouvez-vous nous fournir un WAR et nous aider à faire du tuning de download parallèle?

**Comment by pvalsecc** [comment]
Le WAR est disponnible là: http://repo1.maven.org/maven2/org/mapfish/print/print-servlet/3.6.0/
Pour tuner le download parallèle, une fois que le WAR est deployé, il faut éditer le fichier `WEB-INF/classes/mapfish-spring.properties` et changer cette section:
```
# Number of parallel threads to make requests for tile/image layers.
threadsParallelRequests=30

# Maximum number of parallel requests.
maxConnectionsTotal=100

# Maximum number of parallel requests per route/host.
maxConnectionsPerRoute=10
```
Après, il faut redémarrer tomcat.

**Comment by sbrunner** [comment]
One solutions can be:
* Go back to 128 DPI.
* Add in the print settings a list of authorized resolutions to create the canva (that should corresponds to the resolutions of the WMTS layers)
* Modify the print to used it ...

**Comment by sbrunner** [comment]
The idea of adding the resolutions is to solve the quality issue :-)

**Comment by jaykayone** [comment]
we already do some cheating regarding the resolutions here:
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/print/printdirective.js#L545

We only send the higher resolution tiles to MFP so that it only takes the more detailled tiles.
Is that what you mean?

Our experiences have shown that we still need to set 300 for the result to be comparable to the v2 result. If we set it to 128 the result looks bad.

If you find a way how to make it look good and sharp at 128, we are more than happy.


Here is an example where we compared the different options. It is a map containing labels.
http://g-o.lu/3/712h


[pcn_prints.zip](https://github.com/Geoportail-Luxembourg/geoportailv3/files/513155/pcn_prints.zip)


For maps without labels, 128 can be OK. We did several tests with orthoimagery and topo maps.

What we see more is that the old MFP had a better rendering for the labels than the new one.
(See attachment). How could we solve this? Is there a setting to influence the compression of the tiles? Here the label tiles seem to be compressed too much (JPEG compression ratio??)
