### ISSUE TITLE
permalink

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1429]
the link in the bottom right of the API map should be a permalink to the map (X,Y,Zoom, background and overlay layers

**Comment by pgiraud** [comment]
Should be fixed now.
@jaykayone please confirm.

**Comment by jaykayone** [comment]
yes, but it would be better in target=_blank 
and I think the layer ordering is reversed 
(http://apps.geoportail.lu/exemple_api/apiv3_demo.html#example3)
