### ISSUE TITLE
Less files

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#143]
Why less folder is in the project "root" folder ?
for me it should be in the folder "geoportailv3/static/" ...

**Comment by pgiraud** [comment]
We don't need the less files to be accessible by the browser actually.

**Comment by elemoine** [comment]
@sbrunner can we close this?

**Comment by pgiraud** [comment]
So the less files are now in static folder, right?

**Comment by sbrunner** [comment]
yes
