### ISSUE TITLE
wms layers not working in api

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1434]
http://apps.geoportail.lu/exemple_api/apiv3_demo.html#example3

wms layers are treated like wmts layers.

**Comment by pgiraud** [comment]
Actually, "internal WMS" layers are correctly supported. "External WMS" are not.

**Comment by pgiraud** [comment]
@jaykayone Please confirm that this is OK now.

**Comment by jaykayone** [comment]
yes, as you can see on the example page, it is now OK

**Comment by pgiraud** [comment]
This doesn't seem to be fixed actually.
The layers "Pistes cyclables" are treated as if they were WMTS layers.

**Comment by jaykayone** [comment]
it worked 1 hour ago until the last merge

**Comment by pgiraud** [comment]
Sorry. Something wrong on my side. Will fix it as soon as possible.
