### ISSUE TITLE
Layers exclusion [c2c]

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#144]
Get from #31

Restant c2c 01/01/2015 2j
Restant c2c 01/02/2015 2j
Restant c2c 01/03/2015 2j

----

Some layers cannot be displayed together on the map. There's an exclusion mechanism.

**Comment by pgiraud** [comment]
@jaykayone Dans la version en production actuellement, l'exclusion des layers est gérée via le fichier `themes.ini`.
Or vous nous avez signalé que le fichier `themes.ini` était en réalité désormais extrait depuis une base pour en faciliter sa gestion.
Je suppose que les exclusions sont elles-mêmes des informations qui sont stockées dans la base.
Sous quelle forme sont-elles stockées ?

**Comment by jaykayone** [comment]
Salut Pierre,
ces informations sont stockées de la même manière que dans le themes.ini, en tant qu'array d'entiers.
J'ai aussi migré ces informations dans la base de données de c2cgeoportail en tant que ui_metadata (clé "exclusion")

**Comment by pgiraud** [comment]
Merci @jaykayone.

Dans l'application en production actuellement, lorsque une couche est ajoutée (par exemple parcelles) et qu'elle est incompatible avec la couche de fond courante (par exemple basemap_global), la couche de fond est remplacée par une couche blanche (fond blanc).
Je pense que nous voulons le même mécanisme pour la v3. Or nous n'avons pas de telle couche dans les "background_layers" renvoyées par le service de thèmes.
D'après le code, il suffirait d'avoir une couche dont l'attribut "name" est "blank".
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js#L97

Est-il prévu et envisageable de rajouter une telle couche via la base de données ? Ou bien doit-on rajouter une couche manuellement dans le code javascript ?

**Comment by jaykayone** [comment]
je peux la rajouter dans la base, il n'y a pas de souci.

Une chose qui me vient à l'esprit est que nous avions envisagé d'informer l'utilisateur en cas de remplacement de couche (tel que c'est le cas dans l'app mobile). je le note ici afin de ne pas l'oublier

**Comment by pgiraud** [comment]
Le travail est en cours dans une branche sur github.
https://github.com/Geoportail-Luxembourg/geoportailv3/compare/pgiraud_layers_exclusion?expand=1

Il manque :
 [ ] le switch automatique de base layer,
 [ ] la mise en place d'un système global de messages,
 [ ] la traduction des messages.

**Comment by pgiraud** [comment]
@jaykayone, j'ai noté que tu avais rajouté une layer blank dans les backgrounds. Quelle serait la méthode la plus simple pour que nous ayons cette couche sur notre serveur également ?

**Comment by geoportallux** [comment]
Salut,

en fait, il faut que nous vous envoyions un dmp, mais nous voulons attendre que https://github.com/Geoportail-Luxembourg/geoportailv3/pull/338 soit mergé avant de l’envoyer







Jeff Konnen
Chargé d’études – informaticien/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich . L-1420 Luxembourg
Tél. (+352) 44901-261 . Fax (+352) 44901-333
E-mail: jeff.konnen@act.etat.lu

www.act.public.lu www.geoportail.lu



De : Pierre GIRAUD <notifications@github.com<mailto:notifications@github.com>>
Répondre à : Geoportail-Luxembourg/geoportailv3 <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : Monday 16 March 2015 11:39
À : Geoportail-Luxembourg/geoportailv3 <geoportailv3@noreply.github.com<mailto:geoportailv3@noreply.github.com>>
Objet : Re: [geoportailv3] Layers exclusion [c2c] (#144)


@jaykayone<https://github.com/jaykayone>, j'ai noté que tu avais rajouté une layer blank dans les backgrounds. Quelle serait la méthode la plus simple pour que nous ayons cette couche sur notre serveur également ?

**Comment by pgiraud** [comment]
Fixed via https://github.com/Geoportail-Luxembourg/geoportailv3/pull/364
Il reste à gérer la traduction des messages. J'ouvre un autre ticket pour ça.
