### ISSUE TITLE
Geocoding et reverse geocoding

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#1442]
fonction de geocoding permettant de trouver les coordonnées d’une adresse (geocode)
fonction de “reverse geocoding” permettant de trouver l’adresse la plus proche d’une coordonnée (reversegeocode)

**Comment by pgiraud** [comment]
Example of reverse geocoding: 
http://map.geoportail.lu/main/wsgi/geocode/reverse?easting=6.14991661519588&northing=9.5790084478897

**Comment by pgiraud** [comment]
Pour le geocoding, j'imaginais une méthode "geocode" dans le namespace `lux` qui prenne en argument une adresse et une fonction. Cette fonction serait appelée une fois la réponse reçue du service avec une paire de coordonnées. Libre à l'utilisateur ensuite d'utiliser cette fonction pour par exemple afficher un marqueur.

Pour le reverse geocoding, ce serait une méthode "reverseGeocode" qui prend en argument des coordonnées et une fonction de callback.

**Comment by jaykayone** [comment]
OK, pour le geocode "normal", il manque la fonction côté python pour l'instant. 
Je propose que @rmichaelis la migre avant que vous fassiez le travail côté JS

**Comment by pgiraud** [comment]
Ne s'agit-il pas simplement de la fonction de recherche ?

**Comment by jaykayone** [comment]
non c'est différent:

(pour la v2)
http://wiki.geoportail.lu/doku.php?id=en:api:rest

On va essayer de garder la même syntaxe
