### ISSUE TITLE
sensibility on clic

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1445]
the line in this example http://apps.geoportail.lu/exemple_api/apiv3_demo.html#example9 is very difficult to clic on. there must be a tolerance setting that can be set somewhere.
In our main app, it works better

**Comment by pgiraud** [comment]
I disagree with the fact that it's easier on the main app.
http://maps.geoportail.lu/theme/main?version=3&zoom=16&X=681890&Y=6378675&lang=fr&layers=512-386&opacities=1-1&bgLayer=topo_bw_jpeg&map_id=63c5e450445e438d9126a3757bee9d2b

**Comment by jaykayone** [comment]
you are right. maybe it is related to retina display?

**Comment by tonio** [comment]
https://github.com/openlayers/ol3/issues/5862

**Comment by jaykayone** [comment]
for GPX and KML, the mous pointer changes to a hand when clicable, but not for mymaps. can this be adapted?

**Comment by jaykayone** [comment]
idem for the tooltips. there we should also have the pointer changed

**Comment by tonio** [comment]
mymaps & tooltip hovering are covered by https://github.com/Geoportail-Luxembourg/geoportailv3/pull/1580.
For the sensibility, seems that https://github.com/openlayers/ol3/pull/5995 could be merged next week… I’ll keep an eye on it.
