### ISSUE TITLE
reload strategy when adding KML / GPX

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1455]
When adding a GPX / KML file to a map, the user should be able to define the reload strategy in the options

http://openlayers.org/en/v3.7.0/apidoc/ol.source.TileWMS.html#updateParams

cf: integrators wanting to choose a kml layer to be reloaded once a minute like here: http://cita.lu/

**Comment by pgiraud** [comment]
Should this be configured with something like the following?
```
map.addGPX('gpx-trace.gpx', {
  reloadInterval: 60
});
```

**Comment by jaykayone** [comment]
yes

**Comment by pgiraud** [comment]
Pull request merged.
@jaykayone can you please update the demo and eventually confirm that this is issue is fixed?
