### ISSUE TITLE
addKML

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1456]
When adding a KML saved in Google Earth, it is not shown in the API.
I had to replace the namespaces to make it work.
Can this be fixed?

I had to replace 
this:

<kml 
xmlns="http://www.opengis.net/kml/2.2" 
xmlns:gx="http://www.google.com/kml/ext/2.2" 
xmlns:kml="http://www.opengis.net/kml/2.2" 
xmlns:atom="http://www.w3.org/2005/Atom">

by this:

<kml 
xmlns="http://www.opengis.net/kml/2.2" 
xmlns:gx="http://www.google.com/kml/ext/2.2" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.opengis.net/kml/2.2 https://developers.google.com/kml/schema/kml22gx.xsd">

to make it work

**Comment by pgiraud** [comment]
@jaykayone Can you please share such a KML file?

**Comment by jaykayone** [comment]
[demo.kml.zip](https://github.com/Geoportail-Luxembourg/geoportailv3/files/497615/demo.kml.zip)


BTW: it can't be imported into mymaps either

**Comment by pgiraud** [comment]
I had a try at reading the KML file with OL3 only.
It looks like it's not correctly read.
The problem in this file is that we use the "xsi" namespace but it's not defined anywhere. OL3 accept to read the file by either:
 - adding 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' in the `kml` tag,
 - removing the `schemaLocation` attribute in the `Document` tag.

I tried a validation on the file and I get the following error:
"namespace error : Namespace prefix xsi for schemaLocation on Document is not defined"

**Comment by pgiraud** [comment]
I just installed Google Earth 7.1.7.2602 on my computer and created a KML from a drawn line, and I get a file without any attributes in the `Document` tag.

How did you generated the file you provided?

**Comment by jaykayone** [comment]
OK, I did the following:

* Create a mymaps map
* Export into KML
* Open KML in GE
* Change a color
* Export from GE

--> Then it does not work.

When I make a new drawing in GE, there is no problem.

Let's forget this, it seems to be a GE bug
