### ISSUE TITLE
Background layer question

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#147]
In https://github.com/camptocamp/ngeo/pull/133 I created a `backgroundLayerMgr` service and an example implementing a background layer selector based on that service. In that example a standard `<select>` element is used. The example can be seen at http://erilem.net/ngeo/backgroundlayer/backgroundlayer.html.

The question is: is using a regular `<select>` ok for the geoportailv3 project? The drawback of using `<select>` is that we can't customize the select caret (the small arrow) and the list of options displayed under the field. The advantage of using `<select>` is that it's simple to implement and it's natively accessible.

Another option is to use Bootstrap's [`dropdown`](https://github.com/camptocamp/pyramid_closure) JavaScript plugin. See the Bootstrap documentation for examples. I can work on a new example that uses Bootstrap downdown if using that makes more sense to people.

Please provide feedback.

**Comment by jaykayone** [comment]
Hi
I'm not near a computer so I cannot check it myself.
What was used in the prototype implemented by the designers?

Will a normal select fit into the design or will it necessarily be ugly?

I suspect that it will render diffenrently on diffenrent platforms and browsers which is not wantes

Jeff

**Comment by elemoine** [comment]
> What was used in the prototype implemented by the designers?

A component that pushes the "my layers / catalog" panel down when the list opens. When we were in Lausanne we said that we weren't sure we'd keep that. See https://github.com/Geoportail-Luxembourg/geoportailv3/issues/6.

But, in the design prototype, the design of background layer is obviously well integrated with the rest of the page.

> I suspect that it will render diffenrently on diffenrent platforms and browsers

Right.

> which is not wantes

So this means we should try to use a Bootstrap (or Bootstrap-like) dropdown, right?

**Comment by jaykayone** [comment]
> On 14 janv. 2015, at 15:04, Éric Lemoine <notifications@github.com> wrote:
> 
> What was used in the prototype implemented by the designers?
> 
> A component that pushes the "my layers / catalog" panel down when the list opens. When we were in Lausanne we said that we weren't sure we'd keep that. See #6.
> 
RIGHT
> But, in the design prototype, the design of background layer is obviously well integrated with the rest of the page.
> 
> I suspect that it will render diffenrently on diffenrent platforms and browsers
> 
> Right.
> 
> which is not wantes
> 
> So this means we should try to use a Bootstrap (or Bootstrap-like) dropdown, right?
> 
YES

**Comment by elemoine** [comment]
Here is a new example based on [Angular Bootstrap](http://angular-ui.github.io/bootstrap/)'s `dropdown` directive: http://erilem.net/ngeo/backgroundlayer2/backgroundlayerdropdown.html.

**Comment by jaykayone** [comment]
much better :)

**Comment by pgiraud** [comment]
Question answered. Closing.
