### ISSUE TITLE
impossible to add "blank" bgLayer

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1478]
var map11 = new lux.Map({
  target: 'map11',
  bgLayer: 'blank',
  layers: [353,359]
});

we have to add another layer that will then be removed by the exclusion.

**Comment by pgiraud** [comment]
I just created a pull request to address this.
However, one simple solution is also not to provide the `bgLayer` option.

**Comment by jaykayone** [comment]
I tried that and it did not work ..

**Comment by pgiraud** [comment]
Indeed, sorry, it loads the default bg layer which is not the blank layer.
