### ISSUE TITLE
déduplication des géométries

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1483]
Quand on édite un objet linéaire, des fois, après rechargement de la carte, la ligne existe en 4 versions ou seulement la 4e est la complète

**Comment by rmichaelis** [comment]
Tiens, est-ce que c'est toujours 4 versions ? Ou bien parfois 3, parfois 2, parfois 5 ?

**Comment by jaykayone** [comment]
j'imagine que c'est variable ? mais comme je n'arrive pas à reproduire ...
