### ISSUE TITLE
geocoding not present in API

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1507]
http://apiv3.geoportail.lu/api/wsgi/geocode/search?num=54&street=avenue%20gaston%20diderich&zip=1420&locality=luxembourg

Has this code not been integrated from master yet?

**Comment by pgiraud** [comment]
This probably due to the fact that the jsapi branch was not rebased onto master.
Can you please update your instance with the newly rebased jsapi branch?

**Comment by jaykayone** [comment]
+1
