### ISSUE TITLE
tooltip howto

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1508]
I am missing an example about how to use the tooltip functionality?

http://apps.geoportail.lu/exemple_api/apiv3_demo.html#example14

**Comment by pgiraud** [comment]
The "feature" example is probably what you are looking for.
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/jsapi/jsapi/examples/feature.js

**Comment by jaykayone** [comment]
OK then I did not understand how to display the tooltip

**Comment by pgiraud** [comment]
No, actually you were right. The click-query functionality is still missing. Sorry for the omission.
