### ISSUE TITLE
incohérence entre showMarker et feature

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1526]
quand on fait un showMarker, le tooltip apparaît au clic
quand on fait feature: {}, le tooltip apparaît au hover.

les deux devrait être au hover par défaut, configurables pour le clic

dans les deux cas, on devrait pouvoir spécifier un div pour afficher le contenu hors de la carte

**Comment by tonio** [comment]
Dans le cas ou on spécifie un div, son contenu doit il être le contenu de la popup ou l'intégralité (popup + content) ?

**Comment by jaykayone** [comment]
le contenu

**Comment by tonio** [comment]
OK, c'est ce que j'ai fait dans #1538
