### ISSUE TITLE
attribution

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1537]
add a control to the map to specify the attribution of a layer. this is necessary for the new roadmap which inludes OSM data

**Comment by jaykayone** [comment]
as far as i saw, there is nothing in geoportailv3 or ngeo to specify the attribution of a layer.

I suggest that we add a ui_metadata "attribution" that is added to a layer when present.

We can than use the ol.attribution control to show it.

we also have to make sure that it gets printed

**Comment by petzlux** [comment]
Can @rmichaelis  check out the print templates .. ?
