### ISSUE TITLE
Print issue with overlaying 2 text objects (mymaps)

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#1542]

**Comment by jaykayone** [comment]
voir si on peut faire des règles de collision dans mapserver

**Comment by jaykayone** [comment]
@adonno can you give us an example please?

**Comment by adonno** [comment]
![image](https://cloud.githubusercontent.com/assets/13216947/21799888/73284ff8-d71b-11e6-9ac2-859c154e8676.png) (MAP)
![image](https://cloud.githubusercontent.com/assets/13216947/21799916/94612384-d71b-11e6-9df4-37592fd7cb2f.png) (PRINT)

**Comment by geoportallux** [comment]
MErci

Jeff Konnen  
Chargé d’études / Responsable du géoportail

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG 
Ministère des Finances  
Administration du cadastre et de la topographie 
Service informatique & Service géoportail  

54, avenue Gaston Diderich . L-1420 Luxembourg 
Tél. (+352) 44901-261 . Fax (+352) 44901-333 
E-mail: jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>  
www.act.public.lu<http://www.act.public.lu/>  www.geoportail.lu<http://www.geoportail.lu/>

[cid:image001.jpg@01D26B33.AFA3FDF0]
