### ISSUE TITLE
Clip and merge lines

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1551]
Offer the possibility to clip and merge lines in mymaps

**Comment by geoportallux** [comment]
+ snapping

**Comment by rmichaelis** [comment]
@jaykayone could you please review on devv3/renaud 
I took the decision to keep the line orientation. I don't know if it's appropriate or not. Exemaple : 
![image](https://user-images.githubusercontent.com/5594996/30510014-db1f1d34-9abc-11e7-8334-4dbcd885c78c.png) 
![image](https://user-images.githubusercontent.com/5594996/30510020-ec5fbf04-9abc-11e7-80b5-4eddb2a388b5.png)

**Comment by jaykayone** [comment]
it works fine.
some remarks:
- in the fusion dialog, i would invert the buttons. cancel left, fusion right. seems more natural to me.
- i would not use a check box for the split interaction, but a click once interaction
- for the line orientation question I am not sure. Especially as there is no Undo possibility so that you could go back and flip the line and try again. maybe we should have to possibility to keep the original geometries ?

We will discuss this altogether on monday morning

**Comment by rmichaelis** [comment]
Should be ok. Could you please have a last try ?
