### ISSUE TITLE
orientation arrows sometimes too close

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1553]
apparently sometimes the orientation arrows are drawn too close to each other ..

don't a have an example though

**Comment by jaykayone** [comment]
can you try to find an example please?

**Comment by adonno** [comment]
the issue is that the lines on with the orientation arrows are, get smaller as you zoom out the arrow however has a fixed pixel size. The arrows should get smaller as you zoom out
