### ISSUE TITLE
Search field firefox

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#1585]
when an address is entered there is no way to click and to change a single character. the whole field stays selected (single click or double click) and is deleted on keyenter

**Comment by rmichaelis** [comment]
Only in FF. Workaround is to use the keyboard arrows

**Comment by petzlux** [comment]
Can we all live without the function that onclick on the textbox, the whole search query is selected. 

there are browser inconsistencies that make this very difficult to implement consistently
