### ISSUE TITLE
also render WMS layers in high definition when clients support it

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1588]
![retina](https://cloud.githubusercontent.com/assets/1518019/20622098/822f51ce-b301-11e6-942b-cdae8fb959ec.png)

cf bus stops in this screenshot

**Comment by rmichaelis** [comment]
Do you mean the  map_resolution=144 parameter ?

**Comment by jaykayone** [comment]
actually i mean this

<img width="635" alt="screen shot 2016-12-27 at 09 44 00" src="https://cloud.githubusercontent.com/assets/1518019/21495650/2530c148-cc19-11e6-894a-abca24e140a1.png">

**Comment by rmichaelis** [comment]
Ok thanks. That means we have to store the server type.

**Comment by jaykayone** [comment]
or set mapserver by default
