### ISSUE TITLE
Catalogue interférences d'ouvertures de groupes

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#160]
Dans Firefox 35 / Mac OS Yosemite, l'ouverture d'un sous-groupe referme le groupe principal

**Comment by elemoine** [comment]
Tu peux stp décrire de manière plus précise comment reproduire le problème (pas à pas). Je suis étonné, il me semble que je ne reproduis pas dans mon Firefox (Firefox 36.0a2 Linux).

**Comment by jaykayone** [comment]
![interferences](https://cloud.githubusercontent.com/assets/1518019/5815564/f2039be2-a096-11e4-94a5-7b0f3369abdc.gif)

**Comment by pgiraud** [comment]
Le code ne semble pas être complètement à jour.
En effet, il devrait y avoir un +/- qui apparait à droite pour le niveau 2.

![screenshot from 2015-01-20 11 27 37](https://cloud.githubusercontent.com/assets/319774/5815623/66bf566a-a097-11e4-9383-45b7a08e7872.png)

**Comment by jaykayone** [comment]
en mode incognito c'est OK, il semble donc y avoir un problème de cache assez brutal, est-ce qu'il faudrait dès le départ prévoir de charger certains fichiers avec un paramètre de version comme c'était déjà la cas dans l'ancienne version? (idem https://github.com/Geoportail-Luxembourg/geoportailv3/issues/161)

**Comment by jaykayone** [comment]
je ferme celui-ci et je rouvre un autre
