### ISSUE TITLE
Catalogue: activation de couches

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#161]
Dans Firefox 35 / Mac OS Yosemite, si on active la couche "anf_reserves_naturelles", les 4 couches de se niveau sont cochées, mais aucune d'elles n'est affichée

**Comment by elemoine** [comment]
À nouveau (comme #160) je ne reproduis pas le problème dans mon Firefox (36.0a2 Linux). Ce bug me semble être un bug de logique, je suis donc étonné de ne pas pouvoir le reproduire.

**Comment by jaykayone** [comment]
cf video https://github.com/Geoportail-Luxembourg/geoportailv3/issues/160
