### ISSUE TITLE
Search: specify layers to return results for per theme [lux]

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#162]

**Comment by jaykayone** [comment]
can you develop this? Is this about subtypes being specified per theme for the search-field?
This has to be discussed.
As we can now add layers between themes, it gets more complicated.
Should certain subtypes only be searchable if the layer is present? eg FLIK - numbers?
For others, it's the other way round though. POIs should always be searchable, and if the layer is not present it will be added ..

**Comment by petzlux** [comment]
@jaykayone still need to discuss this.

**Comment by jaykayone** [comment]
duplicate
