### ISSUE TITLE
Prise en charge de la version des fichiers statiques (cache bursting) [c2c]

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#163]
Get from #31
Restant c2c 01/01/2015 0.25j
Restant c2c 01/02/2015 1j

----

Firefox semble avoir un gros souci de cache après upgrade de la solution.
On doit prévoir un mécanisme d'invalidation du cache dès le départ (par exemple avec un paramètre de version dans les requêtes de chargement du js)

**Comment by elemoine** [comment]
Oui, @sbrunner et moi avons discuté de ça hier. Nous avons prévu de le prendre en place. @sbrunner, ça pourrait être une de tes prochaines tâches non ?

**Comment by sbrunner** [comment]
Oui :-)
