### ISSUE TITLE
Toponyme

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1645]
Dans la couche Toponymes Cadastraux : 

On a "in der Salzbach" et "Zone Industrielle in Salzbaach"

Dans la recherche on trouve in der Salzbach mais pas l'autre. La couche toponyme cadstraux est alors automatique ajoutée. Donc on se dit qu'on pourrait chercher après Zone Industrielle in Salzbaach

**Comment by petzlux** [comment]
@rmichaelis je ne peux pas reproduire, voir screenshot de la recherche prod

![screen shot 2017-02-23 at 15 12 18](https://cloud.githubusercontent.com/assets/2540428/23262316/939ae156-f9da-11e6-8656-434a3649690b.png)

**Comment by rmichaelis** [comment]
Ce que je veux dire c'est que "Zone Industrielle in Salzbaach" n'est pas trouvé comme lieu-dit, alors que je pense qu'il devrait l'être.

**Comment by rmichaelis** [comment]
Si aucune adresse n'est associée avec "Zone Industrielle in Salzbaach"(ce qui était le cas, quand j'ai créé le ticket)  alors il est introuvable.

**Comment by petzlux** [comment]
il n-y a pas de lieu dit 'Zone industrielle in Salzbach' !

**Comment by petzlux** [comment]
@jaykayone can you check the toponyme database

**Comment by jaykayone** [comment]
in der salzbach exists and i think what rmichaelis meant was that it should be found although the user was looking for an address in der salzbaach with 2 a

**Comment by rmichaelis** [comment]
Not really. I would like to find  'Zone industrielle in Salzbach' as lieu-dit

**Comment by jaykayone** [comment]
but it does not exist in the toponyme db

**Comment by rmichaelis** [comment]
Example here : http://g-o.lu/3/ufmD

'Zone industrielle in Salzbach' is displayed in the layer "Toponymes Cadastraux" , just like "In der Salzbach" or "Im Gruendchen"

In the searchbox "Im Gruendchen" and "In der Salzbach" are found as lieu dit, but not "Zone industrielle in Salzbach"

I think that the layer is inconsistent with the search.

If you search for "Im Gruendchen", the map automatically open the layer 'Toponymes cadastraux'.
Then the user think that he could search as well for "Zone industrielle in Salzbach".

**Comment by jaykayone** [comment]
ok i see the problem is in the loading of the search db where we exclude road names
