### ISSUE TITLE
Filter research per result type

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1646]
Pouvoir rechercher sur un élément particulier.

Par exemple: ne rechercher que les adresses. ou que les num cadastraux.

L'utilisateur écrirait un truc du genre adresse:54 did et ne recevrait en résultat que les adresses.

**Comment by petzlux** [comment]
Need to include a query string query to enable this functionality 

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html#_field_names

**Comment by geoportallux** [comment]
pour moi, ça devrait fonctionner comme suit:

Quand on tape p.ex. junglinster, la recherche nous renvoie:

- le lieu
- des parcelles
- des poi
- des adresses

On devrait avoir un "..." par catégorie qui permettrait de voir tous les résultats de ce type
