### ISSUE TITLE
Question sur la doc de l'api

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1649]
@tonio @pgiraud 

Nous aimerions fournir à nos utilisateur une première version de l'api pour la fin de cette semaine, et il me reste 2 questions concernant la doc: 

- Je  ne comprends pas comment configurer le build pour que la source pointe vers la branche github jsapi et non pas le master :
![image](https://cloud.githubusercontent.com/assets/5594996/22210835/6bf40d56-e18b-11e6-801b-566449920e6c.png)

- Quelle est la meilleure stratégie pour servir la documentation à travers apache ? Pour le moment la doc est construite dans le répertoire geoportailv3/static/build/apidoc/. qui n'est pas directement accessible à travers les règles apache misent en place pour le projet. J'aimerais avoir votre avis la dessus, parceque je crois que je passe à coté de quelque chose.

Merci de votre aide.

**Comment by pgiraud** [comment]
1. Le nom de la branche est apparemment spécifié dans `jsapi/jsdoc/api/template/tmpl/details.tmpl`.
Tu peux apporter la modification suivante :

``` diff
diff --git a/jsapi/jsdoc/api/template/tmpl/details.tmpl b/jsapi/jsdoc/api/template/tmpl/details.tmpl          
index 92ff9a8..a68c11a 100644                                                                                 
--- a/jsapi/jsdoc/api/template/tmpl/details.tmpl                                                              
+++ b/jsapi/jsdoc/api/template/tmpl/details.tmpl                                                              
@@ -117,7 +117,7 @@ if (data.defaultvalue && (data.defaultvaluetype === 'object' || data.defaultvalu          
    |<?js                                                                                                     
    |// https://github.com/Geoportail-Luxembourg/geoportailv3/tree/jsapi/jsapi/src                            
    |var baseUrl = 'https://github.com/Geoportail-Luxembourg/geoportailv3/blob/' +                            
-      (process.env.TRAVIS_COMMIT || 'master') + '/jsapi/';                                                   
+      (process.env.TRAVIS_COMMIT || 'jsapi') + '/jsapi/';                                                    
    |?>                                                                                                       
    |   |<a href="<?js= baseUrl ?><?js= meta.shortpath ?>"><?js= meta.shortpath ?></a>,                       
    |   |<a href="<?js= baseUrl ?><?js= meta.shortpath ?>#L<?js= meta.lineno ?>">line <?js= meta.lineno ?></a>

```

**Comment by pgiraud** [comment]
2. Le hash "e8f66439e6244f0c8d1312ed1b89cf57" peut être n'importe quoi. "xxx" fonctionne aussi.
http://apiv3.geoportail.lu/api/wsgi/proj/xxx/build/apidoc/

Partant de ce principe, nous pensons qu'un RewriteRule devrait faire l'affaire.

```
RewriteRule ^${apache_entry_point}api/doc/(.*)$ /${instanceid}/wsgi/proj/a/build/apidoc//$1 [PT]
```

À rajouter dans `apache/wsgi.conf.mako` (non testé).

**Comment by rmichaelis** [comment]
Merci pour les informations. 
Une dernière question,pour le moment on travaille sur une branche séparée. 
Est-ce que tu penses qu'il vaut mieux rester sur une branche dédicacée, qu'on rebasera régulièrement sur le master ? ou bien de merger le tout dans le master ?  ou bien avoir un fork dédicacé à l'api ? Ca serait quoi la meilleure pratique ?

**Comment by pgiraud** [comment]
S'agit-il de deux instances différentes sur le serveur (l'application principale et l'API) ?
Je pensais que la branche `jsapi` allait être mergée dans master, c'était une branche de développement qui nous permettait de travailler tranquillement en isolant cette fonctionnalité. Maintenant que le travail est fait et qu'il ne reste éventuellement que des bugfix ou des améliorations, je suis d'avis que cette branche peut désormais faire l'objet d'une pull request globale et d'un merge sur master.
