### ISSUE TITLE
Send fme notification when a map of a certain category is updated

### ISSUE THREAD

**Issue by geoportallux** [Geoportail-Luxembourg/geoportailv3#1662]
(cf v2)

**Comment by rmichaelis** [comment]
il faut juste appeler le job fme au bon moment

**Comment by rmichaelis** [comment]
dans la config key value categorie à qui on envoie

**Comment by rmichaelis** [comment]
In Map V3, we don't save anymore a map when modification is done.
That means each feature or map modification is directly saved.
And any modification will send a fme notification.
That's probably not wanted.

**Comment by jaykayone** [comment]
could we just monitor the triggering of the public flag?
