### ISSUE TITLE
Shapely installation issue

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#167]
We get hit by https://github.com/Toblerity/Shapely/issues/231, making the build fail on Travis.

**Comment by elemoine** [comment]
Until this is fixed we can go back to Shapely 1.5.4. @sbrunner, what is the proper place in the project to fix package versions?

**Comment by elemoine** [comment]
`requirements.txt` I guess.

**Comment by sbrunner** [comment]
Yes :-)
