### ISSUE TITLE
search: proposition from IVV

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1684]
Moie Jeff a Francis,
 
Et sinn ëmmer mei Strukturen op der Musel, déi mam Geoportail schaffen. Dat sinn haaptsächlech Spretzgenossenschaften, awer och gréisser Betrieber déi mat dem Geoportail hier Areal gérèieren.
 
Mir kruuten vun deene Leit gesot, dats se onbedengt gären eng Recherche Fonctioun hätten fir d’Parcelle viticole. Momentan geet d’Recherche jo nëmme mat der FLIK Parzell. Ass do eppes ze maachen w.e.g.?

**Comment by petzlux** [comment]
merged with #1286
