### ISSUE TITLE
copy/paste DM to use in www.geocaching.com

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1704]

**Comment by geoportallux** [comment]
EXAMPLES SUR CETTE PAGE: https://www.geocaching.com/geocache/GC4A7AN_piraten-kannercache?guid=eed36ead-1aba-424b-8a4c-a86aba411142

le souci c'est qu'il faut mettre les apostropes pour les minutes à la fin de chaque coordonnée
