### ISSUE TITLE
Info button X open on load of site

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#1782]
<img width="794" alt="screen shot 2017-04-20 at 16 49 10" src="https://cloud.githubusercontent.com/assets/2540428/25236877/535eedb8-25e9-11e7-8aaa-b72a9026cfa8.png">

**Comment by petzlux** [comment]
@rmichaelis can we look over this together tomorrow, the variable `infosOpen` gets changed somewhere on initialisation , but cant work out where ....

**Comment by petzlux** [comment]
this also happens on firefox, when its the very first visit to the site (tested in incognito mode) ...

**Comment by rmichaelis** [comment]
The problem occurs when the map is started with sidepanel closed. 
@fredj 
here : https://github.com/camptocamp/ngeo/blob/master/src/directives/btngroup.js#L176
It seems that ngModelCtrl.$viewValue is undefined, and it causes the info button to be active although the mainCtrl.infosOpen is set to false. Do you have an idea why it is so ?

**Comment by fredj** [comment]
`infosOpen` is correctly initialized to `false` but is then set to `undefined` by the print directive.
