### ISSUE TITLE
rebase of jsapi 

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1785]
Hi @fredj 

I want to rebase our jsapi on the master. 
With the ngeo migration I now have the following error. 
I'm not sur how to solve this error. Do you have an idea  ?

> ERR! compile ../../node_modules/ngeo/options/ngeox.js:158: WARNING - Bad type annotation. Unknown type ngeo.rule.Rule
> ERR! compile  * @type {!Array.<!ngeo.rule.Rule>|undefined}
> ERR! compile                    ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:369: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  *     dataSources: (Array.<ngeo.DataSource>|undefined),
> ERR! compile                             ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:394: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  * @type {Array.<ngeo.DataSource>|undefined}
> ERR! compile                  ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:465: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  *     wfs: (!Array.<!ngeo.DataSource>),
> ERR! compile                       ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:466: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  *     wms: (!Array.<!ngeo.DataSource>)
> ERR! compile                       ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:474: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  * @type {Array.<ngeo.DataSource>}
> ERR! compile                  ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:481: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  * @type {Array.<ngeo.DataSource>}
> ERR! compile                  ^
> ERR! compile
> ERR! compile 0 error(s), 7 warning(s), 96.8% typed
> ERR! compile
>

**Comment by fredj** [comment]
@rmichaelis we have this same issue in an other project, it has to be fixed in ngeo.

**Comment by fredj** [comment]
See https://github.com/camptocamp/ngeo/pull/2576
