### ISSUE TITLE
extent search restriction

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1794]
Search for a parcel.
Not for a POI.

**Comment by rmichaelis** [comment]
here https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/jsapi/src/main.js#L1118

**Comment by petzlux** [comment]
Change layer url parameter to accept a list 
Iterate layers here: 
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/views/fulltextsearch.py#L114
