### ISSUE TITLE
C2C pypi server -  package problems ? 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#181]
```
Collecting Pillow==2.7.0 (from -r CONST_versions.txt (line 15))
  Downloading http://pypi.camptocamp.net/pypi/pillow/Pillow-2.7.0.zip (7.6MB)
    99% |############################### | 7.6MB 455bytes/s eta 0:00:25
  Hash of the package http://pypi.camptocamp.net/pypi/pillow/Pillow-2.7.0.zip#md5=da10ee9d0c0712c942224300c2931a1a (from http://pypi.camptocamp.net/pypi/pillow/) (9bd16d050fa8b2422d081501336d7a1d) doesn't match the expected hash da10ee9d0c0712c942224300c2931a1a!
  Bad md5 hash for package http://pypi.camptocamp.net/pypi/pillow/Pillow-2.7.0.zip#md5=da10ee9d0c0712c942224300c2931a1a (from http://pypi.camptocamp.net/pypi/pillow/)
make: *** [.build/eggs.timestamp] Error 1
```

**Comment by rmichaelis** [comment]
Est-ce que ce n'est pas un problème de cache sur notre proxy ??

**Comment by petzlux** [comment]
on avait des problèmes, mais @jaykayone avait dit que c'etait résolu !

**Comment by petzlux** [comment]
Autre problème: 

on a besoin d'une branche spécifique de transifex de transifex pour éviter des problèmes de proxy, comme spécifié dans 
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/requirements.txt#L5

Par contre, dans mon build, transifex semble étre chargé du pypi c2c , qui ne semble pas contenir la bonne version de transifex:

```
Collecting transifex-client
  Downloading http://pypi.camptocamp.net/pypi/transifex-client/transifex-client-0.10.tar.gz (68kB)
    100% |################################| 69kB 6.7MB/s 
  Running setup.py install for transifex-client
    changing mode of build/scripts-2.7/tx from 664 to 775
    changing mode of /home/wepa/geoportailv3/.build/venv/bin/tx to 775
Successfully installed c2c.template-1.0.1.dev3 c2c.versions-0.4 closure-linter-2.3.13 flake8-2.3.0 mccabe-0.3 pep8-1.5.7 pep8-naming-0.2.2 pyflakes-0.8.1 pyramid-debugtoolbar-2.3 python-gflags-2.0 transifex-client-0.10 z3c.recipe.filetemplate-2.2.0 zc.buildout-2.3.1 zc.recipe.egg-2.0.1
```

Donc nos problèmes de proxy reviennent quand on veut communiquer avec le site transifex . Je peux manuellement remédier a ce problème en installant la bonne branche manuellement ...

**Comment by sbrunner** [comment]
Hello, pour transifex c'est tout a fait normal qu'il charge la version 0.10, si on veut une version de "dev" il faut spécifier la version dans `DEV_REQUIREMENTS += transifex-client`
par exemple avec `DEV_REQUIREMENTS += transifex-client>=0.11.1dev` :-)

**Comment by sbrunner** [comment]
Pour Pillow il doit de nouveau avoie un problème dans votre proxy ...
si je fais :
```
wget http://pypi.camptocamp.net/pypi/pillow/Pillow-2.7.0.zip
md5sum Pillow-2.7.0.zip
da10ee9d0c0712c942224300c2931a1a  Pillow-2.7.0.zip
```
J'obtiens le bon md5 ...

**Comment by geoportallux** [comment]
Bizarrement, la règle “no-cache” est définie au niveau du host complet …
Je vais quand même leur demander





Jeff Konnen
Chargé d’études – informaticien/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich . L-1420 Luxembourg
Tél. (+352) 44901-261 . Fax (+352) 44901-333
E-mail: jeff.konnen@act.etat.lu

www.act.public.lu www.geoportail.lu



De : Stéphane Brunner <notifications@github.com<mailto:notifications@github.com>>
Répondre à : Geoportail-Luxembourg/geoportailv3 <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : Monday 26 January 2015 12:06
À : Geoportail-Luxembourg/geoportailv3 <geoportailv3@noreply.github.com<mailto:geoportailv3@noreply.github.com>>
Objet : Re: [geoportailv3] C2C pypi server - package problems ? (#181)


Pour Pillow il doit de nouveau avoie un problème dans votre proxy ...
si je fais :

wget http://pypi.camptocamp.net/pypi/pillow/Pillow-2.7.0.zip
md5sum Pillow-2.7.0.zip
da10ee9d0c0712c942224300c2931a1a  Pillow-2.7.0.zip


J'obtiens le bon md5 ...

**Comment by jaykayone** [comment]
avec wget, ça marche aussi correctement:
[root@workshop3-local tmp]# md5sum Pillow-2.7.0.zip
da10ee9d0c0712c942224300c2931a1a  Pillow-2.7.0.zip

**Comment by petzlux** [comment]
@sbrunner okay, probleme transifex resolu avec #191

**Comment by elemoine** [comment]
@jaykayone est-ce qu'on peut fermer ça ? Est-ce que le problème avec Pillow a été résolu ?e

**Comment by petzlux** [comment]
Non encore aujourd'hui , j'avais le problème :-(

**Comment by jaykayone** [comment]
je confirme que le problème existe toujours. avec wget, le fichier est OK, mais avec l'installer il a un mauvais hash

**Comment by elemoine** [comment]
Que faut-il faire ? Pensez-vous qu'il s'agit d'un problème de notre côté ? En tout cas un problème que Camptocamp doit résoudre ?

**Comment by jaykayone** [comment]
je dirais que vous pourriez analyser si la dépendance pillow est définie d'une autre manière que tous les autres ce qui nous expliquerait la différence. Ensuite une installation "à part" dans le script make pourrait être envisagée pour contourner le problèmes

**Comment by sbrunner** [comment]
Pillow est une dépendance de TileCoud tout a fait classique ...

**Comment by jaykayone** [comment]
seems to be solved
