### ISSUE TITLE
Eviter que les clés de traduction soient visibles avant que les traductions ne soient chargées [c2c]

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#182]
Restant c2c 01/02/2015 0.25j uniquement pour investigation
Restant c2c 01/03/2015 0.25j uniquement pour investigation
Restant c2c 01/04/2015 0.25j uniquement pour investigation
Restant c2c 01/05/2015 0.25j uniquement pour investigation

**Comment by elemoine** [comment]
Que voudrait-on exactement ? Veut-on vraiment cacher toutes les clés de traduction tant qu'on a pas les valeurs de traduction ? Si on utilise l'anglais pour les clés de traduction n'est-il pas préférable d'avoir du texte en anglais plutôt que du vide ? Le problème est peut-être lié aux clés de traduction qui ne sont pas du texte en anglais mais des mots techniques genre « seach_key_words ».

**Comment by rmichaelis** [comment]
Est-ce que les clés de traduction ne devraient pas être dans la langue la plus utilisée du géoportail plutôt que l'anglais ?

**Comment by jaykayone** [comment]
tu as raison: si toutes les clés étaient "parlantes", le problème serait moins grave.
en fait, il y a très peu de texte traduit chez nous, chez geoadmin ça me gênait plus, mais ils ont dû changer qqch récemment, le problème n'est plus là. les traductions mettaient 2-3 secondes avant d'arriver, mais ça semble résolu

**Comment by jaykayone** [comment]
@rmichaelis bonne question. Le FR est le plus utilisé

**Comment by elemoine** [comment]
> Est-ce que les clés de traduction ne devraient pas être dans la langue la plus utilisée du géoportail plutôt que l'anglais ?

Oui, je me suis posé la même question.

Ce serait réaliste d'utiliser le français pour toutes les clés de traduction ?

**Comment by jaykayone** [comment]
En tout cas pour celle qu'on voit au chargement de la page

**Comment by elemoine** [comment]
> En tout cas pour celle qu'on voit au chargement de la page

Pour les traducteurs ce serait plus simple si toutes les clés de traduction avaient la même forme.

Et il faut que les traducteurs connaissent le français si les clés de traduction sont en français. C'est le cas ?

**Comment by jaykayone** [comment]
oui, ça c'est le cas.
C'est pour le nom des couches que je ne suis pas très chaud pour les faire en français. Ces noms feront partie des permaliens, et on peut éviter des problèmes si ces noms ne contiennent pas d'accent. C'est pour cela que je définis les noms de couches toujours sans accents et avec "_" etc .... 

Pour tout ce qui n'est pas "noms de couche", on peut prendre la valeur française comme clé

**Comment by pgiraud** [comment]
Sur géoadmin, les éléments de la page apparaissent tout d'un coup, une fois l'application initialisée.
Ils reposent apparemment sur ngCloak. https://docs.angularjs.org/api/ng/directive/ngCloak

**Comment by jaykayone** [comment]
Nous allons changer les clés de traduction de la loupe et des 7 icônes qui sont visibles lors du chargement pour qu'elles soient en français, comme ça 90% des utilisateurs n'auront pas de problème. @petzlux peux-tu t'en charger?
