### ISSUE TITLE
debug mode doesn't work anymore

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#184]
Restant c2c 01/02/2015 0.5j

----

I get the following error: `goog.require could not find: app.MainController`

`http://localhost:5000/closure-deps.js` returns an empty response.

**Comment by jaykayone** [comment]
same for me

**Comment by pgiraud** [comment]
This has been fixed in pyramid_closure. Closing.

**Comment by sbrunner** [comment]
This should also be fix in c2cgeoportal
