### ISSUE TITLE
less restrictions on password

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1850]
passwords are maximum 10 chars
why?
we should remove this restriction

**Comment by rmichaelis** [comment]
I don't find any place in geoportail where the password would be restricted to maximum 10 chars. Any idea ?

**Comment by jaykayone** [comment]
the one who told me said it was in myaccount when creating a new user

**Comment by rmichaelis** [comment]
Probably already solved. Now it seems to work as expected.
