### ISSUE TITLE
When using WMTS layers, use information from capabilities

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#1866]
At the moment, the connection information for wmts layers is hardcoded.

It is not possible to use a layer like this:

https://arcgis-portal.gouv.etat.lu/arcgis_server/rest/services/Hosted/cantons_on_portal/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

We need a proxy for wmts requests like we have one for "internal wms" ..

to be discussed

**Comment by geoportallux** [comment]
with a flag in the config to decide whether to use the url from the capabilities or not
