### ISSUE TITLE
Need to add .eggs to .gitignore ? 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#187]
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/search/.eggs/README.txt

**Comment by sbrunner** [comment]
I don't understand why this repository is created ...
Anyone know why ?

**Comment by elemoine** [comment]
I don't know either at this point, but it should be removed from the GitHub repository.

**Comment by sbrunner** [comment]
sure that should be removed :-) and added to the .gitignore !
