### ISSUE TITLE
Display distance on the path

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#1936]
Gudde Mëtteg !

 

Am GPSIES gëtt et eng Méiglechkeet, d’Kilometer op enger Streck unzeweisen.

 

Et wär interessant och des Funktioun am Geoportail ze hunn (wann dat net mat ze vill Opwand fir Iech verbonnen ass)

 

Merci a léif Gréiss

![image](https://user-images.githubusercontent.com/5594996/33473727-d90687de-d677-11e7-9ae7-b9c6d183b138.png)

**Comment by jaykayone** [comment]
duplicate #1893
