### ISSUE TITLE
problem with translations when label <> key [lux]

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#195]
There is a problem in the translations:
http://devv3.geoportail.lu/main/ vs http://emwelt.geoportail.lu/

In the old version there is a group called "env_bruit" which should be translated "bruit"... but it is translated "Aéroport 2011 (LNGT)"...

I guess it is a problem with the migration of the translations @petzlux ... in the old portal, the group was called "env_bruit" but it's label was "bruit" --> it's translation has not been migrated. we should check this.

**Comment by petzlux** [comment]
maybe simplest to update transifex  .... ?

**Comment by jaykayone** [comment]
I will take care of updating transifex
