### ISSUE TITLE
layer info - Modal ?

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#196]
Bonjour,

J'ai commencé à travailler sur l'outil qui permettra d'afficher des infos (métadonnées) sur les couches de données.
Pour afficher ces métadonnées, plusieurs options s'offrent à nous en terme de UI.

- popover :
L'avantage de cette solution est que le block qui apparait est lié à un élément via une flèche.
Il sera par contre assez difficile de gérer techniquement le fait qu'un seul popover ne doit être affiché à la fois, en permettant quand même à l'utilisateur de cliquer dans le contenu du popover.
Je pense que cette option peut-être éliminée.
http://getbootstrap.com/javascript/#popovers

- modal :
Avec cette option, le positionnement est simple et géré par bootstrap. L'implémentation serait facile.
L'inconvénient, c'est qu'une fenêtre modale est en général utilisée pour demander une action à l'utilisateur. Ça peut sembler intrusif.

- popup :
(ala geoadmin)
Cette option est moins intrusive que l'option modal. Elle est techniquement moins facile à mettre en oeuvre que modal, mais je dois pouvoir récupérer du code de géoadmin.
Par contre, je pense qu'il ne faut pas permettre à l'utilisateur d'afficher plusieurs popup à la fois. Le fait de pouvoir déplacer la popup ne me parait pas pertinent, mais je veux bien votre avis.

Avez-vous des idées ? Connaissez-vous de bons exemples d'application qui font cela ?

**Comment by jaykayone** [comment]
En tout cas, la solution actuelle n'est pas optimale, parce que le texte des métadonnées peut remplir toute la fenêtre et on ne voit alors pas la légende. La légende elle peut-être très longue ..

Une petite fenêtre comme un popover ne s'y prête donc pas.

La solution à la geoadmin est viable sans me plaire, surtout qu'on peut y superposer une multitude de popups

**Comment by pgiraud** [comment]
Pour info, mon commentaire était parti un peu vite. J'ai complété.

@jaykayone "viable sans me plaire"  : peux-tu élaborer ?

**Comment by pgiraud** [comment]
Au SITG, quand la fiche de métadonnées est conséquente, c'est une nouvelle fenêtre du navigateur qui s'ouvre.
http://ge.ch/geoportail/pro/?share=2bf9e744-881b-435a-8237-45cda4fac5d4

![screenshot from 2015-01-28 14 30 40](https://cloud.githubusercontent.com/assets/319774/5938359/6fc06be6-a6fa-11e4-9ca9-ff26397ddfe8.png)

**Comment by jaykayone** [comment]
Ma réponse était partie trop vite aussi, tu n'avais pas encore complété.
Le premier truc qui me gêne c'est qu'on puisse en ouvrir plusieurs, tu l'as dit toi-même dans ta réponse complétée. 
Je dis viable parce que ça correspond au fonctionnement actuel ... donc faisable et OK
Mais l'actuel ne me plaît pas non plus, notamment parce qu'on doit scroller autant. 
Est-ce qu'un panneau latéral tel que tu l'as prévu pour les "featureinfo" ne serait pas une alternative?
Une deuxième page qui s'ouvre style "target="_blank"" ça fait un peu 1990

**Comment by pgiraud** [comment]
Quand tu parles de l'actuel, tu parles du géoportail Luxembourg actuel n'est-ce pas ?
Autre considération à prendre en compte, c'est l'affichage sur mobile.

> ça fait un peu 1990
OK, mais ça fonctionne bien et même sur mobile. C'est sans surprise.

**Comment by pgiraud** [comment]
> Est-ce qu'un panneau latéral tel que tu l'as prévu pour les "featureinfo" ne serait pas une alternative?

Un inconvénient est peut-être la largeur réduite de ce panneau.

**Comment by jaykayone** [comment]
oui, "actuel" c'est le map.geoportail.lu actuel

**Comment by petzlux** [comment]
Je ne vois pas d'inconvénient majeur a une fenêtre modale , avec un button clair pour fermer, ca se prête alors aussi bien pour le mobile ou l'on peut utiliser toute la fenêtre.

Tout popover assez large est fonctionellement similaire a un modal de toute facon. Un popover en général contient juste un contenu court, un tooltip par exemple ...

**Comment by petzlux** [comment]
Autre question est quels sont les metadonnées qu'on veut afficher, la quantité de contenu dicte aussi quel manière d'affichage on doit choisir.

**Comment by jaykayone** [comment]
Le contenu est le même qu'aujourd'hui

en moyenne, c'est ceci, mais les description peuvent être bcp plus longues
![screen shot 2015-02-02 at 09 09 37]

(https://cloud.githubusercontent.com/assets/1518019/5997423/45407afe-aabb-11e4-8fd9-694b36a2bcab.png)

je suis finalement pour une solution à la geoadmin (sans ouverture multiple). ça me semble le meilleur compromis

**Comment by pgiraud** [comment]
OK. Merci.
