### ISSUE TITLE
Add  pytz-2014.10-py2.7.egg to .gitignore

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#202]
The build process adds `pytz-2014.10-py2.7.egg` as an untracked file. Should it be added to `.gitignore`?

**Comment by sbrunner** [comment]
He isn't in the `.eggs` folder ?
We added the `.eggs` folder to the `.gitignore` for him ...

**Comment by elemoine** [comment]
It's not in my case. It's at the root of the repo.

**Comment by elemoine** [comment]
The problem is gone.
