### ISSUE TITLE
Interrogation clic-droit

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#205]
Avec le géoportail actuel il est possible de faire un clic-droit pour obtenir un certain nombre d'informations relatives à la position géographique cliquée.

Voici à quoi ressemble la popup de résultats :

![right-click-popup](https://cloud.githubusercontent.com/assets/76594/5976216/99a60690-a88b-11e4-89ff-79f3ee1925e3.png)

La popup contient donc :

* des permaliens
* un QR code (permalien)
* des liens liés au routing
* la position du point selon 4 systèmes de projection

Questions :

* conserve-t-on cette interrogation/popup clic-droit ?
* quelles informations y mettons-nous ?

**Comment by jaykayone** [comment]
ce n'est pas primordial, je propose que ce soit réalisé par @rmichaelis ou @petzlux le moment venu.

**Comment by petzlux** [comment]
utiliser la fenetre infos pour afficher informations
