### ISSUE TITLE
Sélection de l'échelle [c2c/lux]

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#206]
Get from #29
Restant c2c 01/01/2015 1j
Restant c2c 01/02/2015 fini

---

Une directive `ngeoScaleselector` a été développée dans ngeo pour cette fonctionnalité. Voir https://github.com/camptocamp/ngeo/pull/150.

Cette directive utilise le plugin `dropdown` de Bootstrap. L'exemple `scaleselector` dans ngeo montre comment utiliser cette directive, et comment la configurer pour que le mode "dropup" plutôt que "dropdown" soit utilisé.

Voici un lien vers l'exemple `scaleselector` utilisant cette directive : http://camptocamp.github.io/ngeo/master/scaleselector.html.

Pour rappel, la "dropup" de sélection d'échelle est à placer dans un panel collapsible sur la carte :

![map-information-panel](https://cloud.githubusercontent.com/assets/76594/5976316/a55d906a-a88c-11e4-87a5-add3920011aa.png)

**Comment by jaykayone** [comment]
intégration à faire par @petzlux

**Comment by jaykayone** [comment]
cf #250
