### ISSUE TITLE
openlayers controls - incorrect display

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#207]
Characters are shown in the fullextent and fullscreen buttons.
![screenshot from 2015-02-02 09 54 17](https://cloud.githubusercontent.com/assets/319774/5997918/a6d2a99e-aac1-11e4-8a8d-73b4de27ddc1.png)

**Comment by elemoine** [comment]
@pgiraud I just added the `bug` and `Base/Navigation` labels. I think it makes sense to try to add proper labels when we create new issues.

**Comment by jaykayone** [comment]
OK, can reproduce on current state of master @rmichaelis

**Comment by rmichaelis** [comment]
This issue is introduced with the new version of OpenLayers.
I can now reproduce it on my environment.

**Comment by rmichaelis** [comment]
fixed

**Comment by pgiraud** [comment]
Here's what I get now:
![screenshot from 2015-02-03 09 44 38](https://cloud.githubusercontent.com/assets/319774/6016980/5ae05306-ab89-11e4-82a0-24f67b55f853.png)

**Comment by jaykayone** [comment]
can you try incognito mode?
we don't have the problem ..
shift-reload helps

**Comment by pgiraud** [comment]
My bad.
