### ISSUE TITLE
Permaliens: Paramètre spécifique [c2c, lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#209]
Get from #36 

Restant c2c 01/02/2015 : 0.5j (implémenter la base, explication)
Restant c2c 01/03/2015 : 1j (implémenter la base, explication)

Note : j'ai ajouté ½ journée pour prendre en compte les permaliens "dièse" et cookies/localStorage, même si je ne connais encore pas les implications.

**Comment by jaykayone** [comment]
Il faudra s'assurer que les anciens permaliens (paramètres URL) et les permaliens "dièse" ainsi qu'un cookie qui contient les paramètres puissent fonctionner en parallèle

**Comment by pgiraud** [comment]
cookie ou localStorage

**Comment by elemoine** [comment]
> Il faudra s'assurer que les anciens permaliens (paramètres URL) et les permaliens "dièse"

Jeff, qu'entends-tu par permaliens "dièse" ? Merci.

**Comment by geoportallux** [comment]
on avait d�fini que les permaliens soient mis � jour en permanence dans l'URL.
comme chez swisstopo ... en fait je viens de v�rifier, je vois que maintenant ils utilisent des param�tres URL normaux, avant ils les mettaient dans le di�se (https://support.google.com/richmedia/answer/190941?hl=fr).

finalement, il n'y a pas de raison pour nous de favoriser les di�ses ..

**Comment by elemoine** [comment]
> finalement, il n'y a pas de raison pour nous de favoriser les dièses ..

Ok, très bien comme ça, et ça correspond à ce que j'ai mis en place dans https://github.com/Geoportail-Luxembourg/geoportailv3/pull/350.

**Comment by elemoine** [comment]
Pour être compatible avec l'ancien système faut-il que x et y (et zoom) dans les permaliens utilisent la projection LUREF ?

**Comment by geoportallux** [comment]
oui je pr�f�rerais

**Comment by elemoine** [comment]
Concernant le localStorage quel est le besoin exactement ? Faut-il retrouver les états de la carte/application d'une « session » navigateur à l'autre ? En d'autres termes faut-il reposer sur [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) ou sur [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) ?

**Comment by elemoine** [comment]
> oui je pr�f�rerais

Ok, je vais regarder ça.

**Comment by geoportallux** [comment]
oui, d'une session à l'autre.
les gens ont pris goût à ça avec la version mobile

**Comment by elemoine** [comment]
> oui je pr�f�rerais

Et pour le zoom ? Est-ce que les niveaux de zoom de l'ancienne application corresponde aux niveaux de zoom de la nouvelle ?

**Comment by geoportallux** [comment]
Et pour le zoom ? Est-ce que les niveaux de zoom de l'ancienne application corresponde aux niveaux de zoom de la nouvelle ?


non ... c'est une bonne question, on doit faire une table de mapping

**Comment by elemoine** [comment]
> non ... c'est une bonne question, on doit faire une table de mapping

Est-ce quelqu'un est en mesure de me fournir ce mapping?

**Comment by geoportallux** [comment]
commence par
(ancien système, nouveau système)
0, 9
..
9,18
10,19
on ajustera en cas de besoin


Jeff Konnen

Chargé d’études – informaticien/Chef de projet



LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG

Ministère des Finances

Administration du cadastre et de la topographie

Service informatique & Service géoportail



54, avenue Gaston Diderich<x-apple-data-detectors://1/0> . L-1420 Luxembourg

Tél. (+352) 44901-261<tel:(+352)%252044901-261> . Fax (+352) 44901-333<tel:(+352)%252044901-333>

E-mail: jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>

www.act.public.lu<http://www.act.public.lu/> www.geoportail.lu<http://www.geoportail.lu/>

On 18.03.2015, at 15:30, Éric Lemoine <notifications@github.com<mailto:notifications@github.com>> wrote:


non ... c'est une bonne question, on doit faire une table de mapping

Est-ce quelqu'un est en mesure de me fournir ce mapping?

**Comment by elemoine** [comment]
> commence par (ancien système, nouveau système) 0, 9 .. 9,18 10,19 on ajustera en cas de besoin

Un simple décalage de 9 donc ?

**Comment by geoportallux** [comment]
oui, pour l'instant, mais je pr�f�re un tableau si on devait faire des ajustements plus tard

**Comment by elemoine** [comment]
Ok. Je note aussi que le minZoom dans la vue est égal à 8 actuellement, et pas 9 comme ton tableau de correspondance semble l'indiquer.

**Comment by geoportallux** [comment]
ok, j'improvise, je suis en route :)
Le plus important c'est que 10 correspond � 19, le reste c'est de la d�duction

**Comment by jaykayone** [comment]
see #375
