### ISSUE TITLE
QR code dans ngeo [c2c]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#211]
Get from #36 

Restant c2c 01/01/2015 1j
Restant c2c 01/02/2015 1j

**Comment by jaykayone** [comment]
is this going to be similar to https://project.camptocamp.com/viewvc/geoportail_luxembourg/trunk/geoadmin/geoadmin/geoadmin/controllers/shorten.py?view=markup ? 

In my implementation of the print template, I need a controller that generates an image for the QR code. Is it already in c2cgeoportal, will it be, or should I add a controller by myself?

**Comment by sbrunner** [comment]
With ngeo the QR code will be probably generate in client side :-) (=> ngeo only)

**Comment by jaykayone** [comment]
So I will have to write a controller nevertheless to get a qrcode in the print template, is this correct?

**Comment by sbrunner** [comment]
I asked the question to the print developers: https://github.com/mapfish/mapfish-print/issues/199

**Comment by jaykayone** [comment]
implementing a qrcode - controller is really not complicated. I am not sure we should "waste time" to enhance ngeo and mfprint for this.

**Comment by elemoine** [comment]
Décision : l'équipe Luxembourg implémente un controller qrcode dans le projet geoportailv3.
