### ISSUE TITLE
Geocoding in R with Geoportail API

### ISSUE THREAD

**Issue by dknykrisztina** [Geoportail-Luxembourg/geoportailv3#2147]
Hello,
I'm quite new here but I'm searching for geocoding script to get lon-lat coordinates for addresses with this API, but my all database and work is in R. Could anybody help where and how can I start?
Tnx

**Comment by rmichaelis** [comment]
Hello,

The geoportal API is a javascript client api that is documented here : https://apiv3.geoportail.lu/proj/1.0/build/apidoc/
with some examples here : 
https://apiv3.geoportail.lu/proj/1.0/build/apidoc/examples/

However, the javascript is calling an undocumented webservice that you could use to geocode your address.
You can either provide the full address and let the webservice decompose it, just like that :
https://apiv3.geoportail.lu/geocode/search?queryString=54%20avenue%20gaston%20diderich%201420%20luxembourg

or you can provide each component of the address like this : 
https://apiv3.geoportail.lu/geocode/search?num=54&street=avenue%20gaston%20diderich&zip=1420&locality=luxembourg

The webservice response is in json and contains :
- the geometry expressed in both wgs84  and in LUREF.
- an accuracy.
When accuracy equals 1, that means response accuracy is country
When accuracy equals 5, that means response accuracy is locality
When accuracy equals 6, that means response accuracy is street
When accuracy equals 8, that means response accuracy is address

- a "ratio". ratio contains a value between 1 and 0 and could be viewed as a percentage of how much we trust the response.

example : 
54 avenue gaston dideri ch 1420 luxembourg ==> ratio 1
54 avenue gastaun diederich 1420 luxembourg ==> ratio : 0.94


I'm not familiar with R, but I suppose that a webservice call could be integrated.

I hope it helps,

Best Regards,

**Comment by dknykrisztina** [comment]
Hello,
Thanks everything, I´ve found a solution for the geocoding, so now at least I have the results.
Regards
