### ISSUE TITLE
Outil de mesure, (distance, surface, azimut(altitude), ngeo [c2c]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#215]
Get from #33

Restant c2c 01/01/2015 5j
Restant c2c 01/02/2015 5j

 * [x] Distance
 * [x] Surface
 * [x] Azimut
 * [ ] Altitude

**Comment by pgiraud** [comment]
Un travail de design préalable est nécessaire.

**Comment by pgiraud** [comment]
Dans l'offre, il n'est pas précisé si les outils de mesure (distance et surface) doivent afficher la valeur de la mesure au fur et à mesure comme c'est le cas actuellement.
Mais, dans l'offre toujours, dans la section "4.2.5 Dessin et marker", il est prévu d'adapter OL3 afin d'afficher les mesures au fur et à mesure du dessin.
Cette fonctionnalité (ou exemple qui montre que c'est possible) n'existe pas dans OL3 actuellement.
Cette fonctionnalité est-elle essentielle ?

**Comment by pgiraud** [comment]
Ce matin, Éric a proposé de discuter un peu de ce point. Nous avons décidé de tester la faisabilité, avec OL3, d'affichar la mesure au fur et à mesure du dessin. Bien lui en a pris, car j'ai pu montrer assez rapidement que nous avions tout ce qu'il nous fallait pour le faire.

**Comment by pgiraud** [comment]
Il y a une pull request en cours de review.
https://github.com/openlayers/ol3/pull/3206
https://cloud.githubusercontent.com/assets/319774/6044255/60f6dd46-ac92-11e4-86b7-96fa0bc36b4e.gif

**Comment by elemoine** [comment]
Voici le lien vers la PR ol3 de Pierre : https://github.com/openlayers/ol3/pull/3206. Il y a un screencast qui montre le résultat.

**Comment by jaykayone** [comment]
génial!!

**Comment by jaykayone** [comment]
cf #259
