### ISSUE TITLE
Integration outil de mesure [lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#216]
Get from #33 

 * [x] Distance
 * [x] Surface
 * [x] Azimut
 * [x] Altitude

**Comment by jaykayone** [comment]
pour distance et surface, les exemples OL sont là.
quid pour azimut et profile?

**Comment by jaykayone** [comment]
cf #217

**Comment by elemoine** [comment]
@jaykayone, quel est le rapport avec #217 ?

**Comment by jaykayone** [comment]
sorry, wrong link. corrected

On Mon, Feb 23, 2015 at 11:23 AM, Éric Lemoine <notifications@github.com>
wrote:

> @jaykayone <https://github.com/jaykayone>, quel est le rapport avec #217
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/217> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/216#issuecomment-75518583>
> .
>



-- 
Jeff Konnen
