### ISSUE TITLE
Opacity ruler is ugly with Firefox 65

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#2164]
![capture](https://user-images.githubusercontent.com/5594996/52216881-8d75ef80-2897-11e9-9cd8-7e14d7abf36d.PNG)

**Comment by PitWenkin** [comment]
Somehow the 'height: 5px;' rule in '#sidebar input[type="range"]::-moz-range-track' is not applied
 
Placing 'height: 5px;' rule in '#sidebar input[type="range"]' seems to fix this issue (only tested on Firefox 65 & Safari 11.1)

**Comment by rmichaelis** [comment]
@PitWenkin Thank for the review.
The problem is not related to the component height but to the component background color.
