### ISSUE TITLE
Donnée selectionnée / Ordre des couches [c2c, lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#217]
Get from #32 
Restant c2c 01/01/2015 2j
Restant c2c 01/02/2015 fini

 * [ ] Intégration [lux]

**Comment by elemoine** [comment]
Voir ce commentaire pour le travail d'intégration : https://github.com/Geoportail-Luxembourg/geoportailv3/issues/32#issuecomment-72057153.

**Comment by jaykayone** [comment]
A faire par @rmichaelis

**Comment by pgiraud** [comment]
@elemoine doit d'abord finaliser un patch pour supporter les touch events.

**Comment by elemoine** [comment]
Voici l'issue ngeo : https://github.com/camptocamp/ngeo/issues/154.

**Comment by elemoine** [comment]
Comme indiqué dans l'issue ngeo j'ai noté un bug dans Closure Library. J'ai fait un PR pour Closure Library mais il n'est pas encore mergé. Nous sommes donc en attente.

**Comment by jaykayone** [comment]
si je comprends bien, ce patch concerne le touch. nous pouvons donc déjà implémenter la fonctionnalité côté desktop et attendre que ta PR soit mergée?

**Comment by elemoine** [comment]
Oui, je suis d'accord. Un développeur de Closure Library m'a conseillé de mieux expliquer le problème dans ma PR. Je vais tenter de faire ça cette semaine.

**Comment by elemoine** [comment]
Je suis acutellement assigné à cette tâche. Faut-il réassigner ?

**Comment by jaykayone** [comment]
A toi de me dire :) si pour toi tout est prêt, on la passe à @rmichaelis

**Comment by elemoine** [comment]
En fait il faudrait qu'on merge ma branche ngeo avant. Je vous tiens au courant.

**Comment by elemoine** [comment]
Ok, le [PR ngeo](https://github.com/camptocamp/ngeo/pull/170) a été mergé. C'est l'exemple layerorder qu'il faut regarder.

**Comment by elemoine** [comment]
> Oui, je suis d'accord. Un développeur de Closure Library m'a conseillé de mieux expliquer le problème dans ma PR. Je vais tenter de faire ça cette semaine.

Pour info, j'ai mis à jour ma PR à closure-library pour bien expliquer le problème et la correction, mais je n'ai pas de nouvelle.

**Comment by jaykayone** [comment]
OK, à faire par @petzlux

**Comment by elemoine** [comment]
À noter l'utilisation du service `ngeoSyncArrays` dans l'exemple `layerorder`. Il faut utiliser ce service pour le "re-ordering" des layers.

**Comment by petzlux** [comment]
#336

**Comment by petzlux** [comment]
After some styling adjustments by @pgiraud , can this be considered done ? I quite like that there is some contrast and simplification in styling between dragged element and other elements ...

**Comment by pgiraud** [comment]
Yes.
This is still not perfect on mobile, but it can be addressed in a different issue.
