### ISSUE TITLE
Sélection des thèmes [c2c/lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#220]
Get from #31 
* [x] Service return backgrounds and themes [c2c]
* [x] Central service to manage themes web service
* [ ] themes error handling [c2c]
* [ ] Integration [lux]

Restant c2c 01/02/2015 1j
Restant c2c 01/03/2015 0.5j (themes error handling)

**Comment by elemoine** [comment]
> Central service to manage themes web service + themes error handling [c2c]

En ce qui concerne ce point : avec le travail de Stéphane dans c2cgeoportal la réponse du service de `themes` va contenir les informations relatives à tous les thèmes, toutes les couches overlay, et toutes les couches background. Il faut donc, côté client, créer un composant central, un service Angular en fait, de gestion des informations retournées par ce web service. Ce service central sera utilisé par plusieurs composants de l'application : catalog, backgroundlayer, etc.

**Comment by jaykayone** [comment]
quid de l'aspect CSS? @pgiraud avait fait des propositions d'UI pour le sélectionneur de thèmes?

**Comment by pgiraud** [comment]
Je crois que nous pouvons garder ce qui avait été proposé dans les templates initiaux.
![screenshot from 2015-02-03 09 36 30](https://cloud.githubusercontent.com/assets/319774/6016909/6cb29766-ab88-11e4-9463-9d3d5eb2c755.png)

cf. http://dev.camptocamp.com/files/lux/geoportail_lux_specs/cartes/

**Comment by jaykayone** [comment]
cf aussi https://github.com/Geoportail-Luxembourg/geoportailv3/issues/22
Je propose de mettre @petzlux dessus, avec appui css de @pgiraud si nécessaire

**Comment by jaykayone** [comment]
switched from @petzlux to @rmichaelis, so that @petzlux can concentrate on #searchfield for now
