### ISSUE TITLE
Géolocalisation [c2c, integration: lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#229]
Get from #29 
Restant c2c 01/01/2015 1j
Restant c2c 01/02/2015 fini (à voir si le usecase est bien couvert)

**Comment by elemoine** [comment]
Voici l'exemple ngeo : http://camptocamp.github.io/ngeo/master/geolocation.html.

**Comment by elemoine** [comment]
Action @elemoine : donner plus de détails sur le fonctionnement.

**Comment by elemoine** [comment]
Dans la lib ngeo il y a le décorateur `ngeoDecorateGeolocation` qui permet d'utiliser `ng-model` pour activer/désactiver le tracking du composant `ol.Geolocation`. C'est en fait la seule chose fournie par la lib ngeo. Tout le reste (affichage du point, de la zone de précision, etc.) eest fait dans l'exemple `geolocation.html`. Voir https://github.com/camptocamp/ngeo/blob/master/examples/geolocation.js.

**Comment by jaykayone** [comment]
ok alors c'est l'intégration dans notre page qui devrait se faire un peu autrement

lorsque je dézoome je voudrais qu'il garde ce niveau de zoom pendant que je me déplace

**Comment by elemoine** [comment]
> lorsque je dézoome je voudrais qu'il garde ce niveau de zoom pendant que je me déplace

En effet. Dans l'exemple un `setZoom(17)` est fait à chaque fois qu'une nouvelle position est obtenue.

**Comment by jaykayone** [comment]
cf #265
