### ISSUE TITLE
Finalisation du layout [c2c]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#230]
Get from #27 
Restant c2c 01/02/2015 1j
Restant c2c 01/03/2015 1j
Restant c2c 01/04/2015 1j
Restant c2c 01/05/2015 1j

**Comment by jaykayone** [comment]
dans http://dev.camptocamp.com/files/lux/geoportail_lux_specs/cartes/ on voit que le logo cache aussi une fonction pour faire afficher le menu du cms. @petzlux as-tu une proposition pour intégrer ce menu sans devoir le dupliquer?

**Comment by pgiraud** [comment]
@jaykayone peux-tu ouvrir une nouvelle issue pour le menu ? Nous souhaitons fermer cette issue qui est devenue trop "générale".

**Comment by jaykayone** [comment]
oublions ce point pour l'instant.
tu peux le fermer
