### ISSUE TITLE
Mobile (contrôles à afficher) ? [lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#232]
Get from #27

**Comment by elemoine** [comment]
Il s'agit de discuter des fonctionnalités qu'on veut/veut pas sur mobile.

**Comment by elemoine** [comment]
Déjà discuté ici : https://github.com/Geoportail-Luxembourg/geoportailv3/issues/43. https://github.com/Geoportail-Luxembourg/geoportailv3/issues/43 est l'issue à l'utiliser si on besoin de continuer à discuter.
