### ISSUE TITLE
Search Autocomplete UI, who implements ?  

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#235]
Is this C2C , as part of ngeo ?

**Comment by elemoine** [comment]
Can we please discuss what the UI will look like? What types of results will be provided? I think we should specify it before deciding where it will be implemented.

**Comment by elemoine** [comment]
I think you're abusing the `help wanted` label a bit :-)

**Comment by petzlux** [comment]
eric, so what does the tag apply to ?

**Comment by elemoine** [comment]
Sorry, I am bit pedantic here. My apologies. To me `help wanted` means "I'm blocked, please help me so I can move forward". And `question` means "I have a question/I need to discuss something". So, to me, we should either use `question` or `help wanted`, but not both at the same time. But this may just be my interpretation of the flags…

**Comment by petzlux** [comment]
Okay, I understand then :-) no worries

**Comment by jaykayone** [comment]
I just had a look at the new geo.admin.ch search component and I think we could try to copy it as much as possible (without the sharing stuff)

**Comment by jaykayone** [comment]
to be analyzed by c2c if something is done in ngeo

**Comment by jaykayone** [comment]
At the last meeting, c2c decided to implement such a component in ngeo. we'll have to wait for it to ready to make an implmentation in the project

**Comment by elemoine** [comment]
This issue was just a question, and the question is now answered, so closing…
