### ISSUE TITLE
Language Switcher UI adjustments

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#243]
Gap between tiles is too large, and also slight overlap on top with header bar

**Comment by elemoine** [comment]
FWIW, I agree.

**Comment by jaykayone** [comment]
In the design, I also saw that the color is theme-dependant
![screen shot 2015-02-04 at 11 48 54](https://cloud.githubusercontent.com/assets/1518019/6039125/d7d22b20-ac63-11e4-9013-5cce09e7cabf.png)
