### ISSUE TITLE
theme webservice throws error when user has got a role

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#254]
tested with the theme "eau" and a user having roleid = 1
demo on demosite will follow asap

**Comment by jaykayone** [comment]
voici le contenu du logfile:

[Thu Feb 12 14:49:38.697974 2015] [:error] [pid 25124] 2015-02-12 14:49:38,697 INFO  [c2cgeoportal.views.entry][Dummy-1] User 'fk' logged in.
[Thu Feb 12 14:49:52.612850 2015] [:error] [pid 25124] [remote 10.111.80.101:164] Error - <class 'sqlalchemy.exc.ArgumentError'>: All selectables passed to CompoundSelect must have identical numbers of columns; select #1 has 24 columns, select #2 has 31
[Thu Feb 12 14:49:52.614459 2015] [:error] [pid 25124] [remote 10.111.80.101:164] URL: http://devv3.geoportail.lu/main/wsgi/themes?min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2
[Thu Feb 12 14:49:52.614487 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
[Thu Feb 12 14:49:52.614492 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   app_iter = self.application(environ, sr_checker)
[Thu Feb 12 14:49:52.614497 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
[Thu Feb 12 14:49:52.614525 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   return self.app(environ, start_response)
[Thu Feb 12 14:49:52.614545 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Thu Feb 12 14:49:52.614591 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = request.get_response(self.app)
[Thu Feb 12 14:49:52.614596 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1320 in send
[Thu Feb 12 14:49:52.614615 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   application, catch_exc_info=False)
[Thu Feb 12 14:49:52.614628 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1284 in call_application
[Thu Feb 12 14:49:52.614659 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   app_iter = application(self.environ, start_response)
[Thu Feb 12 14:49:52.614691 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 242 in __call__
[Thu Feb 12 14:49:52.614716 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = self.invoke_subrequest(request, use_tweens=True)
[Thu Feb 12 14:49:52.614746 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 217 in invoke_subrequest
[Thu Feb 12 14:49:52.614771 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = handle_request(request)
[Thu Feb 12 14:49:52.614800 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/tweens.py', line 21 in excview_tween
[Thu Feb 12 14:49:52.614825 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = handler(request)
[Thu Feb 12 14:49:52.614864 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 95 in tm_tween
[Thu Feb 12 14:49:52.614893 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   reraise(*exc_info)
[Thu Feb 12 14:49:52.614914 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 76 in tm_tween
[Thu Feb 12 14:49:52.614956 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = handler(request)
[Thu Feb 12 14:49:52.614978 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 163 in handle_request
[Thu Feb 12 14:49:52.615000 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = view_callable(context, request)
[Thu Feb 12 14:49:52.615024 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 355 in rendered_view
[Thu Feb 12 14:49:52.615053 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   result = view(context, request)
[Thu Feb 12 14:49:52.615082 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 477 in _class_requestonly_view
[Thu Feb 12 14:49:52.615088 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   response = getattr(inst, attr)()
[Thu Feb 12 14:49:52.615092 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 1167 in themes
[Thu Feb 12 14:49:52.615095 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   role_id, interface, True, version, catalogue, min_levels
[Thu Feb 12 14:49:52.615101 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 1013 in decorate
[Thu Feb 12 14:49:52.615133 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   should_cache_fn)
[Thu Feb 12 14:49:52.615137 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 640 in get_or_create
[Thu Feb 12 14:49:52.615140 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   async_creator) as value:
[Thu Feb 12 14:49:52.615143 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 158 in __enter__
[Thu Feb 12 14:49:52.615146 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   return self._enter()
[Thu Feb 12 14:49:52.615149 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 98 in _enter
[Thu Feb 12 14:49:52.615151 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   generated = self._enter_create(createdtime)
[Thu Feb 12 14:49:52.615154 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 149 in _enter_create
[Thu Feb 12 14:49:52.615159 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   created = self.creator()
[Thu Feb 12 14:49:52.615162 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 612 in gen_value
[Thu Feb 12 14:49:52.615165 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   created_value = creator()
[Thu Feb 12 14:49:52.615168 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 1009 in creator
[Thu Feb 12 14:49:52.615186 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   return fn(*arg, **kw)
[Thu Feb 12 14:49:52.615221 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 563 in _themes
[Thu Feb 12 14:49:52.615247 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   layers = self._layers(role_id, version, interface)
[Thu Feb 12 14:49:52.615289 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 1013 in decorate
[Thu Feb 12 14:49:52.615313 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   should_cache_fn)
[Thu Feb 12 14:49:52.615337 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 640 in get_or_create
[Thu Feb 12 14:49:52.615366 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   async_creator) as value:
[Thu Feb 12 14:49:52.615391 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 158 in __enter__
[Thu Feb 12 14:49:52.615414 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   return self._enter()
[Thu Feb 12 14:49:52.615443 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 98 in _enter
[Thu Feb 12 14:49:52.615467 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   generated = self._enter_create(createdtime)
[Thu Feb 12 14:49:52.615495 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 149 in _enter_create
[Thu Feb 12 14:49:52.615522 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   created = self.creator()
[Thu Feb 12 14:49:52.615553 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 612 in gen_value
[Thu Feb 12 14:49:52.615583 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   created_value = creator()
[Thu Feb 12 14:49:52.615612 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 1009 in creator
[Thu Feb 12 14:49:52.615636 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   return fn(*arg, **kw)
[Thu Feb 12 14:49:52.615665 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 535 in _layers
[Thu Feb 12 14:49:52.615699 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   query = self._create_layer_query(role_id, version)
[Thu Feb 12 14:49:52.615791 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 156 in _create_layer_query
[Thu Feb 12 14:49:52.615848 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   q = q.union(get_protected_layers_query(role_id))
[Thu Feb 12 14:49:52.615891 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 1417 in union
[Thu Feb 12 14:49:52.615930 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   expression.union(*([self] + list(q))))
[Thu Feb 12 14:49:52.615976 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '<string>', line 2 in union
[Thu Feb 12 14:49:52.616026 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py', line 1834 in _create_union
[Thu Feb 12 14:49:52.616072 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   return CompoundSelect(CompoundSelect.UNION, *selects, **kwargs)
[Thu Feb 12 14:49:52.616120 2015] [:error] [pid 25124] [remote 10.111.80.101:164] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/sqlalchemy/sql/selectable.py', line 1809 in __init__
[Thu Feb 12 14:49:52.616160 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   n + 1, len(s.c._all_columns))
[Thu Feb 12 14:49:52.616220 2015] [:error] [pid 25124] [remote 10.111.80.101:164] ArgumentError: All selectables passed to CompoundSelect must have identical numbers of columns; select #1 has 24 columns, select #2 has 31
[Thu Feb 12 14:49:52.616300 2015] [:error] [pid 25124] [remote 10.111.80.101:164] 
[Thu Feb 12 14:49:52.616338 2015] [:error] [pid 25124] [remote 10.111.80.101:164] 
[Thu Feb 12 14:49:52.616387 2015] [:error] [pid 25124] [remote 10.111.80.101:164] CGI Variables
[Thu Feb 12 14:49:52.616436 2015] [:error] [pid 25124] [remote 10.111.80.101:164] -------------
[Thu Feb 12 14:49:52.616485 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   AUTH_TYPE: 'cookie'
[Thu Feb 12 14:49:52.616535 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   CONTEXT_DOCUMENT_ROOT: '/var/www/html'
[Thu Feb 12 14:49:52.616578 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   DOCUMENT_ROOT: '/var/www/html'
[Thu Feb 12 14:49:52.616624 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   GATEWAY_INTERFACE: 'CGI/1.1'
[Thu Feb 12 14:49:52.616670 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_ACCEPT: 'application/json, text/plain, */*'
[Thu Feb 12 14:49:52.616737 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_ACCEPT_ENCODING: 'gzip, deflate, sdch'
[Thu Feb 12 14:49:52.616752 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_ACCEPT_LANGUAGE: 'en,en-US;q=0.8,fr;q=0.6,de;q=0.4'
[Thu Feb 12 14:49:52.616756 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_CACHE_CONTROL: 'max-age=0'
[Thu Feb 12 14:49:52.616759 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_CONNECTION: 'Keep-Alive'
[Thu Feb 12 14:49:52.616766 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_COOKIE: 'auth_tkt_main="8889276cb84b502e3bceffef9a0d4a883929795d1a4bb25fe185cd90e0a9b04a11e3a29aa1ba5f506c4e9e5f0d54185520aa85077048e6beb95326969d1b01b054dcaf72Zms%3D!userid_type:b64unicode"; auth_tkt_main="8889276cb84b502e3bceffef9a0d4a883929795d1a4bb25fe185cd90e0a9b04a11e3a29aa1ba5f506c4e9e5f0d54185520aa85077048e6beb95326969d1b01b054dcaf72Zms%3D!userid_type:b64unicode"'
[Thu Feb 12 14:49:52.616771 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_HOST: 'devv3.geoportail.lu'
[Thu Feb 12 14:49:52.616774 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_REFERER: 'http://devv3.geoportail.lu/main'
[Thu Feb 12 14:49:52.616777 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_USER_AGENT: 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36'
[Thu Feb 12 14:49:52.616788 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_X_FORWARDED_FOR: '10.202.9.53'
[Thu Feb 12 14:49:52.616798 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_X_FORWARDED_HOST: 'devv3.geoportail.lu'
[Thu Feb 12 14:49:52.616819 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   HTTP_X_FORWARDED_SERVER: 'devv3.geoportal.lu'
[Thu Feb 12 14:49:52.616830 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   PATH_INFO: '/themes'
[Thu Feb 12 14:49:52.616834 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   PATH_TRANSLATED: '/var/www/html/themes'
[Thu Feb 12 14:49:52.616836 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   QUERY_STRING: 'min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2'
[Thu Feb 12 14:49:52.616839 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REMOTE_ADDR: '10.111.80.101'
[Thu Feb 12 14:49:52.616875 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REMOTE_PORT: '38634'
[Thu Feb 12 14:49:52.616975 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REMOTE_USER_DATA: u'userid_type:b64unicode'
[Thu Feb 12 14:49:52.617032 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REMOTE_USER_TOKENS: ['']
[Thu Feb 12 14:49:52.617085 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REQUEST_METHOD: 'GET'
[Thu Feb 12 14:49:52.617151 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REQUEST_SCHEME: 'http'
[Thu Feb 12 14:49:52.617226 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   REQUEST_URI: '/main/wsgi/themes?min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2'
[Thu Feb 12 14:49:52.617281 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SCRIPT_FILENAME: '/var/www/vhosts/geoportailv3/apache/geoportailv3.wsgi'
[Thu Feb 12 14:49:52.617332 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SCRIPT_NAME: '/main/wsgi'
[Thu Feb 12 14:49:52.617370 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SCRIPT_URI: 'http://devv3.geoportail.lu/main/wsgi/themes'
[Thu Feb 12 14:49:52.617441 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SCRIPT_URL: '/main/wsgi/themes'
[Thu Feb 12 14:49:52.617493 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SERVER_ADDR: '10.113.80.80'
[Thu Feb 12 14:49:52.617546 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SERVER_ADMIN: 'root@localhost'
[Thu Feb 12 14:49:52.617596 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SERVER_NAME: 'devv3.geoportail.lu'
[Thu Feb 12 14:49:52.617648 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SERVER_PORT: '80'
[Thu Feb 12 14:49:52.617702 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SERVER_PROTOCOL: 'HTTP/1.1'
[Thu Feb 12 14:49:52.617756 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   SERVER_SOFTWARE: 'Apache/2.4.6 (Red Hat) mod_wsgi/3.4 Python/2.7.5'
[Thu Feb 12 14:49:52.618101 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   UNIQUE_ID: 'VNyvgG36yna2DvUOB1V8UgAAAAU'
[Thu Feb 12 14:49:52.618132 2015] [:error] [pid 25124] [remote 10.111.80.101:164] 
[Thu Feb 12 14:49:52.618156 2015] [:error] [pid 25124] [remote 10.111.80.101:164] 
[Thu Feb 12 14:49:52.618454 2015] [:error] [pid 25124] [remote 10.111.80.101:164] WSGI Variables
[Thu Feb 12 14:49:52.618500 2015] [:error] [pid 25124] [remote 10.111.80.101:164] --------------
[Thu Feb 12 14:49:52.618531 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   application: <fanstatic.publisher.Delegator object at 0x7f43a5fcc490>
[Thu Feb 12 14:49:52.618563 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   fanstatic.needed: <fanstatic.core.NeededResources object at 0x7f438866ed90>
[Thu Feb 12 14:49:52.618598 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.application_group: ''
[Thu Feb 12 14:49:52.618678 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.callable_object: 'application'
[Thu Feb 12 14:49:52.618697 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.enable_sendfile: '0'
[Thu Feb 12 14:49:52.618730 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.handler_script: ''
[Thu Feb 12 14:49:52.618805 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.input_chunked: '0'
[Thu Feb 12 14:49:52.618824 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.listener_host: ''
[Thu Feb 12 14:49:52.618908 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.listener_port: '80'
[Thu Feb 12 14:49:52.619005 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.process_group: 'c2cgeoportal:main'
[Thu Feb 12 14:49:52.619071 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.queue_start: '1423748992600949'
[Thu Feb 12 14:49:52.619098 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.request_handler: 'wsgi-script'
[Thu Feb 12 14:49:52.619151 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.script_reloading: '1'
[Thu Feb 12 14:49:52.619216 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   mod_wsgi.version: (3, 4)
[Thu Feb 12 14:49:52.619317 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   paste.parsed_querystring: ([('min_levels', '1'), ('amp', ''), ('interface', 'desktop'), ('amp', ''), ('catalogue', 'true'), ('amp', ''), ('version', '2')], 'min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2')
[Thu Feb 12 14:49:52.619331 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   paste.throw_errors: True
[Thu Feb 12 14:49:52.619401 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   webob._parsed_cookies: ({u'auth_tkt_main': u'8889276cb84b502e3bceffef9a0d4a883929795d1a4bb25fe185cd90e0a9b04a11e3a29aa1ba5f506c4e9e5f0d54185520aa85077048e6beb95326969d1b01b054dcaf72Zms%3D!userid_type:b64unicode'}, 'auth_tkt_main="8889276cb84b502e3bceffef9a0d4a883929795d1a4bb25fe185cd90e0a9b04a11e3a29aa1ba5f506c4e9e5f0d54185520aa85077048e6beb95326969d1b01b054dcaf72Zms%3D!userid_type:b64unicode"; auth_tkt_main="8889276cb84b502e3bceffef9a0d4a883929795d1a4bb25fe185cd90e0a9b04a11e3a29aa1ba5f506c4e9e5f0d54185520aa85077048e6beb95326969d1b01b054dcaf72Zms%3D!userid_type:b64unicode"')
[Thu Feb 12 14:49:52.619436 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   webob._parsed_query_vars: (GET([(u'min_levels', u'1'), (u'amp', u''), (u'interface', u'desktop'), (u'amp', u''), (u'catalogue', u'true'), (u'amp', u''), (u'version', u'2')]), 'min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2')
[Thu Feb 12 14:49:52.619452 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   wsgi process: 'Multithreaded'
[Thu Feb 12 14:49:52.619455 2015] [:error] [pid 25124] [remote 10.111.80.101:164]   wsgi.file_wrapper: <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f4384104e40>
[Thu Feb 12 14:49:52.619458 2015] [:error] [pid 25124] [remote 10.111.80.101:164] ------------------------------------------------------------

**Comment by sbrunner** [comment]
Thanks for the log :-)
