### ISSUE TITLE
make translations

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#258]
@sbrunner je ne retrouve plus le make target pour synchroniser les traductions avec transifex.
Comment dois-je faire?

**Comment by jaykayone** [comment]
c'est bon j'ai trouvé, c'est le help du makefile qui n'est pas à jour

**Comment by jaykayone** [comment]
la question qui reste est donc: comment mettre à jour l'aide du make pour que l'option y soit listée vu qu'il s'agit d'un target qui est défini dans geoportail_v3.mk

**Comment by elemoine** [comment]
Tu peux essager ça dans `geoportailv3.mk`:

```
include CONST_Makefile

help: extension-help

extension-help:
        @echo "geoportailv3-specific targets:"
        …
```

Non testé.

**Comment by sbrunner** [comment]
Je pensais plutôt ajouter la possibilité d'ajouter la possibilité d'ajouter des commandes à l'aide :-)

**Comment by jaykayone** [comment]
qui fait? @sbrunner?

**Comment by sbrunner** [comment]
yes :-)
