### ISSUE TITLE
Permettre d'activer une deuxième couche lorsqu'on active une couche

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#2604]
Exemple:

Lorsqu'on active la couche "Sentiers autopédestres", celà doit aussi activer la couche "Autres restrictions temporaires".
Celà doit être configurable à travers les métadonnées de la couche.

Celà ne vaut pas pour la désactivation de la couche.

**Comment by rmichaelis** [comment]
Fixed by #2619
