### ISSUE TITLE
JSAPI: Roadmap

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#2613]
pour certains sites, qui doivent pouvoir être configurés, lorsqu'ils choisissent le fonds roadmap, celà doit utiliser le style "roadmap" au lieu de "roadmap_jsapi".

Ce sont des sites qui ont payés la licence maptiler de leur côté

Voici un exemple: https://www.visitluxembourg.com/en/place/walking/circular-walk-bollendorf-pont

**Comment by rmichaelis** [comment]
done
