### ISSUE TITLE
Elevation offset in azimuth tool

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#263]
In the azimuth tool, the elevation offset should be indicated (see existing tool)

**Comment by elemoine** [comment]
@pgiraud, is this fixed? If not, and if this should be done by c2c, could you please add an estimate? In this form:

```
Restant c2c 01/03/2015 : xj
```

Thanks.

**Comment by pgiraud** [comment]
Sorry, a new issue has been created.
https://github.com/Geoportail-Luxembourg/geoportailv3/issues/303

I think that Lux have everything in their hands to do the job now.
