### ISSUE TITLE
-- github --> branches

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#267]
there are a lot of open branches in github. can everyone take 5 minutes to tidy up please?

**Comment by elemoine** [comment]
I deleted `angular-bootstrap`, `angular-ui-bootstrap`, `tp-eric`, `print-directive`, and `watchers`.

I suggest that we always prefix branches with the github username of the branch creator. E.g. `elemoine_print-directive`.

**Comment by jaykayone** [comment]
@elemoine, il reste translate qui a été créé par toi
@sbrunner: il y a une branche abandonnée  cache_buster_debug -> y en-a-t'on encore besoin?

**Comment by elemoine** [comment]
@jaykayone je viens de supprimer `translate`.

**Comment by sbrunner** [comment]
removed :-)

**Comment by jaykayone** [comment]
thanks.
not closing the issue, as it is a permanent one

**Comment by jaykayone** [comment]
@petzlux I just removed two of your branches after they had been merged.
@elemoine what about elemoine_measure?

**Comment by elemoine** [comment]
`elemoine_measure` deleted.
