### ISSUE TITLE
Lint the JS code

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#268]
It looks like we do not currently lint the JS code.

**Comment by elemoine** [comment]
This is just a typo in `CONST_Makefile`. @sbrunner, where should changes to `CONST_Makefile` go? PR to c2cgeoportal?

**Comment by sbrunner** [comment]
Yes in c2cgeoportal :-)

**Comment by elemoine** [comment]
Ok, will do. Can I still make a local change to geoportailv3 not to wait for the next update of c2cgeoportal in geoportailv3?

**Comment by sbrunner** [comment]
No problem to do the changes also in the project :-)
