### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#27]
* [x] Mockups
* [x] Layout général
* [x] Layout spécifique à chaque device
* [ ] Finalisation [c2c: 1j]
* [ ] Refactor table  en Angular UI [c2c: 1j]
* [ ] Mobile (contrôles à afficher) ? [c2c: ?]

**Comment by elemoine** [comment]
@pgiraud, est-ce qu'on peut considérer que le layout général est fait et qu'il est fait pour tous les types de devices ciblés ? (On a besoin de cette réponse pour les estimations.)

**Comment by elemoine** [comment]
Après discussion : il faut qu'on teste régulièrement l'interface sur différents navigateurs et devices, et ouvrir des issues dès que des problèmes sont détectés.
