### ISSUE TITLE
Authentification [lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#28]
* [x] Authentification (serveur) [lux]
* [x] Gestion des droits [lux]
* [x] UI de connexion [lux]
* [ ] Rechargement du catalogue après login [lux]

**Comment by rmichaelis** [comment]
@sbrunner  Qu'est-ce que tu entends par gestion des droits dans l'authentification?

**Comment by sbrunner** [comment]
Réconcilier les données en provenance de l’authentification avec les rôles de c2cgeoportal.

**Comment by rmichaelis** [comment]
Ok merci pour la réponse mais Ils n'étaient pas vraiment fâchés ;-)

**Comment by jaykayone** [comment]
rechargement du catalogue après login

**Comment by elemoine** [comment]
@jaykayone Faut-il ajouter une checkbox pour ça dans la description de l'issue ? Ce travail est lié à la centralisation du service "themes" que je dois encore faire.

**Comment by jaykayone** [comment]
ah ok, j'avais prévu que renaud le fasse, si tu l'avais prévu, mets une checkbox, ça me va :)

**Comment by elemoine** [comment]
Renaud peut le faire mais il y a une dépendance sur un travail que je dois faire de mon côté, et qui était en attente de changements côté web services des thèmes.

**Comment by jaykayone** [comment]
@elemoine, est-ce que ces changements sont mergés? 
@rmichaelis pourrait alors attaquer ce point?

**Comment by elemoine** [comment]
> @elemoine, est-ce que ces changements sont mergés?

Oui : https://github.com/Geoportail-Luxembourg/geoportailv3/pull/276.

**Comment by elemoine** [comment]
> rechargement du catalogue après login

Ce point remet en fait en cause le design du code. Actuellement le service `appThemes` récupère les thèmes une bonne fois pour toute, à son initialisation. Pour le cas du login il va falloir ajouter une fonction `reload` au service `appThemes`, et il va falloir faire en sorte que tous les composants qui reposent sur `appThemes` se mettent à jour. Par exemple, le composant catalog devra détecter que les thèmes ont été rechargés et qu'il faut mettre à jour la UI. Même chose pour le composant background layer. Rien d'insurmontable à mon avis, mais ça demande un peu de travail.
