### ISSUE TITLE
pkg_resources.VersionConflict: (js.jqgrid 4.3.1-1…

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#281]
With a recent version of c2cgeoportal I get the following error in the `pserve` console:

```
pkg_resources.VersionConflict: (js.jqgrid 4.3.1-1 (/home/elemoine/src/geoportailv3/.build/venv/lib/python2.7/site-packages), Requirement.parse('js.jqgrid==4.3.1.post1'))
```

On my machine, even though `CONST_versions.txt` and `c2cgeoportal-1.6.0dev_20150226-py2.7.egg-info/requires.txt` include `js.jqgrid==4.3.1.post1` `js.jqgrid` version `4.3.1-1` gets installed. It should be ok as `4.3.1-1` and `4.3.1.post1` actually refer to the same version. But it's not ok, because `pkg_resources` raises a `VersionConflict` exception on my machine.

It may be related to the version of `setuptools`/`distribute` I have on my machine. This is what I see in the stacktrace:

```
  File "/home/elemoine/.venvburrito/lib/python/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 600, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (js.jqgrid 4.3.1-1 (/home/elemoine/src/geoportailv3/.build/venv/lib/python2.7/site-packages), Requirement.parse('js.jqg
rid==4.3.1.post1'))
```

To fix the problem locally and temporarily I edited the files `CONST_versions.txt` and `c2cgeoportal-1.6.0dev_20150226-py2.7.egg-info/requires.txt`, to use `js.jqgrid==4.3.1-1` instead of ``js.jqgrid==4.3.1.post1`.

**Comment by jaykayone** [comment]
this seems to be solved, right?

**Comment by elemoine** [comment]
Fixed in c2cgeoportal with https://github.com/camptocamp/c2cgeoportal/pull/1278. I haven't tested whether it works in the project. I will do it and close this issue if it works as expected.

**Comment by jaykayone** [comment]
problem still present

**Comment by jaykayone** [comment]
after a cleanall, I had to do a pip install js.jqgrid==4.1.0 to make the serve mode work

**Comment by petzlux** [comment]
confirm still present here as well

**Comment by elemoine** [comment]
@jaykayone, @petzlux, https://github.com/Geoportail-Luxembourg/geoportailv3/pull/330 fixes it for you. I hope it'll fix it for you as well :-)
