### ISSUE TITLE
Measure correctness issues

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#284]
As noted in https://github.com/Geoportail-Luxembourg/geoportailv3/pull/259#issuecomment-75930828 there are measure correctness issues related to the use of the Web Mercator projection. Two options to fix the problem: reproject the geometries from EPSG:3857 to EPSG:2169 before doing the cartesian length/area calculations, or use spherical length/area calculations, as done in the ol3 [measure example](https://github.com/openlayers/ol3/blob/master/examples/measure.js#L249-L256).

**Comment by elemoine** [comment]
See https://github.com/camptocamp/ngeo/pull/172.

**Comment by pgiraud** [comment]
Needs a node modules update. Should be fixed.

**Comment by jaykayone** [comment]
OK, I confirm
