### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#29]
* [x] Composant Map
* [x] Navigation
* [ ] Contrôles openlayers dans la carte (zoom, full extent, full screen) [c2c: 1j]
* [ ] Mode plein écran [lux]
* [ ] Sélection de l'échelle [c2c: 1j] [lux ?]
* [ ] Affichage des coordonnées de la souris [lux ?]
* [ ] Affichage de l'altitude [lux ?]
* [ ] Sélection projection affichage coordonnées [lux ?]
* [ ] Géolocalisation [c2c: 1j] [lux]

**Comment by elemoine** [comment]
Le bouton "plein écran" sera au même endroit que les boutons +/- de zoom (dans la carte), et tous les boutons doivent avoir le même look&feel.

Dans un premier temps, l'équipe Luxembourg peut utiliser simplement le control FullScreen d'OpenLayers, en ajoutant ce control à la carte (qui est créée dans le `MainController`).
