### ISSUE TITLE
Measure button

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#294]
I would like to deactivate the active measure tool, when the user is closing the main measure button.

I'm not sure how I should do that. 
Is there a kind of event that I could catch when the state of the ngeo button is changing ?
Any advice ?

**Comment by elemoine** [comment]
I happened to have just created a PR for that! By chance. https://github.com/Geoportail-Luxembourg/geoportailv3/pull/295

**Comment by elemoine** [comment]
Fixed with https://github.com/Geoportail-Luxembourg/geoportailv3/pull/295.
