### ISSUE TITLE
Measure tools: guiding point not correctly aligned with cursor

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#296]
When using the measure tools, a circle follows the cursor. Unfortunately, this circle is not centered exactly on the cursor position. There's a small offset to the right.

Restant c2c 01/03/2015 : 0.5j
Restant c2c 01/04/2015 : 0.5j

**Comment by elemoine** [comment]
Camptocamp to investigate and fix this bug.

**Comment by pgiraud** [comment]
It looks like is due to the fact that the map is incorrectly sized at first. If one resizes the browser window we can clearly see that the map is stretched back to it's correct size. After that the measure guiding point is correctly placed.
