### ISSUE TITLE
background layers

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#300]
a lot of bglayers (and other layers) are currently not working

Restant c2c 01/04/2015 0.25j

**Comment by jaykayone** [comment]
One question for @sbrunner:

ortho_2013_global does not work.

the problem seems to be that it tries to get png images, but it should get jpeg according to the capabilities document: http://wmts.geoportail.lu/mapproxy_4_v3/demo/?wmts_capabilities

 <Layer>
      <ows:Title>orthogr_2013</ows:Title>
      <ows:Abstract></ows:Abstract>
      <ows:WGS84BoundingBox>
        <ows:LowerCorner>-180.0 -85.0511287798</ows:LowerCorner>
        <ows:UpperCorner>180.0 85.0511287798</ows:UpperCorner>
      </ows:WGS84BoundingBox>
      <ows:Identifier>orthogr_2013_global</ows:Identifier>
      <Style>
        <ows:Identifier>default</ows:Identifier>
      </Style>
      <Format>image/jpeg</Format>
      <TileMatrixSetLink>
        <TileMatrixSet>GLOBAL_WEBMERCATOR</TileMatrixSet>
      </TileMatrixSetLink>
      <ResourceURL format="image/jpeg" resourceType="tile"
template="http://wmts.geoportail.lu/mapproxy_4_v3/wmts/orthogr_2013_global/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.jpeg"/>
    </Layer>

**Comment by pgiraud** [comment]
We currently don't read capabilities. And the format in hard coded.
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/layerfactoryservice.js#L66

**Comment by elemoine** [comment]
Decision: we add a "image format" column to c2cgeoportal's "layer" table. @sbrunner to work on this. See https://github.com/Geoportail-Luxembourg/geoportailv3/issues/305.

**Comment by jaykayone** [comment]
OK, I will make a new migration once the field is added and provide a dmp

**Comment by jaykayone** [comment]
remarks for the other baselayers: topobw and streets are not defined in the mapproxy config. TBD

**Comment by jaykayone** [comment]
the image_type parameter now has to be used. @elemoine / @pgiraud?

**Comment by elemoine** [comment]
> the image_type parameter now has to be used. @elemoine / @pgiraud?

I created an issue for that: https://github.com/Geoportail-Luxembourg/geoportailv3/issues/355. Are we talking about the WMTS layers or the WMS layers or both here?

**Comment by jaykayone** [comment]
To be verified. I only saw an issue with WMTS. I guess that for WMS it already works correctly?

**Comment by elemoine** [comment]
> I guess that for WMS it already works correctly?

I don't think so. We only use PNG at this point. I'll look into that when I work on the project.

**Comment by jaykayone** [comment]
est-ce que ce ticket peut être fermé?

**Comment by elemoine** [comment]
Oui, toutes les couches de fond semblent fonctionner maintenant. Et nous prenons maintenant en [compte](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/layerfactoryservice.js#L133) le format des images à la construction des couches WMS.
