### ISSUE TITLE
integrate profile tool

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#301]

**Comment by jaykayone** [comment]
intégrer le code ngeo pour l'outil de profil

**Comment by pgiraud** [comment]
To start with, here's what I would do:
 - create a button in the UI,
 - link it to a linestring draw interaction,
 - listen to the event which tells that the line is drawn,
 - send a request to the elevation service,
 - get the response and build the profile with it.
The profile chart should be displayed in a div simply positioned absolutely on top of the document. No need to do more w/ styling.
