### ISSUE TITLE
Add image format column to layer table in c2cgeoportal

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#305]
Restant c2c 01/03/2015 : 0.5j
 * [ ] update the project to new version of c2cgeoportal

**Comment by elemoine** [comment]
@sbrunner Where do we stand with that issue? Could you please add estimates in the description? Thanks.

**Comment by petzlux** [comment]
is this connected to #327  ?

**Comment by sbrunner** [comment]
yes
