### ISSUE TITLE
document: write() method is strongly discouraged

### ISSUE THREAD

**Issue by PitWenkin** [Geoportail-Luxembourg/geoportailv3#3050]
Both [apiv3 ](https://apiv3.geoportail.lu/proj/1.0/build/apidoc/) and [apiv4 ](https://apiv4.geoportail.lu/proj/1.0/build/apidoc/) reference a single script line to be included in a webpage to include geoportail maps:
`https://apiv3.geoportail.lu/apiv3loader.js` and  `https://apiv4.geoportail.lu/apiv4loader.js` respectively.

Unfortunately both scripts use [document.write](https://developer.mozilla.org/en-US/docs/Web/API/Document/write) to load additional javascript and css files. Apart from this delaying the page building (https://developer.chrome.com/blog/removing-document-write/), some browser (e.g. Chrome) no longer allow the usage of document.write in external script and simply don't add those script which breaks some functions of the map.

![Chrome console](https://github.com/Geoportail-Luxembourg/geoportailv3/assets/45786226/fb9fd44c-d73b-4ee3-b55b-af972374f6f0)

I had to rewrite the content of `apiv*loader.js` into a locally hosted file to get api working again

**Comment by rmichaelis** [comment]
This problem has a still non documented solution. 
To include the js and css libraries should do the job : 
For v4 version : 
```
        <link rel="stylesheet" type="text/css" href="https://apiv4.geoportail.lu/static-ngeo/build/apiv4.css"/>
        <script src="https://apiv4.geoportail.lu/apiv4-full-async.js" type="text/javascript"></script>

```
for v3 version :
```
   <link rel="stylesheet" type="text/css" href="https://apiv3.geoportail.lu/static-ngeo/build/apiv3.css"/>
        <script src="https://apiv3.geoportail.lu/apiv3-full-async.js" type="text/javascript"></script>

```

**Comment by rmichaelis** [comment]
This solution allows the use of the async or defer keywords : 
```
      <link defer rel="stylesheet" type="text/css" href="https://apiv4.geoportail.lu/static-ngeo/build/apiv4.css"/>
      <script defer src="https://apiv4.geoportail.lu/apiv4-full-async.js" type="text/javascript"></script>
... 
<script>
window.onload = function(){
    var map = new lux.Map({
      layers: [ '1637','359'],
      layerOpacities: [0.75, 0.8],
      layerVisibilities: [false, false],
      target: 'map',
      bgLayer: 'basemap_2015_global',
      zoom: 18,
      position: [75977, 75099],
      zoomToExtent: true,
      queryableLayers: [359]
    });
};
</script>
```

**Comment by PitWenkin** [comment]
Seems to work. However apiv4.css is only partially minified
