### ISSUE TITLE
Possibilty to use a MyMap with "fit: false"

### ISSUE THREAD

**Issue by PitWenkin** [Geoportail-Luxembourg/geoportailv3#3051]
Is there a way to include the `fit: false` option in `addMyMapLayer` ?

It exists for `addGeoJSON`, `addGeoJsonObject`, `addGPX`, and `addKML` and at least for `addKML` it seems to work as described.

**Comment by rmichaelis** [comment]
This parameter already exists with the name : `fitToExtent`
example : 
`          map18.addMyMapLayer({
            mapId: '0416ef680fbe4cdaa2d8009262d1127c',
            fitToExtent: false
          }); 
`

**Comment by PitWenkin** [comment]
I did not find any documentation for `addMyMapLayer`, is there one anywhere?

Most links on https://apiv4.geoportail.lu/ and https://apiv3.geoportail.lu/ are dead …

**Comment by PitWenkin** [comment]
Sorry is was blind in the apiv3 docu, but in the apiv4 there are no properties under options
