### ISSUE TITLE
addKML onClick Handler

### ISSUE THREAD

**Issue by PitWenkin** [Geoportail-Luxembourg/geoportailv3#3052]
When adding multiple KML files with an `onClick` function, the function is executed as many times as there are KML files added.

The following script would show three alerts with 'this should only appear once' instead of one as expected …
```
var popup= function(num) {
  alert('this should only appear once');
}
var curMap = new lux.Map({
  target: 'map1',
  bgLayer: 'topo_bw_jpeg',
  zoom: 12,
  position: [76825, 75133]
});
map.addKML(1.kml',{click:true, fit: false, name: 'First', onClick: popup});
map.addKML(2.kml',{click:true, fit: false, name: 'Second', onClick: popup});
map.addKML(3.kml',{click:true, fit: false, name: 'Third', onClick: popup});
```

**Comment by rmichaelis** [comment]
Yes you're right. 
Issue is now solved on apiv4 and will be soon solved on apiv3

**Comment by PitWenkin** [comment]
I have not (yet) tried if this bug also affects other functions like `addGeoJson` …

**Comment by rmichaelis** [comment]
Issue is the same for other functions. The part of the code causing troubles is shared between all the functions.
