### ISSUE TITLE
Set zoom and extent limits

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#306]
At the moment no zoom or extent limits are set. This causes issues with scaleselector being out of bounds, and user loosing Luxembourg in sea of grey

**Comment by rmichaelis** [comment]
It could be worse... You could lose Luxembourg in 50 shades of grey instead of in a sea of grey :-)

**Comment by elemoine** [comment]
> At the moment no zoom or extent limits are set.

We do have zoom limits. The resolutions/zoom levels used in the map view are those of OSM.

**Comment by jaykayone** [comment]
If we want to set different zoom levels and extents, would we have to add them here?
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/maincontroller.js#L130

**Comment by elemoine** [comment]
> If we want to set different zoom levels and extents, would we have to add them here?
> https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/maincontroller.js#L130

Right, you can pass an array of `resolutions` in the view options.

**Comment by jaykayone** [comment]
do we have to pass the entire array of resolutions if we only want to limit the map to a maximum zoomlevel of 9 ?

The tiling scheme will stay the webmercator one, it's only to limit the extent where the user can zoom in and out.

If I define a new set of resolutions, they will be renumbered and I guess, the fakescale-chooser will have to be adapted, is that correct?

**Comment by elemoine** [comment]
Yep, `maxZoom` and `minZoom` are also view options.

**Comment by jaykayone** [comment]
@petzlux can you check this please?
