### ISSUE TITLE
Missing layer in example 8 apiv3

### ISSUE THREAD

**Issue by PitWenkin** [Geoportail-Luxembourg/geoportailv3#3060]
[Example 8 in apiv3](https://apiv3.geoportail.lu/proj/1.0/build/apidoc/examples/index.html#example8)  uses non-existing layer `386` instead of `1386`

https://github.com/Geoportail-Luxembourg/geoportailv3/blob/4622e7351ae1b8fe35ebf2556b3fa548984b6b9f/geoportal/jsapi/examples/index.html#LL248C20-L248C24

**Comment by rmichaelis** [comment]
The branch of api V3 is apiv3_master :
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/apiv3_master/geoportal/jsapi/examples/index.html#LL248C20-L248C24
