### ISSUE TITLE
Choix des données

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#31]
* [ ] Couches de fond [c2c: 2j]
* [x] Catalogue des données
* [ ] Sélection des thèmes [=> lux ?]
* [x] Modèle de données catalogue/thèmes
* [x] Mécanisme de caching
* [ ] Prise en charge de la version des fichiers statiques (cache bursting) [c2c: 0.25j]
* [x] Services Web
* [ ] Exclusion layer [c2c: 2j]

**Comment by elemoine** [comment]
Pour les couches de fond il me reste à connecter le composant des couches de fond au web service des thèmes. Il faudra aussi que je fasse du refactoring pour que la réponse du web service des thèmes soit partagé par les composants catalogue et couches de fond, à travers un service. Je pense que j'ai besoin d'½ journée pour ça.
