### ISSUE TITLE
Background layer "Carte routière" is broken

### ISSUE THREAD

**Issue by PitWenkin** [Geoportail-Luxembourg/geoportailv3#3125]
Switching to "Carte routière" provokes lots of errors in console an show an mainly empty background

Both on map.geoportail.lu as well on websites with embedded maps via API

![Screenshot 2024-01-24 at 09 59 56](https://github.com/Geoportail-Luxembourg/geoportailv3/assets/45786226/1f3f59cf-e643-4cec-a5f2-b40eef1f5448)
![Screenshot 2024-01-24 at 10 02 04](https://github.com/Geoportail-Luxembourg/geoportailv3/assets/45786226/da461f99-a44b-4062-b733-2d13e42d396a)

**Comment by rmichaelis** [comment]
Hello. Thanks for reporting the issue. We had some troubles with one of our server. This is now solved.

**Comment by PitWenkin** [comment]
Confirmed
