### ISSUE TITLE
Print coordsys

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#313]

**Comment by jaykayone** [comment]
if we use Webmercator, the scale bar will be wrong
if we use LUREF, there might be a problem to use webmercator tiles

**Comment by jaykayone** [comment]
what I don't understand in this case:

if the map coord sys is LUREF, how could the measures be wrong (@pgiraud).
I thought this was due to the fact that the map was in webmercator?

**Comment by elemoine** [comment]
The OpenLayers 3 map's projection is Web Mercator. So tiles, images and vectors displayed in the map use that projection. And, yes, this is why the measures are not correct if we use simple cartesian calculations.

**Comment by jaykayone** [comment]
That's what I thought, thanks.
And that's why I have used webmercator in my print sample
And that's where the scalebar goes wrong.
Could we open an issue for this in mfprint ?

**Comment by elemoine** [comment]
Yep,  please do. You have more information than  me about the problem.

**Comment by jaykayone** [comment]
https://github.com/mapfish/mapfish-print/issues/210
