### ISSUE TITLE
print legends

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#314]
find a way to include our legends in print.
an idea might be this:
https://project.camptocamp.com/viewvc/geoportail_luxembourg/trunk/geoadmin/geoadmin/geoadmin/controllers/print.py?view=markup

especially this part: 
  weasyprint.HTML(url).write_pdf(legend_buffer, stylesheets=[css])

**Comment by sbrunner** [comment]
Voici une possibilité pour avoir des URL absolues:
```
import requests
import html5lib
from urlparse import urljoin
url = "http://wiki.geoportail.lu/doku.php?id=fr:legend:tour_velo_national&do=export_html"
html = requests.get(url).text
document = html5lib.parse(html)
for img in document.iter("{http://www.w3.org/1999/xhtml}img"):
    img.set("src", urljoin(url, img.get("src")))
html5lib.serialize(document.findall('{http://www.w3.org/1999/xhtml}body')[0])
```

**Comment by jaykayone** [comment]
looks great, thanks!
where should this be implemented?

should we add a controller that transforms a given legend into absolute html that's then passed to the print service using the standard json object?

who should implement it?

**Comment by sbrunner** [comment]
Or having a proxy that doing this job directly, when we show the legend ...

It should be in a controller of the project.

Luxembourg team ?

**Comment by jaykayone** [comment]
OK, I'll assign it to myself.
I'll maybe come back to you during implementation

**Comment by sbrunner** [comment]
Petit description de ce que j'ai commencer à faire:
 * Dans le fichier [print.py](https://project.camptocamp.com/viewvc/geoportail_luxembourg/trunk/geoadmin/geoadmin/geoadmin/controllers/print.py?view=markup) on a aussi une gestion de la légende, comme normalement cela doit fonctionner avec JasperReport je ne le report pas sur le nouveau contrôleur!
 * Avec le print sur la ligne `css = weasyprint.CSS(string="@page{ size: %s; margin: 20px; } img {max-height: 1050px}" % (c.size))` je ne voie pas à quoi ce rapport `c.size` j'ai donc mis `"@body{ size: 595px 842px; margin: 20px; } img {max-height: 800px}"`
 * Le n'ai pas bien compris comment est structuré l'attribut légende, mais comme de toute façon on ne repose plus sur `theme.ini` je l'ai défini comme une liste de nom de légende.

**Comment by sbrunner** [comment]
First view: https://github.com/Geoportail-Luxembourg/geoportailv3/compare/legend (untested)

**Comment by jaykayone** [comment]
OK, we can discuss this further with a first example. In the print config and the themes service, all the elements should be given to generate a first example using the layer "pistes cyclables nationales".
Another good example to test the legend printing is the layer "parcels"

**Comment by jaykayone** [comment]
closes #266

**Comment by jaykayone** [comment]
what is the status here?

**Comment by jaykayone** [comment]
what's the status here @sbrunner? can we hope to have a working solution for the next meeting?
I want to be feature complete on June 15th so we can start testing

**Comment by sbrunner** [comment]
I'm waiting on response, see #467
what the deference between this issue and #467 ?

**Comment by jaykayone** [comment]
no difference
