### ISSUE TITLE
infobar remarks

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#316]
* [x] dropup list is not ordered numerically
* [x] start scale. we should either add some more levels to the scaleSelector or restrict the available levels in the map, so that map and scaleselector have the same options
* [ ] css -> the looks in the mockup http://dev.camptocamp.com/files/lux/geoportail_lux_specs/cartes/ are nicer. can we adapt the CSS to be closer to the design?

**Comment by petzlux** [comment]
regarding Point 2, see also #306

**Comment by petzlux** [comment]
![screen shot 2015-06-18 at 09 21 49](https://cloud.githubusercontent.com/assets/2540428/8226061/8a0e94c2-159b-11e5-8038-93bca0139d3b.png)

Buttons need adapting as well , @pgiraud I tried but failed miserably to make them smaller using `.btn-sm`

**Comment by petzlux** [comment]
fixed by #575
