### ISSUE TITLE
Actions sur les données sélectionnées

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#32]
* [x] Sélection/visibilité [c2c: 1j]
* [x] Transparence [c2c: 1j]
* [ ] Ordre [c2c: 2j]
* [ ] Affichage méta-données [c2c: 2j]

**Comment by elemoine** [comment]
À noter que pour l'ordre des couches Pierre et moi avons travaillé sur une directive `ngeoSortable` et un service `ngeoSyncArrays` pour la sélection des couches et le drag&drop des couches dans le layer manager. Les PRs sont https://github.com/camptocamp/ngeo/pull/148, https://github.com/camptocamp/ngeo/pull/149, et https://github.com/camptocamp/ngeo/pull/151.

La directive `ngeoSortable`, qui permet de changer l'ordre des couches, est basée sur le plugin jQuery UI Sortable. Ceci veut dire que le script de ce plugin doit être dans la page pour que la directive fonctionne. Le PR https://github.com/camptocamp/ngeo/pull/148 montre ce qui doit être fait dans le projet pour télécharger et installer jQuery UI Sortable. Bower est malheureusement nécessaire parce ce plugin n'est actuellement pas dans le dépôt npm.
