### ISSUE TITLE
Profile tool

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#324]
I try to use the ngeo profile component and I've got this error message :

ERR! compile /home/mire/geoportailv3/node_modules/ngeo/src/d3-ext/profile.js:56: ERROR - variable d3 is undeclared
ERR! compile   var bisectDistance = d3.bisector(function(d) {

Am i doing something wrong ?

**Comment by elemoine** [comment]
You have to add the d3 externs file to the list of `externs` in `build.js`. The d3 externs file is in ngeo.

**Comment by rmichaelis** [comment]
thanks, It compiles now. 
But as the d3 libraries are not in node_modules, I have now a javascript error telling me that d3 is undefined.
Should I install d3 by myself ?

**Comment by elemoine** [comment]
Yes, see https://github.com/camptocamp/ngeo/pull/173/files.

**Comment by elemoine** [comment]
@rmichaelis can we close that issue?

**Comment by rmichaelis** [comment]
Yes. thanks
