### ISSUE TITLE
Profile interaction between graph and map

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#325]
Is there any kind of interaction between the map and the profile tool ?

**Comment by pgiraud** [comment]
With the current code, we can interact between the profile chart and map, but there's currently no way to interact between map and chart.

**Comment by rmichaelis** [comment]
Could the interaction between the chart and the map be developed by Luxembourg, or should it be done by c2c ?

**Comment by pgiraud** [comment]
I think you already have everything to interact between chart and map.
From my understanding, this interaction means use the x, y coordinates of the hovered point in profile chart to show a marker on the map.
See the ngeo example to see how to listen to hover events:
https://github.com/camptocamp/ngeo/blob/master/examples/profile.js#L104

**Comment by rmichaelis** [comment]
Ok, you are right. I do it like that.
Thanks.
