### ISSUE TITLE
themes error - image_type missing after c2cgeoportal update

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#327]
@sbrunner , I think you changed c2cgeoportal (https://github.com/camptocamp/c2cgeoportal/pull/1287), to support layer_wmts.image_type, but didnt provide an alembic script to migrate geoportailv3 database ?

**Comment by petzlux** [comment]
Can this issue be closed now ?

**Comment by sbrunner** [comment]
yes => closed
