### ISSUE TITLE
Absolutely fix c2cgeoportal version ? 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#328]
Looking into issue #327 , wouldnt it be better to fix dependency to specific version of c2cgeoportal, instead of greater than version XXXX ? 

https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/setup.py#L18

**Comment by elemoine** [comment]
In the end yes, but using `>=` during this development phase sounds good to me.

**Comment by sbrunner** [comment]
+1 effectively

**Comment by rmichaelis** [comment]
quid de la solution apportée par le  #331 ?

**Comment by petzlux** [comment]
closed with https://github.com/Geoportail-Luxembourg/geoportailv3/commit/c9141a6d8d0107f0df2c067c840352823d5c7b9c
