### ISSUE TITLE
KeyError: 'mapserv_url'

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#331]
Since last cleanall, I've got an error when the application is calling the following webservice http://workshop.geoportal.lu:8081/themes?min_levels=1&interface=desktop&catalogue=true&version=2&background=bglayers

I've added the variable in vars_XXX.yaml but it seems to be not enough.

Any idea ?

**Comment by petzlux** [comment]
yes this is blocking for me as well

**Comment by sbrunner** [comment]
`.build/venv/bin/pip install c2cgeoportal==1.6.0dev-20150217`

**Comment by petzlux** [comment]
@sbrunner do you mean we need to run this command ? 

`````
wepa@workshop3-local:~/geoportailv3 (master $%)$ .build/venv/bin/pip install c2cgeoportal==1.6.0dev-20150217
Collecting c2cgeoportal==1.6.0dev-20150217
  Could not find any downloads that satisfy the requirement c2cgeoportal==1.6.0dev-20150217
  No distributions at all found for c2cgeoportal==1.6.0dev-20150217

**Comment by sbrunner** [comment]
Oups I miss the find-links ...:
`.build/venv/bin/pip install --find-links http://pypi.camptocamp.net/internal-pypi/index/c2cgeoportal c2cgeoportal==1.6.0.dev-20150217`

**Comment by rmichaelis** [comment]
I've installed it. Now I don't have the mapserv error anymore but I've got this one : IOError: [Errno 2] No such file or directory: u'/home/mire/geoportailv3/geoportailv3/static/tourisme_mobile'

What is this file ?

**Comment by sbrunner** [comment]
I don't know, do you have more informations ? a stack trace ?

**Comment by rmichaelis** [comment]
Yes, here it is : 

URL: http://workshop.geoportal.lu:8081/themes?min_levels=1&interface=desktop&catalogue=true&version=2&background=bglayers&mapserv_url=1
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
  return self.app(environ, start_response)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1320 in send
  application, catch_exc_info=False)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1284 in call_application
  app_iter = application(self.environ, start_response)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/router.py', line 243 in __call__
  response = self.invoke_subrequest(request, use_tweens=True)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/router.py', line 218 in invoke_subrequest
  response = handle_request(request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/tweens.py', line 21 in excview_tween
  response = handler(request)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 94 in tm_tween
  reraise(*exc_info)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 75 in tm_tween
  response = handler(request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/router.py', line 164 in handle_request
  response = view_callable(context, request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/config/views.py', line 353 in rendered_view
  result = view(context, request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/config/views.py', line 481 in _class_requestonly_view
  response = getattr(inst, attr)()
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 1179 in themes
  role_id, interface, True, version, catalogue, min_levels
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 1040 in decorate
  should_cache_fn)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 651 in get_or_create
  async_creator) as value:
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 158 in __enter__
  return self._enter()
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 98 in _enter
  generated = self._enter_create(createdtime)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/core/dogpile.py', line 149 in _enter_create
  created = self.creator()
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 619 in gen_value
  created_value = creator()
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/dogpile/cache/region.py', line 1036 in creator
  return fn(*arg, **kw)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/entry.py', line 597 in _themes
  errors=errors
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/lib/__init__.py', line 57 in get_url
  return request.static_url(netloc + obj.path)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/url.py', line 717 in static_url
  return info.generate(path, self, **kw)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/lib/__init__.py', line 130 in generate
  subpath, kw = cachebust(subpath, kw)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/config/views.py', line 1985 in cachebust
  spec + subpath, subpath_tuple, kw)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/static.py', line 206 in pregenerate
  token = self.tokenize(pathspec)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/static.py', line 192 in tokenize
  self.token_cache[pathspec] = token = _generate_md5(pathspec)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/static.py', line 163 in _generate_md5
  with asset.stream() as stream:
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/path.py', line 402 in stream
  return self.pkg_resources.resource_stream(self.pkg_name, self.path)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py', line 1135 in resource_stream
  self, resource_name
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py', line 1689 in get_resource_stream
  return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 2] No such file or directory: u'/home/mire/geoportailv3/geoportailv3/static/nordstad'

**Comment by jaykayone** [comment]
these are names of themes that are interfering somehow here ...

**Comment by rmichaelis** [comment]
I've create 24 empty files with the name of each theme, and now I've got an answer from webservice

**Comment by sbrunner** [comment]
And what about this ? 
https://github.com/Geoportail-Luxembourg/geoportailv3/compare/fix-version?expand=1

**Comment by rmichaelis** [comment]
This solves both issue #333 #331

**Comment by petzlux** [comment]
Can this issue be closed now ?

**Comment by sbrunner** [comment]
yes => closed
