### ISSUE TITLE
debug mode fails

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#333]
Here is the stacktrace :

URL: http://workshop.geoportal.lu:8081/?debug=true
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
  return self.app(environ, start_response)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1320 in send
  application, catch_exc_info=False)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1284 in call_application
  app_iter = application(self.environ, start_response)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/router.py', line 243 in __call__
  response = self.invoke_subrequest(request, use_tweens=True)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/router.py', line 218 in invoke_subrequest
  response = handle_request(request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/tweens.py', line 21 in excview_tween
  response = handler(request)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 94 in tm_tween
  reraise(*exc_info)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 75 in tm_tween
  response = handler(request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/router.py', line 164 in handle_request
  response = view_callable(context, request)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/__init__.py', line 245 in new_f
  return f(root, request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/config/views.py', line 375 in rendered_view
  context)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/renderers.py', line 417 in render_view
  return self.render_to_response(response, system, request=request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/renderers.py', line 440 in render_to_response
  result = self.render(value, system_values, request=request)
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/renderers.py', line 436 in render
  result = renderer(value, system_values)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py', line 156 in __call__
  reraise(MakoRenderingException(errtext), None, exc_info[2])
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py', line 148 in __call__
  result = template.render_unicode(**system)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/template.py', line 452 in render_unicode
  as_unicode=True)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 803 in _render
  **_kwargs_for_callable(callable_, data))
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 835 in _render_context
  _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py', line 860 in _exec_template
  callable_(context, *args, **kwargs)
File 'index_html', line 41 in render_body
File '/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/url.py', line 717 in static_url
  return info.generate(path, self, **kw)
File '/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/lib/__init__.py', line 144 in generate
  raise ValueError('No static URL definition matching %s' % path)
MakoRenderingException: 

Traceback (most recent call last):
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_mako/__init__.py", line 148, in __call__
    result = template.render_unicode(**system)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/mire/geoportailv3/geoportailv3/templates/index.html", line 166, in render_body
    <script src="${request.static_url('%s/proj4/dist/proj4-src.js' % node_modules_path)}"></script>
  File "/home/mire/geoportailv3/.build/venv/src/pyramid/pyramid/url.py", line 717, in static_url
    return info.generate(path, self, **kw)
  File "/home/mire/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/lib/__init__.py", line 144, in generate
    raise ValueError('No static URL definition matching %s' % path)
ValueError: No static URL definition matching /home/mire/geoportailv3/node_modules/proj4/dist/proj4-src.js

**Comment by elemoine** [comment]
Est-ce que le fichier `node_modules/proj4/dist/proj4-src.js` est bien présent ?

**Comment by rmichaelis** [comment]
Oui, il est bien présent.

**Comment by elemoine** [comment]
À moins que @sbrunner ne soit déjà sur le problème, je regarde cet am…

**Comment by sbrunner** [comment]
Non, je m'occupe de l'autre problème ...

**Comment by elemoine** [comment]
Ok je regarde alors…

**Comment by rmichaelis** [comment]
It is solved by the solution proposed by @sbrunner in #331
