### ISSUE TITLE
Ngeo Scale Selector - levels not ordered properly

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#342]
In the scale selector, the zoom levels and corresponding scales are not ordered properly, i.e 1:1.000.000 comes at bottom when it should be at top of list. 

see  https://github.com/Geoportail-Luxembourg/geoportailv3/blob/petzlux_extents/geoportailv3/static/js/infobar/scaleselectordirective.js#L54-L55

![screen shot 2015-03-11 at 16 55 54](https://cloud.githubusercontent.com/assets/2540428/6600386/95172840-c80f-11e4-83b6-13f4af4936d2.png)

**Comment by elemoine** [comment]
This is a problem in ngeo's scale selector component. See https://github.com/camptocamp/ngeo/pull/199 for a fix.

**Comment by elemoine** [comment]
https://github.com/camptocamp/ngeo/pull/199 is now merged so the issue should now be fixed.

**Comment by elemoine** [comment]
> camptocamp/ngeo#199 is now merged so the issue should now be fixed.

This was not sufficient. I had to modify the partial we use in the project.

See https://github.com/Geoportail-Luxembourg/geoportailv3/pull/368.
