### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#352]
After fetch and cleanall I've got this new blocking compilation error :

`ERR! compile node_modules/ngeo/externs/ngeox.js:291: ERROR - Bad type annotation. Unknown type TypeaheadDataset
ERR! compile  *       TypeaheadDataset)|undefined),
ERR! compile          ^
ERR! compile
ERR! compile
ERR! compile node_modules/ngeo/externs/ngeox.js:293: ERROR - Bad type annotation. Unknown type TypeaheadDataset
ERR! compile  *       TypeaheadDataset)|undefined),
ERR! compile          ^
ERR! compile
ERR! compile node_modules/ngeo/externs/ngeox.js:295: ERROR - Bad type annotation. Unknown type TypeaheadDataset
ERR! compile  *       TypeaheadDataset)|undefined)
ERR! compile          ^
ERR! compile
ERR! compile node_modules/ngeo/externs/ngeox.js:314: ERROR - Bad type annotation. Unknown type TypeaheadDataset
ERR! compile  * @type {function(jQuery.event, Object, TypeaheadDataset)|undefined}
ERR! compile                                          ^
ERR! compile
ERR! compile node_modules/ngeo/externs/ngeox.js:320: ERROR - Bad type annotation. Unknown type TypeaheadDataset
ERR! compile  * @type {function(jQuery.event, Object, TypeaheadDataset)|undefined}
ERR! compile                                          ^
ERR! compile
ERR! compile node_modules/ngeo/externs/ngeox.js:326: ERROR - Bad type annotation. Unknown type TypeaheadDataset
ERR! compile  * @type {function(jQuery.event, Object, TypeaheadDataset)|undefined}
ERR! compile                                          ^
ERR! compile
ERR! compile 6 error(s), 0 warning(s)
ERR! compile
`

**Comment by elemoine** [comment]
I've created a PR for that: https://github.com/Geoportail-Luxembourg/geoportailv3/pull/351.

**Comment by rmichaelis** [comment]
Ok thanks.
