### ISSUE TITLE
Take image_type into account

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#355]
As [commented](https://github.com/Geoportail-Luxembourg/geoportailv3/issues/300#issuecomment-83639253) in #300 the js code that creates OpenLayers layers from layer nodes should take the `image_type` property into account.

Restant c2c 01/04/2015 0.25j

**Comment by elemoine** [comment]
@jaykayone Is there a jpeg background layer I could use for testing? The `streets_jpeg` and `topo_bw_jpeg` layers don't seem to work, even when using the correct image type in the URL.

E.g. http://wmts.geoportail.lu/mapproxy_4_v3/wmts/streets_jpeg/GLOBAL_WEBMERCATOR/8/132/88.jpg

**Comment by jaykayone** [comment]
ortho_2013_global should work, but attention it's jpeg not jpg.

http://wmts.geoportail.lu/mapproxy_4_v3/wmts/ortho_2013_global/GLOBAL_WEBMERCATOR/8/132/88.jpeg

**Comment by elemoine** [comment]
Ok thanks.

New problem: it looks like there's no `imageType` for background layers in the JSON response from the `themes` service. @sbrunner is this a known issue?

**Comment by jaykayone** [comment]
It might be because we have not sent you the dump yet ...

**Comment by elemoine** [comment]
> It might be because we have not sent you the dump yet ...

Ok, thanks for the response.

I have a [patch](https://github.com/Geoportail-Luxembourg/geoportailv3/compare/elemoine_imagetype) ready that I'm looking forward to testing :-)

**Comment by jaykayone** [comment]
fixes #300

**Comment by elemoine** [comment]
It looks like "topo_bw_jpeg" layer has imageType set to "image/png" in the database. Is this expected?

**Comment by elemoine** [comment]
> It looks like "topo_bw_jpeg" layer has imageType set to "image/png" in the database. Is this expected?

Same comment for the "streets_jpeg".

**Comment by jaykayone** [comment]
my bad, please change it manually.

**Comment by elemoine** [comment]
Done:

```
lux=# update geov3.layer_wmts set image_type = 'image/jpeg' where layer = 'streets_jpeg';
UPDATE 1
lux=# update geov3.layer_wmts set image_type = 'image/jpeg' where layer = 'topo_bw_jpeg';                                                                                                                           
UPDATE 1
lux=#
```

**Comment by elemoine** [comment]
But both `topo_bw_jpeg` and `streets_jpeg` still do not work for me. They produce 400 responses.

E.g.

http://wmts.geoportail.lu/mapproxy_4_v3/wmts/streets_jpeg/GLOBAL_WEBMERCATOR/15/16940/11139.jpeg
http://wmts.geoportail.lu/mapproxy_4_v3/wmts/topo_bw_jpeg/GLOBAL_WEBMERCATOR/15/16940/11139.jpeg

**Comment by jaykayone** [comment]
you are right, the have been forgotten during the migration.
I'll check that after my return. It should not hold back the PR. It's a config issue

**Comment by elemoine** [comment]
> I'll check that after my return. It should not hold back the PR. It's a config issue

Definitely.

**Comment by rmichaelis** [comment]
The orthos produce error 500 responses. it seems to be a different problem as the one mentioned by @elemoine 

http://wmts.geoportail.lu/mapproxy_4_v3/wmts/ortho_2007/GLOBAL_WEBMERCATOR/11/1060/698.jpeg

**Comment by elemoine** [comment]
> The orthos produce error 500 responses. it seems to be a different problem as the one mentioned by @elemoine

And it looks like it's unrelated to the image type. The image type is correct in the request.

**Comment by jaykayone** [comment]
my bad .. I guess ...I'll check it next week

**Comment by jaykayone** [comment]
trying to test this .. 
but I cannot compile:

info geoportailv3 Compiling 415 sources
ERR! compile ERROR - Cannot read: node_modules/openlayers/externs/vbarray.js
ERR! compile 
ERR! compile 
ERR! compile 1 error(s), 0 warning(s)
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 1 
make: *** [.build/build.js] Error 1
