### ISSUE TITLE
Profile: Interaction map -> profile

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#356]
à faire dans ngeo

Restant c2c 01/04/2015 2.5j
Restant c2c 01/05/2015 1j

**Comment by pgiraud** [comment]
WIP https://github.com/pgiraud/ngeo/tree/profile_interaction

**Comment by pgiraud** [comment]
https://github.com/camptocamp/ngeo/pull/210

**Comment by pgiraud** [comment]
https://github.com/Geoportail-Luxembourg/geoportailv3/pull/405

**Comment by jaykayone** [comment]
this does not seem to work: http://devv3.geoportail.lu/main?version=3&zoom=15&X=708610&Y=6368971. Prod is on petzlux_search but I've rebased it several minutes ago ..

**Comment by pgiraud** [comment]
I don't have any problems.
Here's what I do:
 - I select the profile tool,
 - I draw a line on the map,
 - the profile chart is displayed,
 - I move the mouse cursor over the line on the map,
 - the corresponding point in the chart is highlighted & a popover with distance and elevation displays on the map.

Can it be a browser cache issue?

**Comment by jaykayone** [comment]
Ok, it was a a cache issue, now it works.
Could we set a higher tolerance?

You are right that the "click to start drawing" is disturbing. Could it be hidden as soon as there is an interaction between the map and the graph ? Idem for the length popup

**Comment by pgiraud** [comment]
Can we close this issue?

**Comment by jaykayone** [comment]
let's keep it in the backlog
