### ISSUE TITLE
Profile: Placement du profile

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#357]
pour l'instant c'est dans un div, meilleur concept à trouver

**Comment by pgiraud** [comment]
Alors voilà, ce que j'imaginais pour la position du profil dans la page.
![screenshot from 2015-03-31 11 55 03](https://cloud.githubusercontent.com/assets/319774/6916474/daf4d87a-d79c-11e4-82b7-e4388571e043.png)

L'idée serait de remplacer la barre des outils de mesure par un bloc vide lorsque l'utilisateur sélectionne l'outil profil. Puis si l'utilisateur clique sur la croix, le panneau se ferme et laisse de nouveau la place aux autres outils de mesure. Ça nécessite deux clics pour changer d'outil de mesure mais je ne pense pas que ce soit gênant.

**Comment by jaykayone** [comment]
Hello,

ce qui nous gène c'est que cette fenêtre pourra potentiellement se superposer avec la géométrie ..
As-tu une proposition pour celà?
Panner et dézoomer la carte?

**Comment by pgiraud** [comment]
Selon moi, le bloc doit être présent avant que l'utilisateur ne commence à dessiner. Ainsi, l'utilisateur ne devrait pas pouvoir dessiner sous le bloc. En tous cas pas de façon involontaire.

**Comment by jaykayone** [comment]
removing question label and putting a name on it

**Comment by pgiraud** [comment]
Can we close this one?
