### ISSUE TITLE
ouvrir un thème donné dans l'URL

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#358]
Paramètre URL pour ouvrir un thème avec /{nom_du_theme}

**Comment by jaykayone** [comment]
cf cgxp

**Comment by elemoine** [comment]
C.f. https://github.com/Geoportail-Luxembourg/geoportailv3/issues/400.

**Comment by jaykayone** [comment]
est-ce que ce ticket peut être fermé?
