### ISSUE TITLE
couleurs de thèmes

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#359]
faire une proposition pour avoir des changements de thème moins brutaux. par exemple ne pas changer le fond du catalogue. avoir des textes plus lisibles

**Comment by pgiraud** [comment]
Pendant la dernière réunion, j'avais proposé une couleur neutre lorsque l'on change de thème. Voici ce que ça pourrait donner.

![notheme](https://cloud.githubusercontent.com/assets/319774/6805422/23f41c5c-d243-11e4-9bc7-ab2481d454c8.gif)

**Comment by petzlux** [comment]
we decided to keep current behaviour 

also, can we tone down some colour schemes, to increase text contrast in catalogue.

**Comment by pgiraud** [comment]
OK. I agree that colors are not correct. So, instead of computing secondary and tertiary colors from a primary one (ligthen, darken, etc...), we should configure the theme with 3 colors. I'll provide a patch.

**Comment by pgiraud** [comment]
See https://github.com/Geoportail-Luxembourg/geoportailv3/pull/394
