### ISSUE TITLE
Problème avec nouvelle version de CONST_Makefile

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#365]
```
[root@workshop3-local geoportailv3]# make -f main.mk build
echo "Include /var/www/vhosts/geoportailv3/apache/*.conf" > /var/www/vhosts/luxembourg-geomapfish/conf/main.conf
/bin/sh: /var/www/vhosts/luxembourg-geomapfish/conf/main.conf: No such file or directory
make: *** [/var/www/vhosts/luxembourg-geomapfish/conf/main.conf] Error 1
```

Ce ne sont pas les bons répertoires.
1) le vhost ne s'appelle pas comme ça
2) il n'y a pas de répertoire conf ..

je viens de tout mettre en commentaire pour le faire fonctionner:

```
# Apache config
.PHONY: apache
#apache: .build/apache.timestamp

#$(APACHE_CONF_DIR)/$(INSTANCE_ID).conf:
#       echo "Include $(shell pwd)/apache/*.conf" > $@

#.build/apache.timestamp: $(CONF_FILES) $(PY_FILES) $(APACHE_CONF_DIR)/$(INSTANCE_ID).conf .build/requirements.timestamp
#       sudo /usr/sbin/apache2ctl graceful
#       touch $@
```

**Comment by sbrunner** [comment]
1) il s’appelle comment ?
2) pas de répertoire conf ? vous incluez comment votre config ?

**Comment by rmichaelis** [comment]
`2) pas de répertoire conf ? vous incluez comment votre config ?`
Moi par exemple je ne travaille pas avec apache mais avec serve

**Comment by jaykayone** [comment]
pour le main:
1) le vhost s'appelle geoportailv3
2) voici comment c'est configuré:

 [root@workshop3-local geoportailv3]# cd /etc/httpd/conf.d
 [root@workshop3-local conf.d]# ll
 total 24
 -rw-r--r--. 1 root root 2893 Jul 17  2014 autoindex.conf
 -rw-r--r--  1 root root   51 Dec  4 17:32 geoportail.conf
 -rw-r--r--. 1 root root  366 Jul 17  2014 README
 -rw-r--r--  1 root root   56 Dec  5 14:13 renaud.conf
 -rw-r--r--. 1 root root 1252 Jul 17  2014 userdir.conf
 -rw-r--r--. 1 root root  516 Jul 17  2014 welcome.conf
 [root@workshop3-local conf.d]# cat geoportail.conf 
 Include /var/www/vhosts/geoportailv3/apache/*.conf
 [root@workshop3-local conf.d]# cd /var/www/vhosts/geoportailv3/apache/
 [root@workshop3-local apache]# ll
 total 32
 -rw-r--r-- 1 root root  506 Mar 20 16:52 frontend.conf
 -rw-r--r-- 1 root root  533 Feb 27 14:40 frontend.conf.in
 -rw-r--r-- 1 root root  369 Mar 20 16:52 geoportailv3.wsgi
 -rw-r--r-- 1 root root  353 Feb 12 11:13 geoportailv3.wsgi.mako
 -rw-r--r-- 1 root root   93 Mar 20 16:52 README.txt
 -rw-r--r-- 1 root root   86 Feb 12 11:13 README.txt.in
 -rw-r--r-- 1 root root 2148 Mar 20 16:52 wsgi.conf
 -rw-r--r-- 1 root root 2441 Feb 27 14:40 wsgi.conf.in
 [root@workshop3-local apache]# 


Les autres n'utilisent pas apache, seulement pserve

**Comment by pgiraud** [comment]
J'utilise moi-même pserve et Stéphane m'a donné comme astuce d'ajouter la
ligne suivante dans mon fichier de config make :

APACHE_CONF_DIR = /tmp

On Mon, Mar 23, 2015 at 10:05 AM, Jeff Konnen <notifications@github.com>
wrote:

> pour le main:
> 1) le vhost s'appelle geoportailv3
> 2) voici comment c'est configuré:
>
> [root@workshop3-local geoportailv3]# cd /etc/httpd/conf.d
> [root@workshop3-local conf.d]# ll
> total 24
> -rw-r--r--. 1 root root 2893 Jul 17 2014 autoindex.conf
> -rw-r--r-- 1 root root 51 Dec 4 17:32 geoportail.conf
> -rw-r--r--. 1 root root 366 Jul 17 2014 README
> -rw-r--r-- 1 root root 56 Dec 5 14:13 renaud.conf
> -rw-r--r--. 1 root root 1252 Jul 17 2014 userdir.conf
> -rw-r--r--. 1 root root 516 Jul 17 2014 welcome.conf
> [root@workshop3-local conf.d]# cat geoportail.conf
> Include /var/www/vhosts/geoportailv3/apache/*.conf
> [root@workshop3-local conf.d]# cd /var/www/vhosts/geoportailv3/apache/
> [root@workshop3-local apache]# ll
> total 32
> -rw-r--r-- 1 root root 506 Mar 20 16:52 frontend.conf
> -rw-r--r-- 1 root root 533 Feb 27 14:40 frontend.conf.in
> -rw-r--r-- 1 root root 369 Mar 20 16:52 geoportailv3.wsgi
> -rw-r--r-- 1 root root 353 Feb 12 11:13 geoportailv3.wsgi.mako
> -rw-r--r-- 1 root root 93 Mar 20 16:52 README.txt
> -rw-r--r-- 1 root root 86 Feb 12 11:13 README.txt.in
> -rw-r--r-- 1 root root 2148 Mar 20 16:52 wsgi.conf
> -rw-r--r-- 1 root root 2441 Feb 27 14:40 wsgi.conf.in
> [root@workshop3-local apache]#
>
> Les autres n'utilisent pas apache, seulement pserve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/365#issuecomment-84899648>
> .
>



-- 
Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by sbrunner** [comment]
La proposition de pierre est un bon workaround mais je vais regarder pour trouver une bonne solution :-)

**Comment by rmichaelis** [comment]
Je viens d'essayer mais j'ai toujours un problème à cause de `sudo /usr/sbin/apache2ctl graceful`

**Comment by sbrunner** [comment]
quel problème ? tu n'a pas les droits de le faire ?

**Comment by geoportallux** [comment]
Mon utilisateur n'a effectivement pas les droits de le faire mais je pourrais l'obtenir.

Par contre, je n'ai pas spécialement envie de redémarrer apache alors que je ne m'en sers pas pour mes dev.


________________________________

**Comment by sbrunner** [comment]
effectivement on est bien d'accord :-)

**Comment by sbrunner** [comment]
Es-ce que si vous ajouter uniquement `DISABLE_BUILD_RULES += apache` cela fonctionne bien pour vous ?

**Comment by elemoine** [comment]
> Es-ce que si vous ajouter uniquement DISABLE_BUILD_RULES += apache cela fonctionne bien pour vous ?

Où ajouter ça exactement ? Avant ou après `include geoportailv3.mk` dans notre Makefile ? Ça n'a pas l'air de fonctionner pour moi en tout cas.

**Comment by elemoine** [comment]
> Par contre, je n'ai pas spécialement envie de redémarrer apache alors que je ne m'en sers pas pour mes dev.

D'ailleurs dans mon cas je n'ai même pas Apache installé sur ma machine, donc la commande apache2ctl échoue.

**Comment by elemoine** [comment]
> Où ajouter ça exactement ? Avant ou après include geoportailv3.mk dans notre Makefile ? Ça n'a pas l'air de fonctionner pour moi en tout cas.

Je pense savoir pourquoi. Je vais faire un PR.

**Comment by elemoine** [comment]
Voir https://github.com/Geoportail-Luxembourg/geoportailv3/pull/366.
