### ISSUE TITLE
Impression [c2c / lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#37]
* [x] UI formulaire spécifique [lux]
* [x] Interfacer le protocole [c2c: 2j]
* [x] Lecture des données de la carte [c2c: 1j]
* [x] Layers vecteurs [c2c: 2j]
* [x] Impression de la légende [c2c: 1j]
* [x] Annulation de l'impression
* [x] Configuration des templates [lux]
* [x] MapFish Print v3 fonctionnel [c2c: 1j]
* [x] Ajouter entêtes cors dans print proxy [c2c: 0.5j]

Restant c2c 01/03/2015 : 6j
Restant c2c 01/04/2015 : 4j
Restant c2c 01/05/2015 : 4j (reste : couches vecteur, impression de la légende)

**Comment by jaykayone** [comment]
@sbrunner peux-tu mettre à jour ce ticket avec ce qui est fait et ce qui reste à faire stp?

**Comment by sbrunner** [comment]
Pas grands chose n'a été fais il est donc à jours :-)

**Comment by elemoine** [comment]
Pour info, j'ai commencé à travailler sur des composants de print (MapFish Print v3) pour ngeo. Ici : https://github.com/camptocamp/ngeo/pull/204.

**Comment by elemoine** [comment]
Pour info, j'ai repris aujourd'hui mon travail sur le print dans ngeo. C.f. https://github.com/camptocamp/ngeo/pull/204. Pour le moment, je ne supporte que les couches WMS non tuilées. Je bosserai sur les couches WMTS la semaine prochaine.

En discutant avec Pierre tout à l'heure nous nous sommes posés une question : dans les [mockups](http://dev.camptocamp.com/files/lux/geoportail_lux_specs/cartes/), et tel qu'on l'avait imaginé jusqu'à présent, le formulaire de print s'ouvre au dessus de la barre d'outils par dessus la carte. Mais l'ouverture du formulaire de print va afficher le rectangle d'impression dans la carte. Dans la pratique une partie du rectangle d'impression va être caché par le formulaire d'impression.

Je mets le label "question" sur cet issue parce qu'il me semble qu'il faut qu'on discute de ça.

**Comment by pgiraud** [comment]
On garde le formulaire à la position telle que prévue dans les mockups. Mais on tente de minimiser le problème au maximum, par exemple en réduisant son emprise, et/ou en le rendant moins vertical et plus horizontal.
Ensuite, on teste avec des utilisateurs, et on évalue la gêne.

**Comment by elemoine** [comment]
"question" tag removed for now.

**Comment by elemoine** [comment]
For everyone's information I've started working on vector print support.
