### ISSUE TITLE
Feature is not propagated with measureend event in ngeo.interaction.Measure

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#370]
in `ngeo.interaction.Measure`
`  this.sketchFeature = null;
  this.dispatchEvent(new ngeo.MeasureEvent(ngeo.MeasureEventType.MEASUREEND,
      this.sketchFeature));
};`

It seems that the propagated sketchFeature is always null.

**Comment by elemoine** [comment]
Will be fixed with https://github.com/camptocamp/ngeo/pull/202.
