### ISSUE TITLE
catalog -> checkboxes

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#371]
In the current state the checkboxes are on the right.
after using the portal for some time now, we are convinced that they would be better on the left so that they can be aligned

**Comment by pgiraud** [comment]
Given the mockups they were supposed to be aligned on the right.
I havent 't done anything for that yet.

![screenshot from 2015-03-24 11 45 18](https://cloud.githubusercontent.com/assets/319774/6800037/5f01b94e-d21b-11e4-8631-c72651cef858.png)

**Comment by jaykayone** [comment]
that's probably even better, as they stay aligned even if we have different imbrications

**Comment by pgiraud** [comment]
Addressed in #384.
