### ISSUE TITLE
localstorage

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#372]
the seems to be a problem with the localstorage:

http://devv3rm.geoportail.lu/?version=3&zoom=12&X=674880&Y=6390772
If you reopen the page without url params:
http://devv3rm.geoportail.lu/?version=3&zoom=8&X=16676259&Y=623889

I think that it does not use the version=3 parameter and then applies the coordinate system switch to the coordinates that are already in webmercator or something like that

**Comment by elemoine** [comment]
Yep, Pierre and I just had realized about the problem. I am on it.

**Comment by jaykayone** [comment]
another point I saw is that the selected layers and theme are neither stored in localstorage nor in URL. Is this WIP ?

**Comment by elemoine** [comment]
> another point I saw is that the selected layers and theme are neither stored in localstorage nor in URL. Is this WIP ?

I just implemented the permalink/localstorage for map-related states. This can be used as a base/example for other states.
