### ISSUE TITLE
full screen & geolocation

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#374]
Je pense que c'est une mauvaise idée d'avoir groupé les boutons full screen et geolocation avec les boutons de zoom (+, -, full extent). Leur but est assez différent et il serait probablement bon de les distinguer soir géographiquement dans l'interface soit visuellement du point de vue du style.

**Comment by pgiraud** [comment]
![screenshot from 2015-03-24 12 19 53](https://cloud.githubusercontent.com/assets/319774/6800621/6f07b5fa-d220-11e4-9a57-d4d503ee94b9.png)

**Comment by jaykayone** [comment]
a discuter

**Comment by jaykayone** [comment]
let's vote on this one. Who's for separating the buttons? (+1). Who's for lettings them grouped (-1)

**Comment by rmichaelis** [comment]
Ca dépend le séparer pour le mettre où, Si on regarde l'interface mobile la place est limitée. Est-ce que c'est pour le mettre en haut à droite ?

**Comment by petzlux** [comment]
:-1:

**Comment by petzlux** [comment]
on mobile, get rid of zoom to country .

separate visually zoom buttons from rest of buttons

**Comment by rmichaelis** [comment]
location button  to right top on mobile and left bottom other devices.
