### ISSUE TITLE
ghost block at loading page

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#376]
There's a weird element showing up on the left side of the page while loading in debug mode.
There may be a trailing closing bracket somewhere.

![screenshot from 2015-03-24 14 03 06](https://cloud.githubusercontent.com/assets/319774/6802202/b20c698c-d22e-11e4-95fb-1382e62ffb0d.png)

**Comment by rmichaelis** [comment]
It's coming from `<span ng-if="mainCtrl.selectedLayers.length > 0">({{mainCtrl.selectedLayers.length}})</span>` in index.html

**Comment by pgiraud** [comment]
I really have no clue how to fix this quickly. As soon as it invisible in built mode, I propose we close this issue.
