### ISSUE TITLE
Activation of a layer vs making them invisible

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#381]
There is a real UX problem:
If a layer is invisible and you deactivate it and activate it later on it stays invisible.
The user will never understand what's happening.

Restant c2c 01/04/2015 : 0.25j

**Comment by elemoine** [comment]
> There is a real UX problem:
> If a layer is invisible and you deactivate it and activate it later on it stays invisible.
> The user will never understand what's happening.

Related to that: do layers have an opacity value in the database?

**Comment by jaykayone** [comment]
They can have on specified in the ui_metadata.
But it should not be 0

**Comment by elemoine** [comment]
Should we use the database value when (re-) adding a layer?

**Comment by jaykayone** [comment]
yes

**Comment by jaykayone** [comment]
Removing the question label, this is "ready" for me
