### ISSUE TITLE
layers not loading

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#388]
I have the impression that if there is one layer that cannot be loaded (eg eau->zones inondables->projet des cartes des zones inondables -> HQ10), the other layers don't always get loaded correctly either

**Comment by elemoine** [comment]
There may be a bug in OpenLayers.

**Comment by elemoine** [comment]
I'm having a hard time reproducing the problem. To try to reproduce the issue I activate the HQ10 layer (the defective layer) and then active the Hydrographie/Cours d'eau primaires et Cours d'eau secondaires layers. The Cours d'eau layers display correctly, and I don't think I observe any abnormal delays.

**Comment by elemoine** [comment]
We forgot to discuss this yesterday. @jaykayone, have you done more testing related to that issue?

**Comment by jaykayone** [comment]
OK, i'll try to find a use case

**Comment by jaykayone** [comment]
I've tried a multitiude of combinations but it seems to be solved in the meantime
