### ISSUE TITLE
Rechargement du catalogue après login

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#389]
Vu qu'un utilisateur peut avoir le droit de voir certaines couches uniquement quand il est logué, il faut recharger le catalogue après login

**Comment by elemoine** [comment]
Question : dans la plupart des cas, les utilisateurs qui ouvrent l'application dans leur navigateur sont-ils déjà authentifiés ? Ou bien s'authentifient-ils après ouverture de l'application ?

Je pose cette question pour savoir s'il est préférable d'attendre d'avoir les informations utilisateur avant de charger le catalogue ? Ou est-ce qu'il est préférable de charger tout de suite le catalogue, quitte à refaire la requête si l'utilisateur était en fait déjà authentifié…

**Comment by jaykayone** [comment]
ils ne le sont pas encore ...
à moins que ce soit un guichet protégé où ils doivent se loguer avant de voir quoi que ce soit

**Comment by elemoine** [comment]
Ok, donc on peut éventuellement ne pas attendre et charger le catalogue tout de suite. On le rechargera si on voit que l'utilisateur est en fait déjà authentifiée. Et, évidemment, on le rechargera, après authentification (formulaire login).

**Comment by rmichaelis** [comment]
Que je sois connecté ou pas j'ai l'impression que le webservice des thèmes retourne l'entièreté des thèmes et l'entièreté des couches. 
Par exemple, le theme go n'est pas publique et contient la couche parcels_go qui n'est également pas publique.  Par contre je la retrouve dans la réponse du webservice des thèmes. 

Quand je suis déconnecté, quels sont les thèmes et les couches qui doivent être retournés ?
Quand je suis connecté, est-ce que je ne dois retrouver que les thèmes publiques et ceux qui sur lesquels j'ai les droits ? 

http://devv3.geoportail.lu/renaud/wsgi/themes?min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2&amp;background=bglayers

**Comment by jaykayone** [comment]
renaud tu as raison quant au fonctionnement. il me semble que dans une version ultérieure ça fonctionnait

**Comment by elemoine** [comment]
C'est un problème côté serveur/c2cgeoportal, qui n'est donc pas directement lié à #403. @sbrunner, tu pourras regarder ça ?

**Comment by sbrunner** [comment]
Je ne comprends pas le problème, avec l'URL:
http://devv3.geoportail.lu/renaud/wsgi/themes?min_levels=1&amp;interface=desktop&amp;catalogue=true&amp;version=2&amp;background=bglayers
je n'ai pas de theme `go` ou de layer `parcels_go`...

**Comment by sbrunner** [comment]
Es-ce que ce ne serais pas un problème de cache navigateur ?

**Comment by rmichaelis** [comment]
Oui probablement. Je suis en train de regarder.

**Comment by rmichaelis** [comment]
Il y a effectivement un problème de cache. 
1. Je ne suis pas connecté. Le webservice themes retourne les données du profil tout public  depuis le réseau.
2. Je me connecte. Le webservice themes retourne toujours les données du profil tout public depuis le cache.
3. Je vide le cache et je recharge l'application. Le webservice themes retourne les données correctes depuis le réseau.

**Comment by elemoine** [comment]
Ok, donc c'est un problème côté client. Angular cache la réponse du service de thème. Je vais regarder ça… Merci!

**Comment by sbrunner** [comment]
Cela peut aussi être le navigateur...
