### ISSUE TITLE
Interrogations [lux]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#39]
* [ ] Service de query [lux]
* [ ] Composant [lux]
* [ ] Popup des résultats [lux]

**Comment by jaykayone** [comment]
ici, il faut de la coordination pour bien comprendre ce qu'il y a dans c2cgeoportal @sbrunner

En plus il faut du support de @pgiraud / @elemoine pour configurer le templating des popups.

Il y a les cas suivants:

1) simple réflection des champs de la base de données dans un tableau HTML
2) réflexion des champs d'un requête REST ESRI dans un tableau HTML
3) possibilité d'intégrer des iframes par une URL qui est retournée par un champ
4) interaction sur le serveur avec des webservices supplémentaires (PF.py)
5) cas des mymaps -> mako très spécifique
6) cas des POI -> makos générés par une autre appli

Le services de query et le popup côté client sont assez clairs, c'est le composant qui nécessite quelques décisions de design

**Comment by sbrunner** [comment]
Hello, dans CGXP on a la possibilité de faire de l'interrogation ponctuelle effectuant une requête `WMS-GetFeatureInfo` ou une interrogations pas bbox effectuant une requête `WFS-GetFeature`.
Donc c2cgeoportal fournis un mapserver fonctionnel, et dans le web-service des thèmes une lecture des capabilities pour en extraire les informations nécessaire soit principalement la composition des groupes et le range de visibilité des différents layers.

**Comment by jaykayone** [comment]
OK, donc nous devons écrire un contrôleur sur mesure pour prendre en compte tous nos besoins.

**Comment by sbrunner** [comment]
C'est bien l'impression que j'avais :-)

**Comment by elemoine** [comment]
Moi aussi, depuis le début.

**Comment by jaykayone** [comment]
changement de pointeur au hover: https://twitter.com/cedricmoullet/status/578555464125911040

**Comment by elemoine** [comment]
> changement de pointeur au hover: https://twitter.com/cedricmoullet/status/578555464125911040

Oui, cette fonctionnalité utilise la fonction `forEachLayerAtPixel` qu'on a ajoutée il y a quelques temps. Cette fonction appelle une fonction de callback pour chaque couche pour laquelle une couleur est détectée à un pixel donné (passé à la fonction). Bien évidemment ceci ne fonctionne qu'avec les couches transparentes, pour distinguer les objets dans les images.

**Comment by rmichaelis** [comment]
Si j'ai bonne mémoire, dans l'ancien guichet, dans la popup d'information des parcelles  les personnes autorisées peuvent télécharger des mesurgaes selon une restriction géographique. C'est bien ça Jeff ?

**Comment by jaykayone** [comment]
oui
