### ISSUE TITLE
ngeoCreatePopup avec différents templates

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#398]
I would like to use ngeoCreatePopup to display information about the layers. 
In the other hand, a value for ngeoPopupTemplateUrl is already defined to display metadata information. 

Is it possible to use ngeoCreatePopup  twice with a different template ? 
Could you please explain me how I could achieve it ?

Note that it's only for my understanding and for test purpose. Jeff  just remembered me that the information has to be display in the info tab panel.

Thanks,

**Comment by pgiraud** [comment]
This is indeed impossible for now.
Please don't hesitate to tell us if this is eventually required to handle different templates.

**Comment by elemoine** [comment]
Is this still relevant?

**Comment by rmichaelis** [comment]
No more relevant. That was just for testing the popup directive. Thanks.
