### ISSUE TITLE
Projection Issues ? 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#411]
![screen shot 2015-04-15 at 16 28 22](https://cloud.githubusercontent.com/assets/2540428/7160959/94c90802-e38c-11e4-821a-cef81f9f3cd9.png)

**Comment by sbrunner** [comment]
Cela me donne plutôt l'impression que les tuiles sont mal calée sure la grille ...

**Comment by pgiraud** [comment]
Ça devrait ressembler à ça:
http://g-o.lu/sobms

![screenshot from 2015-04-15 17 05 35](https://cloud.githubusercontent.com/assets/319774/7161876/b1c3ea6c-e391-11e4-82c9-3595d7e418e9.png)

**Comment by jaykayone** [comment]
is it the basemap or the overlay that's wrong?

**Comment by sbrunner** [comment]
I suspect that that's the base map ...

**Comment by jaykayone** [comment]
I investigated a bit more and it seems to touch all the layers coming from a ArcGIS Server 10.0 source.
In this case it's the WMS overlay.

For ArcGIS Server 10.1+ there is no problem. I'll check with those partners if they are OK to upgrade

**Comment by jaykayone** [comment]
we have several options here:
- make all the providers migrate to arcgis 10.1+
- create a proxy to do the reprojection on our side (server)
- row back and use LUREF as SRS 
- do reprojection on the client side ? @elemoine ?

**Comment by elemoine** [comment]
> do reprojection on the client side ? @elemoine ?

OpenLayers 3 doesn't yet support projection of image and tile layers. This is something that will be implemented in the future. We've even discussed it during the code sprint.

**Comment by petzlux** [comment]
make all providers migrate to 10.1+ , if not possible use proxy ...
