### ISSUE TITLE
Problem with apache build

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#414]
there is a problem with the apache build target.
there seems to be a hardcoded vhost name ? luxembourg-geomapfish is not a variable I have set somewhere
```
echo "Include /var/www/vhosts/geoportailv3/apache/*.conf" > /var/www/vhosts/luxembourg-geomapfish/conf/main.conf
/bin/sh: /var/www/vhosts/luxembourg-geomapfish/conf/main.conf: No such file or directory
make: *** [/var/www/vhosts/luxembourg-geomapfish/conf/main.conf] Error 1
```

**Comment by sbrunner** [comment]
It's not hardcoded: 
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/CONST_Makefile#L232
`?=` mead that it's define only if it's not already defined :-)

Then you can defined you own `APACHE_CONF_DIR`

**Comment by jaykayone** [comment]
What about sudo /usr/sbin/apache2ctl graceful ?

**Comment by sbrunner** [comment]
It should be configurable :-), I will work on that...

**Comment by geoportallux** [comment]
thanks





Jeff Konnen
Chargé d’études – informaticien/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich . L-1420 Luxembourg
Tél. (+352) 44901-261 . Fax (+352) 44901-333
E-mail: jeff.konnen@act.etat.lu

www.act.public.lu www.geoportail.lu



De : Stéphane Brunner <notifications@github.com<mailto:notifications@github.com>>
Répondre à : Geoportail-Luxembourg/geoportailv3 <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : Tuesday 21 April 2015 13:37
À : Geoportail-Luxembourg/geoportailv3 <geoportailv3@noreply.github.com<mailto:geoportailv3@noreply.github.com>>
Objet : Re: [geoportailv3] Problem with apache build (#414)


It should be configurable :-), I will work on that...
