### ISSUE TITLE
hide "search_key_words" on focus

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#420]

**Comment by pgiraud** [comment]
À noter que c'est le comportement par défaut en HTML (ie. le placeholder ne disparait pas avant que l'utilisateur tape du texte).
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

On pourrait conserver ce comportement par défaut.
Par contre, on pourrait faire en sorte que l'on voit mieux la différence entre le placeholder et le texte tapé.

**Comment by jaykayone** [comment]
Pour l'instant ce n'est pas intuitif et dans geoportailv2, on enlève le texte, s'il y a une autre solution qui fait comprendre à l'utilisateur qu'il est en mode saisie, je veux bien

**Comment by pgiraud** [comment]
Le mieux à mon avis est de surligner le bord du champ lors du focus.
cf. champ de recherche sur le portail général https://www.geoportail.lu/fr/

**Comment by pgiraud** [comment]
Forget about my last comment. There's already a border highlight on focus.

**Comment by petzlux** [comment]
I have tried a compromise, the search placeholder text is greyed out when focus is on input field first time, and stays grey thereafter. works quite well
