### ISSUE TITLE
Chrome / Safari Render differences

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#426]
Notice the finer lines in the icons  ... (Safari on top )

![screen shot 2015-04-23 at 16 52 00](https://cloud.githubusercontent.com/assets/2540428/7299936/24c48970-e9d9-11e4-820a-4c0d84da33c1.png)

**Comment by petzlux** [comment]
Is this still relevant ? 

![screen shot 2015-07-08 at 10 49 35](https://cloud.githubusercontent.com/assets/2540428/8566542/17459840-255f-11e5-9693-4557011d399a.png)

**Comment by jaykayone** [comment]
no
