### ISSUE TITLE
BackgroundLayer Switcher translations stuck on french

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#428]
When changing languages, the background layer dropdown menu doesnt update translations

**Comment by elemoine** [comment]
The translate directive is not used in the [backgroundlayer.html](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/backgroundlayer/backgroundlayer.html) partial.

**Comment by petzlux** [comment]
I tried changing it in 

https://github.com/Geoportail-Luxembourg/geoportailv3/blob/petzlux_search/geoportailv3/static/js/backgroundlayer/backgroundlayer.html 

but still get the same effect

**Comment by elemoine** [comment]
> I tried changing it in
> 
> https://github.com/Geoportail-Luxembourg/geoportailv3/blob/petzlux_search/geoportailv3/static/js/backgroundlayer/backgroundlayer.html
> 
> but still get the same effect

Do we have translations for the layer labels? They should be extracted from the database right?

**Comment by petzlux** [comment]
Okay its all in the search branch, probably better idea to do this in a separate branch. 

Yes see http://devv3.geoportail.lu/main?version=3&zoom=18&X=696076&Y=6387606 you can see the effect there

**Comment by petzlux** [comment]
The translations are there and used but language switch doesnt seem to happen
