### ISSUE TITLE
Catalogue - Serverside Caching issue

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#429]
I have changed the catalog data in the database.
c2cgeoportal only reflects the database change after having restarted apache.

I have tried with an incognito browser and no cache, it's not a browser issue, it's the server who is caching

Restant c2c 01/05/2015 1j (verify that caches are correctly handled)

**Comment by elemoine** [comment]
What table did you change?

**Comment by jaykayone** [comment]
all of them :)

I did entirely reload the config

**Comment by elemoine** [comment]
Strange. c2cgeoportal should invalidate the dogpile cache when the layer-related tables change. https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/models.py#L345-L347

**Comment by jaykayone** [comment]
just retried and I confirm it again.

I first do a truncate and then an insert

**Comment by elemoine** [comment]
@sbrunner are you like me surprised by this behavior?

**Comment by sbrunner** [comment]
No, the cache invalidation works only if we modify the database with the admin interface, not with direct SQL modification!

But you can invalidate it manually by calling: `<instance_id>/wsgi/invalidate` :-)

**Comment by elemoine** [comment]
> No, the cache invalidation works only if we modify the database with the admin interface, not with direct SQL modification!

Oops true, I had forgotten about that. The "after_insert", "after_udpate" and "after_delete" events are triggered when an insert, update, delete occurs through the SQLAlchemy mapped class.

**Comment by elemoine** [comment]
@jaykayone what do you think? Is this a problem for you?

**Comment by jaykayone** [comment]
I guess this is per host? Which means that if we use load balancing techniques, it has to be invalidated per host? that's not ideal ...

**Comment by elemoine** [comment]
> I guess this is per host?

Correct.

**Comment by sbrunner** [comment]
We don't already test-it but il should be possible to put the cache in one memcachd server and the the invalidation should work on all the cluster...
Should be investigated :-)

**Comment by elemoine** [comment]
See http://dogpilecache.readthedocs.org/en/latest/api.html#memcached-backends.

**Comment by sbrunner** [comment]
Should be fixed by #565
