### ISSUE TITLE
Piwik tracking integration

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#430]
Just a note to say we need to integrate Piwik tracking in the app. 

One option:  http://luisfarzati.github.io/angulartics/

**Comment by petzlux** [comment]
This is actually quite important to have even just a basic tracking working from the start that we publish as a beta

**Comment by petzlux** [comment]
see #751

**Comment by jaykayone** [comment]
we need a minimal version for the launch, even if it does not use angular

**Comment by petzlux** [comment]
see #815 for minimal integration for now

**Comment by jaykayone** [comment]
add tracking for the prints

**Comment by rmichaelis** [comment]
Tracking for the prints is Done. Should we consider this issue as solved?  Or move it back to the backlog ?

**Comment by jaykayone** [comment]
move to backlog
i want to integrate siteids and layers
