### ISSUE TITLE
wmts config

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#431]
the application does not use the url configured in the themes response

```
{"style": "default", "name": "basemap_2015_global", "url": "http://wmts.geoportail.lu/mapproxy/wmts/1.0.0/WMTSCapabilities.xml", "matrixSet": "GLOBAL_WEB_MERCATOR", "dimensions": {}, "type": "WMTS", "id": 1617, "imageType": "image/png", "metadata": {"exclusion": "[1,2]"}}
```

request that is sent:
```
http://wmts.geoportail.lu/mapproxy_4_v3/wmts/basemap_2015_global/GLOBAL_WEBMERCATOR/9/265/174.png
```

**Comment by elemoine** [comment]
Could you please be more specific? The "url" included in the themes response is the capabilities URL. Are you suggesting the client code should make a WMTS capabilities request?

**Comment by jaykayone** [comment]
I thought it was doing that, I am not necessarliy suggesting it.

Otherwise I don't see why we have to configure it on the server side

**Comment by elemoine** [comment]
We use `name` and `imageType` (and `exclusions`). The rest is [hardcoded](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/layerfactoryservice.js#L66-L106) in the js code.

We could make WMTS GetCapabilities request but this means more complexity, and more requests before being able to display a WMTS request.

**Comment by elemoine** [comment]
@jaykayone Can this be closed for now?

**Comment by jaykayone** [comment]
yes
