### ISSUE TITLE
search on mobile

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#433]
does not work yet

Restant c2c 01/05/2015 1j

**Comment by pgiraud** [comment]
What is expected?
Do you remember if we had discussions regarding this?

**Comment by petzlux** [comment]
well needs adjustments for responsive mode, basically, on search icon click on mobile, should open pane as in old geoportail mobile app , filling whole screen to display search results

**Comment by pgiraud** [comment]
See #501
