### ISSUE TITLE
geolocation

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#436]
geolocation does not force a refresh of the position of the device.

in this case i had to open google maps to refresh my position and then it was also OK in the devv3 page

**Comment by jaykayone** [comment]
@pgiraud: on avait eu le même problème lors du développement de l'app. est-ce que tu t'en rappelles?

**Comment by rmichaelis** [comment]
Dans luxmob ces 3 options sont  settées : enableHighAccuracy: true,maximumAge: 60000,timeout: 7000

Je vais essayer et voir si ca corrige le problème

**Comment by rmichaelis** [comment]
@jaykayone j'ai ajouté les options. Peux-tu tester sur devv3rm ?

**Comment by jaykayone** [comment]
oui semble mieux après un premier test
