### ISSUE TITLE
Buttons stay active (focused) after tap on mobile

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#437]
the geolocation button can sometimes not be deactivated

**Comment by elemoine** [comment]
Do you know how to reproduce that issue?

**Comment by jaykayone** [comment]
https://youtu.be/hqoy8IzIUAA

**Comment by elemoine** [comment]
Problem observed on an iPhone 6 (latest iOS version).

**Comment by pgiraud** [comment]
@jaykayone can you confirm that this is due to the fact that buttons don't loose the focus after being tapped? Same happen for zoom, full extent and also navigation bars buttons.

**Comment by jaykayone** [comment]
Yes that seems to be the reason

**Comment by pgiraud** [comment]
Similar issue is actually reported in Ol3.
https://github.com/openlayers/ol3/issues/3500
Though a fix for OL3 will not fix our issue directly, it will probably help us understand it.
