### ISSUE TITLE
localstorage and private mode in safari

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#438]
when using private mode in safari, the application does not start because the accessing of the localstorage throws an uncaught error

**Comment by elemoine** [comment]
So I guess should check that the local storage is available before attempting to store the application state into it.

**Comment by jaykayone** [comment]
i think the problem is not only when storing but also when reading it..

**Comment by elemoine** [comment]
> i think the problem is not only when storing but also when reading it..

Yes, true.
