### ISSUE TITLE
Two blank layers

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#440]
I see two « blank » layers in the background layer selector locally with my dev environment. Am I the only one seeing this problem?
![doubleblank](https://cloud.githubusercontent.com/assets/76594/7471950/622f380c-f32d-11e4-8581-5c3a7210637b.png)

**Comment by petzlux** [comment]
@jaykayone knows about this.

**Comment by jaykayone** [comment]
You need to delete the blank layer by sql

**Comment by elemoine** [comment]
> You need to delete the blank layer by sql

Got it. Thanks.

**Comment by elemoine** [comment]
This is fixed. We removed the "blank" layer from the database on our server.
