### ISSUE TITLE
Names are truncated

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#443]
In version V2, the names are only displayed once. And sometimes, it appears that names are truncated.
Do you have any idea where this problem come from ?
![image](https://cloud.githubusercontent.com/assets/5594996/7494016/8614c0ec-f405-11e4-893e-f78f03389c47.png)

**Comment by jaykayone** [comment]
this is certainly a metatiling issue in mapproxy, I'll have to check that, thanks for noticing
