### ISSUE TITLE
Default theme layout

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#444]
We need a default theme layout other than a transparent one.
http://devv3.geoportail.lu/renaud/theme/test

**Comment by elemoine** [comment]
Couldn't we use the `main` theme if the theme specified in the URL does not exist.

**Comment by jaykayone** [comment]
Yes we could, but it concerns another issue

**Comment by elemoine** [comment]
So I don't understand that particular issue.

**Comment by jaykayone** [comment]
it is about css

**Comment by elemoine** [comment]
CSS for unknown/non-existing themes? The URL provided by @rmichaelis has the theme "test" specified.

**Comment by jaykayone** [comment]
test is a known theme but it has no css style defined. there should be a fallback style
