### ISSUE TITLE
Correctly handle protected themes

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#446]
Some themes are protected, and accessing them requires authenticating. When an anonymous user loads the application with a protected theme specified in the URL he should be redirected to a login page.

**Comment by jaykayone** [comment]
1) ouvrir la fenêtre de login (non modal)
2) rajouter un texte dans le catalogue qui informe que l'utilisateur doit se loguer

si un permalien contient des couches qui sont protégées il faut réinterpréter le permalien après le login pour les afficher

**Comment by jaykayone** [comment]
il y a un souci qu'on ne sait pas si un thème est protégé.
quand on n'est pas logué, on ne sait pas si le thème existe. il faut un moyen pour le tester.
A coordonner entre @rmichaelis et @elemoine
