### ISSUE TITLE
Active language not in url params

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#447]
Is this desired , when sharing ?

**Comment by jaykayone** [comment]
yes

**Comment by petzlux** [comment]
So, we dont want language in url params, so that next user using link can use his language preferences . Can we close this question ?

**Comment by elemoine** [comment]
Related to the "language preferences": note that, currently, the initial locale is [hardcoded](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/86a6f3f619d8e137f140b35e09fb81e9eb98ad50/geoportailv3/static/js/maincontroller.js#L143) to `fr`. Instead, we should probably use the browser language. Note that ngeo provides a [service](https://github.com/camptocamp/ngeo/blob/master/src/services/getbrowserlanguage.js) to get the browser language.

**Comment by petzlux** [comment]
Okay can do that , will open new issue
