### ISSUE TITLE
clic sensitivity on tablet

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#449]
all the actions needing a single clic like the info bar, drawing a profile etc work on a tablet but it is very hard to find the correct time the finger needs to be pressed. too short and nothing happens, too long and the system (android) wants to do copy/paste

is this configurable in OL3?

**Comment by elemoine** [comment]
Clicks on the map are handled by OpenLayers 3 while clicks outside the map are handled by Angular. For clicks outside the map we should probably use the `ngTouch` module for responsive clicks. For clicks on the map this sounds like a problem (bug) in OpenLayers 3. We will need to test that.

**Comment by jaykayone** [comment]
all the problems I mentioned were in the map.

**Comment by elemoine** [comment]
You mentioned the info bar, which confused me.

**Comment by jaykayone** [comment]
yes but what I meant was the clic on the map to update the coordinates and elevation in the info bar, sorry

**Comment by elemoine** [comment]
Could you please test with http://openlayers.org/en/master/examples/draw-features.html?

**Comment by petzlux** [comment]
@elemoine please check the following video for an example on our Samsung Galaxy Tab S 10.5

https://youtu.be/JV4wIxGyYEM

**Comment by pgiraud** [comment]
I reported this as an issue in OpenLayers https://github.com/openlayers/ol3/issues/3724

**Comment by elemoine** [comment]
I have created an ol3 PR for that issue: https://github.com/openlayers/ol3/pull/3766. The PR adds a `clickTolerance` option to the Draw interaction.

@jaykayone, @petzlux, could you please try using http://erilem.net/ol3/draw-click-tolerance/examples/measure.html with your Android tablets? In this example, `clickTolerance` is set to `6` pixels.

If this does improve things, and if the ol3 PR is merged, we will still need to update ngeo to make the measure interactions configurable.

**Comment by petzlux** [comment]
Much better, entirely usable now on the Samsung Galaxy Tab S 10.5 !

**Comment by elemoine** [comment]
This should be fixed now that we use ol3 master again.
