### ISSUE TITLE
Measure tools do not show numerical result (tablet)

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#450]

**Comment by elemoine** [comment]
See also https://github.com/camptocamp/ngeo/issues/189.

**Comment by elemoine** [comment]
Question from Pierre: on touch devices can we just display the final measure result? Response from Luxembourg: yes.

**Comment by pgiraud** [comment]
https://github.com/camptocamp/ngeo/pull/234 should have fixed the issue.
It works perfectly in debug mode but not in built mode.

**Comment by pgiraud** [comment]
This pull request fixed the issue. https://github.com/openlayers/ol3/pull/3775
However we currently use a fixed version of OL which doesn't include this patch.
I leave the current issue open until we update OL.

**Comment by pgiraud** [comment]
Should be fixed now that we're using master version of OL3 again.
