### ISSUE TITLE
Get browser language preferences 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#451]
Related to comment in #447 

Use https://github.com/camptocamp/ngeo/blob/master/src/services/getbrowserlanguage.js

**Comment by jaykayone** [comment]
get language in the following order:

1) from URL
2) from localstorage
3) from browser pref

**Comment by elemoine** [comment]
Precision: when the user selects a language using the language selector the language is added/updated in URL and in the local storage.

**Comment by elemoine** [comment]
Another precision for 3) (from browser pref): we may want to read the browser pref language from the server, because the server already filters the language lists based on the languages it supports.

**Comment by petzlux** [comment]
fixed by #545
