### ISSUE TITLE
Problems with POI_BY_ID requests

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#459]
POI_BY_ID requests don't work correctly in the new portal:

http://devv3.geoportail.lu/main/wsgi/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=png&TRANSPARENT=true&LAYERS=699&CRS=EPSG%3A3857&STYLES=&WIDTH=1862&HEIGHT=1207&BBOX=678192.2112560247%2C6375683.156367606%2C687087.570422712%2C6381449.374688869

**Comment by rmichaelis** [comment]
It seems to be a problem with the poi manager

**Comment by rmichaelis** [comment]
Problem solved in poi manager
