### ISSUE TITLE
Print - Notification of PDF being generated

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#462]
Currently the user doesn't know what happens when he/she clicks on the PDF button. The system should inform the user that something is currently happening.

In GeoAdmin.ch, here's how they do it:
![screenshot from 2015-05-19 15 23 23](https://cloud.githubusercontent.com/assets/319774/7703873/0f72a022-fe3b-11e4-81fa-1bf317875e8a.png)

Here's what I propose:
 - disable the button,
 - add a spinner with a generating text,
 - add a button or a link to abort PDF creation.

![screenshot from 2015-05-19 15 12 31](https://cloud.githubusercontent.com/assets/319774/7703789/94547c80-fe3a-11e4-9ee6-5b504f0dc218.png)

For tracking, here's how the HTML could look like:
```HTML
<div class="col-md-12" style="
    line-height: 36px;
"><button type="submit" class="btn btn-default pull-right" ng-click="ctrl.print()" disabled="">PDF</button><span class="pull-right" style="
    color: lightgray;
">
  <i class="fa fa-refresh fa-spin"></i>
  generating <a href="" class="" style="
    color: white;
">abort</a>&nbsp;&nbsp;</span>
      
    </div>
```

**Comment by elemoine** [comment]
@pgiraud, are you able to work on that? If not tell me and I'll give it a try.
