### ISSUE TITLE
Print form translations

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#466]
Texts in the print form do not change when switching locale.

**Comment by pgiraud** [comment]
The `translate` filter are there.
Is it due to missing translated strings in the .po files then?

**Comment by elemoine** [comment]
@petzlux, any comment about that?

**Comment by petzlux** [comment]
probably missing strings, will check

**Comment by petzlux** [comment]
@rmichaelis can you review please?
