### ISSUE TITLE
Print legend support

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#467]
Legends are not currently printed, but they should be.

**Comment by sbrunner** [comment]
@elemoine actually is it possible to have a legend argument ?

If not is it possible to add a legend with the structure:
```
legend: [{name="<wiki_name>"}, ...]
```
?

**Comment by elemoine** [comment]
Could you please clarify your questions? Are you talking about the print specifications?

**Comment by sbrunner** [comment]
Yes, the arguments in the print spec.

**Comment by elemoine** [comment]
The application can easily extend the print specifications object returned by ngeo's `createSpecs` function. Please tell me if that doesn't answer the question…

**Comment by jaykayone** [comment]
Legends are now printed, but they are hard-coded
