### ISSUE TITLE
Too many watchers…

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#475]
With the "main" theme we currently have 1609 watchers. That's a lot!

By removing the catalog component from the page we're down to 137 watchers, so the catalog component sets up 1472 watchers by itself.

With https://github.com/Geoportail-Luxembourg/geoportailv3/pull/354 (Theme Switcher) we changed a number of expressions from "one-time binding" to "always binding". Most probably for good reasons… 

But I cannot observe problems when I re-add "one-time binding" expressions. See https://github.com/Geoportail-Luxembourg/geoportailv3/compare/elemoine_onetimebinding. With this branch I have 941 watchers instead of 1609, which would be a major drop.

@rmichaelis are you able to tell what won't work with my branch?

**Comment by rmichaelis** [comment]
You are right, it seems to work as expected. 
I'm not able to reproduce the problem we had. The main categories and layers belonging to these are loaded without any problem.

Maybe a misunderstanding due to the old partials cache mechanism ??

**Comment by jaykayone** [comment]
wasn't it an issue with translations when changing the language?

**Comment by elemoine** [comment]
> wasn't it an issue with translations when changing the language?

I tested it, and could come up with a case where it did not work.

**Comment by jaykayone** [comment]
and now ? :)

**Comment by elemoine** [comment]
> and now ? :)

What do you mean?

**Comment by jaykayone** [comment]
ah you added a "not" to your comment, then I can delete my answer

**Comment by elemoine** [comment]
Yeah, sorry, I was too fast.
