### ISSUE TITLE
One concern with the short URL stuff

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#476]
Currently a short URL is created each time the URL changes, which means each time the map moves. Don't we run the risk to insert too many short URLs in the database?

**Comment by jaykayone** [comment]
in geoportailv2, we only generated short links when the panel was open

**Comment by elemoine** [comment]
> in geoportailv2, we only generated short links when the panel was open

Oh ok, that's the way it works in v3 as well. Closing then…

**Comment by elemoine** [comment]
Reopening this issue for discussion… because we still generate a lot of short links if the user left the share window opened.

**Comment by jaykayone** [comment]
what do you propose? deceleration ?

**Comment by elemoine** [comment]
Yes, debouncing in one option. Another option is to generate the short link when the user opens the share window and not update it while the window is opened.

**Comment by jaykayone** [comment]
create a task in the db to delete short links that have never been clicked after some time
