### ISSUE TITLE
Support cancelling a print job

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#478]
It should be able to cancel a print job (to trigger another one for example). MapFish Print does provide a way to cancel a job: `DELETE /cancel/<ref>`.

**Comment by elemoine** [comment]
Canceling a job is currently not supported by c2cgeoportal's print proxy. See https://github.com/camptocamp/c2cgeoportal/issues/1357.

**Comment by sbrunner** [comment]
Fixed by #565
