### ISSUE TITLE
theme icon placement

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#482]
can you make a propsition where the icon is shown at the left side of the search box?
what's more is that it does not seem to be vertically centered

Another idea we had was that a clic on the icon would open the theme switcher.
what do you think?

**Comment by pgiraud** [comment]
Fixed via #488.

**Comment by pgiraud** [comment]
The icon is not correctly aligned on small devices. This is due to the fact that the navbar is smaller.
![screenshot from 2015-05-26 14 05 48](https://cloud.githubusercontent.com/assets/319774/7812208/819210fa-03b0-11e5-913a-bf365c49296b.png)

Reopening issue.

**Comment by pgiraud** [comment]
Also missplaced on small width devices.
![screenshot from 2015-05-26 14 12 41](https://cloud.githubusercontent.com/assets/319774/7812311/5fbcad54-03b1-11e5-9198-8cd23ad87c6a.png)

**Comment by pgiraud** [comment]
I propose we remove this icon on small devices.

**Comment by jaykayone** [comment]
ok

**Comment by pgiraud** [comment]
Addressed in #501.
