### ISSUE TITLE
print form - dropdown styling

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#486]
in the print panel the drop down lists should use the same technique than for background layers, the ones you are using now use OS dependent styling

**Comment by pgiraud** [comment]
Hey @jaykayone,
You're describing 2 different issues here. One is about styling whereas the other is more technical.
Can you please split this issue into 2?

**Comment by jaykayone** [comment]
done

**Comment by pgiraud** [comment]
Is there an issue for the print dropdown styling?

**Comment by pgiraud** [comment]
Sorry I didn't figure out that this was already taken into account in the code.
