### ISSUE TITLE
Is the magnifier icone really useful

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#490]
The search used autocompletion.
Plus, the button is not visually associated to the input field.

![screenshot from 2015-05-21 10 06 02](https://cloud.githubusercontent.com/assets/319774/7744124/0d2c632c-ffa1-11e4-91d6-ba9f9f589da1.png)

What about completely removing this button?

**Comment by elemoine** [comment]
And this magnifier icon confused me the other day. It is very similar to the "person" and "world" buttons next to it, making me believe that it was clickable and part of the toggle group.

**Comment by jaykayone** [comment]
we discussed about this yesterday too.
our conclusion was that if there is no magnifier icon, people will not understand that it is a searchfield

**Comment by petzlux** [comment]
Can we move the magnifier icon inside the search field ? 

See http://stackoverflow.com/questions/18838964/add-bootstrap-glyphicon-to-input-box

**Comment by pgiraud** [comment]
@jaykayone what's your opinion? Should I work on this and try to put the icon in the search field?

**Comment by jaykayone** [comment]
yes, please make a try
