### ISSUE TITLE
regression on theme switcher look

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#491]
There is a regression 

in the theme switcher the text and icon colors is wrong now.
![screen shot 2015-05-21 at 10 09 14](https://cloud.githubusercontent.com/assets/1518019/7744186/7c3121d6-ffa1-11e4-9a6f-b29a3f8bdfa5.png)
![screen shot 2015-05-21 at 10 06 17](https://cloud.githubusercontent.com/assets/1518019/7744185/7c2f0e00-ffa1-11e4-92db-7a1b9a5198e5.png)

I am not sure how it was before but I'd say it was using light gray as text and icon color instead of a theme dependant one

**Comment by rmichaelis** [comment]
you can compare with an old version here : http://devv3.geoportail.lu/renaud/theme/main
