### ISSUE TITLE
Mobile layout needs work

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#497]
In mobile view and on touch devices, the catalog items have the following problems:

The items are on the small side for touch targets, especially on mobile
The _info_ button and _add to my layers_ checkbox are too close together, users have difficulty touching the right item.

**Comment by elemoine** [comment]
To be discussed… There are probably more touch-related (or small screen related) problems…

**Comment by pgiraud** [comment]
There are some size and positioning parameters we can change in order for the application to be more usable on small touch device screens.
In the image below there are several options we can play with.
![mobile_layout](https://cloud.githubusercontent.com/assets/319774/8204765/3dcba9a2-14eb-11e5-97c8-aa43d37498d7.png)

**Comment by petzlux** [comment]
I prefer the last version , it would both provide significantly more space to the catalog (the Layer header is kind of redundant anyway), and give more space to individual catalog items as tap targets. We will have to see if moving the i to the right makes sense or not.

**Comment by pgiraud** [comment]
@jaykayone what's the future action for this issue?

**Comment by jaykayone** [comment]
let us move it to m2

**Comment by petzlux** [comment]
Regarding the selection of features in mobile view. Can we not similar to the present day mobile app, show a simple Counter of features selected next to Info Button, before opening Info window?

**Comment by jaykayone** [comment]
to be discussed ... the UX of the current implementation is not ideal either ..
