### ISSUE TITLE
Error with forEachLayerAtPixel

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#502]
Hello,

I try to use the openlayers ``forEachLayerAtPixel`` functionality, but it returns this error :
``SecurityError: The operation is insecure.
var imageData = this.context_.getImageData(
canvast...erer.js (line 466)``

Did you already use it with success or did you already experience such problem ?

**Comment by elemoine** [comment]
That is expected if there are layers whose HTTP origins are not the same as that of the page. The "layer at pixel" functionality relies on Canvas' `getImageData`, which throws an exception if the "same origin policy" test doesn't pass.

**Comment by jaykayone** [comment]
is this a geoportal vs geoportail issue? or do the subdomains have to match?

**Comment by rmichaelis** [comment]
In my example, I only have images coming from wmts.geoportail.lu and the page is devv3rm.geoportail.lu Then I think the subdomain has to match too.

**Comment by elemoine** [comment]
Indeed, see http://en.wikipedia.org/wiki/Same-origin_policy#Origin_determination_rules.

CORS headers could probably be used…

**Comment by jaykayone** [comment]
any idea how swisstopo managed this?
CORS headers would have to be set on the reverse proxy I guess?

**Comment by elemoine** [comment]
It looks like they use CORS. See https://github.com/geoadmin/mf-geoadmin3/commit/f87ead09b4e8c186f6c4721700759b31efd7e272. It also looks like they had problems with IE 9 and 10: https://github.com/geoadmin/mf-geoadmin3/commit/546ce656816edad9309c8e8bbd4778b172758abf.

**Comment by rmichaelis** [comment]
Do you have any idea why i'm able to request wms with cors header with apache and not with pserve ?

**Comment by rmichaelis** [comment]
example editus_poi here http://devv3.geoportail.lu/renaud/ is working fine
and here http://devv3rm.geoportail.lu/ is returning this error : ``Image from origin 'http://devv3.geoportail.lu' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://devv3rm.geoportail.lu' is therefore not allowed access.``

**Comment by jaykayone** [comment]
could this help? https://github.com/monsur/cors-python

**Comment by jaykayone** [comment]
CORS: Add headers to WSGI on devv3 machine
