### ISSUE TITLE
layout adaptations for govbar

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#505]
*  Utiliser la font Arial pour le contenu applicatif sur la droite (et pas la DIN) --> Arial comme fallback
*  Remplacer le box-shadow par un filet simple(header : border-bottom: 1px solid #ccc;    box-shadow: 0 1px 1px -1px rgba(0, 0, 0, 0.2);) --> OK
·        Utiliser du blanc pour la govbar dans son entièreté(.navbar-default : background-color: #fff;    border-color: #e7e7e7;) -> OK
·        Diminuer légèrement la taille des icônes pour être dans une proportion égale aux 2 lignes de texte du logo de droite (button.icon::after:font-size:2em -> 1.7em;) -> NON

**Comment by petzlux** [comment]
Without a drop shadow, there is no visual hierarchy between the header toolbar and the map display. I would keep it  .... 

![screen shot 2015-05-28 at 08 24 19](https://cloud.githubusercontent.com/assets/2540428/7853780/01cb90c6-0513-11e5-8ade-51620d33d748.png)

**Comment by jaykayone** [comment]
ok

On Thu, May 28, 2015 at 8:25 AM, Patrick Weber <notifications@github.com>
wrote:

> Without a drop shadow, there is no visual hierarchy between the header
> toolbar and the map display. I would keep it ....
>
> [image: screen shot 2015-05-28 at 08 24 19]
> <https://cloud.githubusercontent.com/assets/2540428/7853780/01cb90c6-0513-11e5-8ade-51620d33d748.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/505#issuecomment-106193767>
> .
>



-- 
Jeff Konnen
