### ISSUE TITLE
Rely on openlayers's or ngeo's tasks scripts instead of having our own copies [c2c]

### ISSUE THREAD

**Issue by sbrunner** [Geoportail-Luxembourg/geoportailv3#51]
Restant c2c 01/02/2015 0.25j
Restant c2c 01/03/2015 0.25j
Restant c2c 01/04/2015 0.25j

**Comment by elemoine** [comment]
Remove unused scripts.

**Comment by sbrunner** [comment]
When I remove them I have an error ...

**Comment by elemoine** [comment]
For information, with `closure-util` new `build` command, we can greatly simplify things, and actually remove most of (if not all) the scripts we have in the `tasks` directory. I'll look into it.
