### ISSUE TITLE
print quality

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#510]
there is a problem with print quality.

print generated here: 

http://devv3.geoportail.lu/main/theme/main?version=3&zoom=15&X=680824&Y=6378491

Options: A4 portrait, 1:10000

**Comment by jaykayone** [comment]
![screen shot 2015-06-02 at 14 15 31](https://cloud.githubusercontent.com/assets/1518019/7935506/db1b44bc-0931-11e5-9a23-78d1d5b2912b.png)

**Comment by jaykayone** [comment]
you use 72 dpi for the moment, setting it to 300 solves the problem

**Comment by elemoine** [comment]
Yes, indeed.
