### ISSUE TITLE
Migrate to HTTPS

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#512]
check if the site works in https mode.

For this to work, all the html references have to be written as =// instead of =http://

**Comment by jaykayone** [comment]
https://devv3.geoportail.lu/main

http is hard coded everywhere

**Comment by elemoine** [comment]
> http is hard coded everywhere

What do you mean by "hard coded everywhere"? We use `static_url` in `index.html` so `http` is not hardcoded there at least.

**Comment by jaykayone** [comment]
I mean that when I load the page in https, most of the requests are sent in http an are therefore blocked

**Comment by elemoine** [comment]
Indeed!

@jaykayone, http://docs.camptocamp.net/c2cgeoportal/master/integrator/https.html may include relevant information, as the problem may be related to proxies (as usual). #proxyhell

**Comment by jaykayone** [comment]
Not sure that's the reason ... In fact, css files, webfonts, js files, XHR requests are all requested over http even after setting   SetEnvIf    X-Https on HTTPS=1 in wsgi conf

**Comment by jaykayone** [comment]
(this is not a prioritary problem though ...) can be worked on later

**Comment by petzlux** [comment]
is this something we should adress soon ?

**Comment by jaykayone** [comment]
yes

**Comment by jaykayone** [comment]
faire le test, si trop compliqué, on fait trop tard
