### ISSUE TITLE
DMS with leading zeroes

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#519]
DMS notation (right click and infobar) should use leading zeroes for minutes and seconds

**Comment by jaykayone** [comment]
seems to be an issue in open layers:
http://openlayers.org/en/v3.6.0/apidoc/ol.coordinate.html#toStringHDMS

http://en.wikipedia.org/wiki/ISO_6709
```
When minutes and seconds are less than ten, leading zeroes should be shown.
```

**Comment by pgiraud** [comment]
It's worth creating an issue in OL3. https://github.com/openlayers/ol3/issues/new

**Comment by jaykayone** [comment]
https://github.com/openlayers/ol3/issues/3776
