### ISSUE TITLE
Switching languages increases the watchers count

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#522]
Each time I change the application language using the lang selector two more Angular watchers are added. This should not happen.

**Comment by elemoine** [comment]
The problem is related to the [elevation directive partial](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/infobar/elevationdirective.js#L35-L36):

```html
<span translate>Elevation: {{ctrl.elevation}} m<span>
```

A new watcher is created each time this partial is re-translated.

If I change the partial to:

```html
<span translate>Elevation: foo m<span>
```

then the problem goes away.

**Comment by jaykayone** [comment]
not a real problem. users don't change language more than once
