### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#532]
We have several problems with the icons (glyphs) webfont we need to address:
 - the infos (query results) icon is not centered,
 - the infobar "i" icon is not displayed on some devices.

The webfont geoportail-icons needs an update.
I'll take this as an opportunity to:
 - remove icons that are not actually used in the map interface,
 - include the geolocate icon instead of using a separate font.

**Comment by petzlux** [comment]
I understand that you will do this ?

**Comment by pgiraud** [comment]
Yes, unless you're willing to do it on your side.

**Comment by petzlux** [comment]
we dont have the tools for editing a webfont ...

**Comment by pgiraud** [comment]
I'll use online tools for that. My first experiments showed that it should be possible.
One question though: do you still have contacts with the design company you worked with earlier?

**Comment by petzlux** [comment]
We would rather not ...

**Comment by pgiraud** [comment]
Fixed via #557.
