### ISSUE TITLE
Click tolerance needs to be adapted to Geometry Type and Input Device

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#536]

**Comment by petzlux** [comment]
Click tolerance should vary according to geometry type : 

Higher tolerance for point symbols
Lower for Surfaces

Click tolerance should also vary according to input device:
Higher for touch devices
Lower for Mouse

**Comment by elemoine** [comment]
What click tolerance are you talking about here?

**Comment by petzlux** [comment]
This one here : https://github.com/Geoportail-Luxembourg/geoportailv3/commit/d8afa0ffbc399ab2a948a37930545f65c49f00c9#diff-8611db398797594a1b2f650400169e1fL253
