### ISSUE TITLE
theme icon still visible on mobile

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#539]
i can still see the (misplaced) icon on mobile![](http://i.imgur.com/WIwxRjk.jpg)

**Comment by pgiraud** [comment]
Are you sure you're running the latest code? The search doesn't work on your instance.

**Comment by jaykayone** [comment]
you are right ... icon is gone after update, but search on mobile does not work. probably related to wsgi mode / routes ?

**Comment by pgiraud** [comment]
Can you please update again to the latest version and build everything? Please make sure that the modules are up-to-date.

**Comment by geoportallux** [comment]
OK works





Jeff Konnen
Chargé d’études – informaticien/Chef de projet

LE GOUVERNEMENT DU GRAND-DUCHÉ DE LUXEMBOURG
Ministère des Finances
Administration du cadastre et de la topographie
Service informatique & Service géoportail

54, avenue Gaston Diderich . L-1420 Luxembourg
Tél. (+352) 44901-261 . Fax (+352) 44901-333
E-mail: jeff.konnen@act.etat.lu

www.act.public.lu www.geoportail.lu



De : Pierre GIRAUD <notifications@github.com<mailto:notifications@github.com>>
Répondre à : Geoportail-Luxembourg/geoportailv3 <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : Thursday 11 June 2015 10:27
À : Geoportail-Luxembourg/geoportailv3 <geoportailv3@noreply.github.com<mailto:geoportailv3@noreply.github.com>>
Objet : Re: [geoportailv3] theme icon still visible on mobile (#539)


Can you please update again to the latest version and build everything? Please make sure that the modules are up-to-date.
