### ISSUE TITLE
Travis complains about unsastified dependency in measure.js

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#540]
Has something changed ? 

info closure-util Getting Closure dependencies
ERR! closure-util Unsatisfied dependency "ol.FeatureOverlay" in script: /home/travis/build/Geoportail-Luxembourg/geoportailv3/node_modules/ngeo/src/ol-ext/interaction/measure.js
make: *** [.build/build.js] Error 1

**Comment by pgiraud** [comment]
https://github.com/openlayers/ol3/blob/fad3cf9672fe440dec8aa439b45119ac235074be/changelog/upgrade-notes.md#v370

**Comment by pgiraud** [comment]
I'll do the required modifications.
