### ISSUE TITLE
FeatureOverlay deprecation

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#544]
I would like to work on #504 , but this issue is related to the ```ol.FeatureOverlay``` in both query and search directives.
As @elemoine  said in his comment (https://github.com/Geoportail-Luxembourg/geoportailv3/pull/541#issuecomment-111039921), we need to think globally about this problem.

Migrating ```ol.FeatureOverlay``` does not mean only replacing it by  ```ol.layer.Vector``` , but also having a mechanism to keep the layer on top of the map.

Should we have a global drawing layer that each directive uses?
Or should have each directive his dedicated drawing layer ?
Should we create a dedicated drawinglayer service that manages the drawing layers ?

I would like your advice.

**Comment by elemoine** [comment]
What we could possibly do is create a service that wraps an "unmanaged" vector layer. That service will expose a `getIndex` method, which any consumer would call first. This index would then be passed to subsequent operations, like `setStyle`, `addFeature`, `removeFeature` and `clear`.

For example:

```js
/**
 * @constructor
 * @param {app.VectorOverlay} appVectorOverlay
 * @ngInject
 */
app.MyController = function(appVectorOverlay) {
  /**
   * @type {app.VectorOverlay}
   * @private
   */
  this.vectorOverlay_ = appVectorOverlay;

  /**
   * @type {number}
   * @private
   */
  this.vectorOverlayIndex_ = appVectorOverlay.getIndex();

  var styles = [
    new ol.style.Style({
      // …
    }
  ];
 
  appVectorOverlay.setStyle(styles, this.vectorOverlayIndex_);
};


/**
 * @param {ol.Feature} feature
 */
app.MyController.prototype.addFeature = function(feature) {
  this.vectorOverlay_.addFeature(feature, this.vectorOverlayIndex_);
};
```

**Comment by elemoine** [comment]
Work started in [elemoine_vector-overlay branch](https://github.com/Geoportail-Luxembourg/geoportailv3/compare/elemoine_vector-overlay).

**Comment by elemoine** [comment]
Fixed with https://github.com/Geoportail-Luxembourg/geoportailv3/pull/560.
