### ISSUE TITLE
Compilation failed 

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#546]
Since a clean all,  the compilation failed :
searchdirective.js:570: ERROR - Bad type annotation. Unknown type jQuery.event

Travis failed too. 

Any idea about what has been changed ?

**Comment by pgiraud** [comment]
Can you try after an update of submodules?

**Comment by pgiraud** [comment]
Forget my last comment.
https://github.com/camptocamp/ngeo/pull/233

**Comment by elemoine** [comment]
Closed with https://github.com/Geoportail-Luxembourg/geoportailv3/pull/551.
