### ISSUE TITLE
[mobile] "i" infobar button is on top of left panels

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#559]
![img_4435](https://cloud.githubusercontent.com/assets/319774/8183537/16b8f458-1439-11e5-9aa4-8bc395256a50.PNG)

**Comment by jaykayone** [comment]
@pgiraud are you working on this?

otherwise I pass it to @rmichaelis

**Comment by ybolognini** [comment]
@pgiraud not at the office today. Eric told me he wasn't working on this. I pass the issue to @rmichaelis
