### ISSUE TITLE
Strange build message

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#566]
`find: ‘geoportailv3/static/mobile/app’: No such file or directory` 

this is new, doesnt seem to have any purpose?

**Comment by elemoine** [comment]
Related to the c2cgeoportal update?

**Comment by elemoine** [comment]
I just got the same error!

**Comment by sbrunner** [comment]
Due an upgrade I have this folder ...
I will fix it :-)

**Comment by elemoine** [comment]
Thanks @sbrunner.
