### ISSUE TITLE
pan with a long press is failing 

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#576]
On Samsung galaxy tab 2 : 
When I pan with a long press, the info panel opens and then the navigation is broken.

![image](https://cloud.githubusercontent.com/assets/5594996/8254598/494785d4-169a-11e5-97f4-41fae8522e5f.png)

**Comment by jaykayone** [comment]
@petzlux what about the newer version of android on the other tablet?

**Comment by jaykayone** [comment]
does not happen on the latest android. what version of android and what browser are you using?

**Comment by rmichaelis** [comment]
Android 4.1.2
it fails with "default browser"
it works fine with chrome
