### ISSUE TITLE
TouchEvent is not defined

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#579]
I receive oft (not always) this error during the page loading.
Any idea ? 

Error: TouchEvent is not defined
app.LocationinfoController.prototype.showInfoPane_@http://devv3rm.geoportail.lu/proj/db871e3a60ec495cb0005c2495aa9525/js/locationinfo/locationinfodirective.js:285:1
app.LocationinfoController@http://devv3rm.geoportail.lu/proj/db871e3a60ec495cb0005c2495aa9525/js/locationinfo/locationinfodirective.js:237:7
invoke@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:4138:14
$ControllerProvider/this.$get</</<@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:8376:11
nodeLinkFn/<@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:7624:13
forEach@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:330:11
nodeLinkFn@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:7623:11
compileTemplateUrl/<@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:7884:1
processQueue@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:13071:27
scheduleProcessQueue/<@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:13087:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:14287:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:14103:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:14391:13
done@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:9567:36
completeRequest@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:9752:7
requestLoaded@http://devv3rm.geoportail.lu/node_modules/angular/angular.js:9695:1
	

return logFn.apply(console, args);

**Comment by elemoine** [comment]
In Firefox? It looks like `TouchEvent` is defined in Chrome but not in Firefox.

**Comment by rmichaelis** [comment]
Yes in Firefox.

**Comment by elemoine** [comment]
So I think doing this:

```js
  if (eventOrCoordinate instanceof MouseEvent ||
      eventOrCoordinate instanceof TouchEvent) {
```

is not correct.

What's the purpose of this test exactly?

I'd recommend using `showInfoPaneCommon_`, `showInfoPaneEvent_` and `showInfoPaneCoordinate_` instead of using this test. The function names are just examples obviously.

**Comment by petzlux** [comment]
@elemoine 

Following on from discussion, do we need to integrate a browser/device sniffer library, like the swiss geoportal ?  

https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/BrowserSnifferService.js

In this case, I wanted to distinguish behaviour between a device with a mouse and a touch input, but it seems that different browsers do different things.
