### ISSUE TITLE
Location Info open on load distorts map

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#585]
If a permalink with crosshair=true is loaded, the map view is distorted.

**Comment by pgiraud** [comment]
There's no animation when the side panel is open with "crosshair=true".

**Comment by pgiraud** [comment]
For now, I've found that the `$animate:close` event is fired immediately after `$animate:before` ie. even if the animation hasn't finished yet. See https://github.com/camptocamp/ngeo/blob/master/src/directives/resizemap.js#L58
Adding a timeout to wait before opening the info panel works but is hackish.
