### ISSUE TITLE
integrate legend printing in application

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#591]
Legends are now printed, but they are hard-coded

**Comment by jaykayone** [comment]
actually, it is not only the legends,

points that are not OK in the current implementation:

- scalebar is in webmercator, should be in LUREF (there is a setting for that)
- formatting of scale-text: include a thousand-separator

**Comment by jaykayone** [comment]
![screen shot 2015-06-24 at 13 51 35](https://cloud.githubusercontent.com/assets/1518019/8329247/2f380646-1a78-11e5-9c70-1ad719bb413f.png)

**Comment by elemoine** [comment]
> scalebar is in webmercator, should be in LUREF (there is a setting for that)

What's this setting?

**Comment by jaykayone** [comment]
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/print/print-apps/geoportailv3/requestData.json#L17
