### ISSUE TITLE
logout route

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#592]
Hello @sbrunner ,

Logout does not work anymore in geoportailv3 since this . 
https://github.com/camptocamp/c2cgeoportal/blob/c8c34ec7b8a1fb0cfecfb0193a4e2f51b83b8a5a/c2cgeoportal/__init__.py#L486

Before modifying the code, I would like to know if there is a reason to limit the logout route to the GET method ?

**Comment by elemoine** [comment]
@rmichaelis you do not use GET for logging out?

**Comment by rmichaelis** [comment]
no, we do use POST. 
I read a lot of threads regarding the POST/GET philosophy for logging out, but I would like to know your mind about that.

**Comment by elemoine** [comment]
I don't know about the GET vs POST philosophy for logging out, but I think c2cgeoportal could allow both methods. @sbrunner?

**Comment by sbrunner** [comment]
In c2cgeoportal 1.6.0rc1 it's possible to logout only with the GET method. It needed we can modify this...
