### ISSUE TITLE
layout problem in print form while printing

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#594]
![screen shot 2015-06-24 at 13 35 00](https://cloud.githubusercontent.com/assets/1518019/8329267/51428ce8-1a78-11e5-8571-6fc7d227df51.png)

**Comment by elemoine** [comment]
Could you please specify the browser?

**Comment by jaykayone** [comment]
sorry, firefox 38.0.5 on Mac OS

**Comment by rmichaelis** [comment]
same problem with chrome on Windows.
