### ISSUE TITLE
vector print

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#595]
location info marker is not printed

**Comment by jaykayone** [comment]
![screen shot 2015-06-24 at 13 59 06](https://cloud.githubusercontent.com/assets/1518019/8329378/525c796c-1a79-11e5-8448-778cbaf2ba0b.png)
![screen shot 2015-06-24 at 13 59 34](https://cloud.githubusercontent.com/assets/1518019/8329379/551b6050-1a79-11e5-9688-117e4a033ed5.png)

**Comment by elemoine** [comment]
Indeed, unmanaged vector layers are not printed. At this point I don't how to address that issue.

**Comment by jaykayone** [comment]
it's the same for highlight after search.
we will have to find a solution for this

**Comment by rmichaelis** [comment]
Should a feature info be printed ?

**Comment by petzlux** [comment]
Should all features from `appVectorOverlay` layers be printed as seen on the map ?

**Comment by jaykayone** [comment]
Yes, people are using this intensively in v2

**Comment by rmichaelis** [comment]
I mean with the feature info text

**Comment by elemoine** [comment]
> Should all features from appVectorOverlay layers be printed as seen on the map ?

Yes, probably. This requires changes to ngeo. At the moment, ngeo only prints layers.

**Comment by elemoine** [comment]
> I mean with the feature info text

Sounds a different issue, right?

**Comment by jaykayone** [comment]
Yeap, I am with you Eric, that's a different issue.
@petzlux can you please add a new one for the info text printing?

**Comment by jaykayone** [comment]
any upate here?

**Comment by elemoine** [comment]
> any upate here?

Yep, see https://github.com/Geoportail-Luxembourg/geoportailv3/pull/639.

**Comment by jaykayone** [comment]
cool
