### ISSUE TITLE
print resolutions

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#597]
the zoom levels in the print are totally different than the ones on screen

**Comment by jaykayone** [comment]
Screen:

![screen shot 2015-06-24 at 14 14 03](https://cloud.githubusercontent.com/assets/1518019/8329669/8927cc6a-1a7b-11e5-9171-eb662bfbc042.png)

Print:

![screen shot 2015-06-24 at 14 14 14](https://cloud.githubusercontent.com/assets/1518019/8329675/94b78e76-1a7b-11e5-8893-910e2f1a4fe5.png)

**Comment by jaykayone** [comment]
point and line symbols are too small

**Comment by elemoine** [comment]
@sbrunner, is this related to the DPI value?

**Comment by sbrunner** [comment]
It's looks like effectively ...

**Comment by elemoine** [comment]
So what is the solution to this problem? You already had the problem if I remember correctly.

**Comment by jaykayone** [comment]
are you talking to me? We had the same problem in v2 indeed and it was never really solved

**Comment by elemoine** [comment]
I was talking to Stéphane :)

**Comment by sbrunner** [comment]
Isn't a missing serverType:
https://github.com/mapfish/mapfish-print/blob/b29dcc21afb709a7bcb3abc52e9c715f4c12b350/examples/src/test/resources/examples/printwms_archsites_server_type/requestData-scale-wms1_0_0.json#L16
?

**Comment by elemoine** [comment]
Could you please provide more explanations?

**Comment by sbrunner** [comment]
It the `serverType` is `"mapserver"` the print add a query params `MAP_RESOLUTION=<DPI>`, see
https://github.com/mapfish/mapfish-print/blob/b29dcc21afb709a7bcb3abc52e9c715f4c12b350/core/src/main/java/org/mapfish/print/map/image/wms/WmsUtilities.java#L96-L119

**Comment by sbrunner** [comment]
Then MapServer can create the symbols with the right size :-)

**Comment by jaykayone** [comment]
OK in this case it will work because it is mapserver in the two examples. 
But if we have wms layers coming from arcgis server it will not be covered I guess.
This concerns all the layers from the water theme
![screen shot 2015-06-24 at 14 39 11]
(https://cloud.githubusercontent.com/assets/1518019/8330051/e54310ec-1a7e-11e5-9e63-00d934f2cd85.png)

![screen shot 2015-06-24 at 14 39 40](https://cloud.githubusercontent.com/assets/1518019/8330054/eb9cbed4-1a7e-11e5-9a42-d445672050ef.png)

**Comment by jaykayone** [comment]
is someone working on this one? 
This is a critical issue for milestone 1

**Comment by sbrunner** [comment]
Not actually, for me the missing information is how it works with ESRI server because it's not an OGC option ... any body know it ?

**Comment by jaykayone** [comment]
there does not seem to be such an option for esri servers.
could it be a compromise to use a different resolution for the wms servers? If I understood the problem right, you are using 300 dpi to query the wms which means that it actually takes data from a totally different scale which makes symbols too small.

Could we simply use 96 dpi in WMS requests in print ?

**Comment by sbrunner** [comment]
And we will have a pixeled layer on the print ... that what you want ?

**Comment by jaykayone** [comment]
that's sure. better than a non readable print :)
i have no other solution for the moment.

**Comment by elemoine** [comment]
FWIW, https://github.com/Geoportail-Luxembourg/geoportailv3/commit/fc82447eafb64a7cb2673dd1d6a779ba75a716d0 changed to print DPI from 72 to 300.

@jaykayone, if the js code had a way to know whether the WMS layer is an ESRI layer or a MapServer layer we could  set `servertype` to `MapPserver` for MapServer layers, and set `DPI` to `96` for ESRI layers.

**Comment by jaykayone** [comment]
We could know it on the serverside by testing the to see if it contains "WMSServer" but on the javascript side we do not have that information for now.

We could add a metadata_ui element is_mapserver and if it is true we use that information, otherwise we use 96 dpi.

Let's do this, I'll add this tag into the db asap

**Comment by elemoine** [comment]
You could add a `serverType` property to `metadata_ui`, set to `'MapServer'` in the case of MapServer layers, and would be `undefined` (or absent) in the case of ESRI layers.

I realize that DPI is a global setting, meaning that we'd use a degraded mode as soon as an ESRI layer is to be printed.

**Comment by jaykayone** [comment]
that's not good. whasn't the comment of stephane aimed to have a differentiatable setting? https://github.com/mapfish/mapfish-print/issues/273

**Comment by elemoine** [comment]
I need to look in this more closely.

**Comment by elemoine** [comment]
So, if the map only includes MapServer layers we can use `"serverType": "MapServer"` and a high DPI value (`300`). In this way we will get a high-resolution print, with correctly sized symbols.

But if the map includes ESRI layers and if we use a high DPI value (`300`) then symbols will be very small in the printed map for the ESRI layers.

As far as I understand, the only way to get correctly sized symbols for ESRI layers is to print the map using a lower DPI value (e.g. `96`). But this also means that we won't get a high-resolution, nice-looking, printed map as long as there's an ESRI layer among the layers to print.

Sorry, I don't see any better solution to this problem.

**Comment by jaykayone** [comment]
couldn't we make a change in mapfishprint that queries a wms of type arcgis always in 96 dpi whatever the desired output resolution is? 
We could then use high resolution for wmts and mapserver and low res for esri ...

how did this work in v2? 

we can't be the only ones facing that problem

**Comment by elemoine** [comment]
I'll talk to print experts tomorrow. 

> how did this work in v2?

I thought you said it never worked for you. Did I misunderstand? 


> we can't be the only ones facing that problem

Not many people with maps including both MapServer and ESRI WMS layers :)

**Comment by jaykayone** [comment]
ad v2: it has never been optimal, but it worked better than in v3

i think the compromise might be to set everything to 96 dpi for now as there are no retina tiles anyway ... if there is no better solution

**Comment by elemoine** [comment]
> couldn't we make a change in mapfishprint that queries a wms of type arcgis always in 96 dpi whatever the desired output resolution is?
> We could then use high resolution for wmts and mapserver and low res for esri ...

Indeed, that may possible. And you were right, this is what https://github.com/mapfish/mapfish-print/issues/273 is about.

**Comment by jaykayone** [comment]
OK, I now made a test.
With the current tile resolutions, you don't see any difference in quality between a print at 96 and 300 dpi.

Let's set the whole config to 96 and the wms sizes will be OK for now.

In Milestone 2, we will then implement a version with high res wmts and wms
