### ISSUE TITLE
Print template language

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#601]
I just realized that there is a conceptual problem.
Texts in print templates are in french. They should be translated though. Where should this translation happen? 

How do we insert the keys into the pot files / transifex ?

**Comment by elemoine** [comment]
I'd suggest that we join our forces and organize a specific call to tackle this issue.

**Comment by sbrunner** [comment]
Related issue: https://github.com/mapfish/mapfish-print/issues/245

**Comment by jaykayone** [comment]
Let's push this to milestone 2

**Comment by jaykayone** [comment]
we stay with french for the moment
