### ISSUE TITLE
crosshair almost true

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#602]
I open the map, my URL contains "crosshair=false".
I do a right click.
My URL changes to crosshair=true
The sidepanel contains a short url.
When I copy and paste that short URL it contains "crosshair=false" and the panel does not open

**Comment by petzlux** [comment]
noted only in Firefox, Chrome doesnt seem to have same problem

**Comment by jaykayone** [comment]
Actually, when I paste a link containing crosshair=true into a new window, it is changed back to crosshair=false in FF

**Comment by jaykayone** [comment]
same thing in safari
