### ISSUE TITLE
Cannot measure small surface

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#608]
The tooltips displayed when measuring a surface  make it impossible to measure the surface of a house.
See this movie:

**Comment by jaykayone** [comment]
![measure2](https://cloud.githubusercontent.com/assets/1518019/8350480/741226a8-1b26-11e5-8b08-1992cdbb29c7.gif)

**Comment by pgiraud** [comment]
This is in our opinion not critical for milestone 1.

**Comment by jaykayone** [comment]
I don't agree

**Comment by sbrunner** [comment]
Shouldn't the popup moved from the `ol-overlaycontainer-stopevent` `<div>' to the `ol-overlaycontainer`?

**Comment by elemoine** [comment]
Thanks @sbrunner. That's a good idea!

See https://github.com/camptocamp/ngeo/pull/250.

**Comment by elemoine** [comment]
https://github.com/camptocamp/ngeo/pull/250 now closed, so closing this as well.
