### ISSUE TITLE
basemap not grey

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#611]
http://devv3.geoportail.lu/main/theme/main?version=3&zoom=16&X=678024&Y=6416558&lang=fr&crosshair=false&layers=555&opacities=0.9&bgLayer=basemap_2015_global

@petzlux can you check this in mapnik please?
there seems to be a problem, the background is white and not grey ..

**Comment by jaykayone** [comment]
problem solved

**Comment by petzlux** [comment]
what was the problem ?

**Comment by jaykayone** [comment]
outdated cache

On Fri, Jun 26, 2015 at 8:21 AM, Patrick Weber <notifications@github.com>
wrote:

> what was the problem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/issues/611#issuecomment-115538809>
> .
>



-- 
Jeff Konnen
