### ISSUE TITLE
catalog refresh is slow after authentication

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#620]
After logging in into the Geoportail, the catalog should reload quicker.
Sometimes I'm waiting 10 seconds before having a catalog refresh.

**Comment by jaykayone** [comment]
I fear it's the 1000 layers from presidence.
I'll make a change

**Comment by jaykayone** [comment]
better?

**Comment by rmichaelis** [comment]
not really.

**Comment by jaykayone** [comment]
upps i fear i made it worse, i think i removed the theme restriction, so now it is slow even when not logged in, I'll repair it this afternoon

**Comment by rmichaelis** [comment]
I had a cache issue.
Removing the 1000 layers from presidence, really improves the performances.
