### ISSUE TITLE
Shorturl fails when user is logged in

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#632]
[Shorturl service](https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/views/shortener.py#L108) complains 
`AttributeError: 'O' object has no attribute 'email'`

The email user attribute is actually named `mail` ! This is a problem in C2C

**Comment by petzlux** [comment]
@jaykayone doesnt this need to be fixed before we go public?

**Comment by jaykayone** [comment]
@sbrunner what is the status here?

**Comment by sbrunner** [comment]
I can't reproduce it, what's the error trace ?

**Comment by rmichaelis** [comment]
[Mon Jul 13 12:23:01.215434 2015] [:error] [pid 39262] 2015-07-13 12:23:01,215 INFO  [c2cgeoportal.views.entry][Dummy-1] User 'fk' logged in.
[Mon Jul 13 12:23:04.833082 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] Error - <type 'exceptions.AttributeError'>: 'O' object has no attribute 'email'
[Mon Jul 13 12:23:04.834672 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] URL: http://devv3.geoportail.lu/main/wsgi/short/create?url=http:%2F%2Fdevv3.geoportail.lu%2Fmain%2Ftheme%2Fmain%3Fversion%3D3%26zoom%3D10%26X%3D684738%26Y%3D6439171%26lang%3Dfr%26layers%3D406-557-558-556-555%26opacities%3D1-0.9-0.9-0.9-0.9%26bgLayer%3Dbasemap_2015_global%26crosshair%3Dtrue
[Mon Jul 13 12:23:04.834708 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
[Mon Jul 13 12:23:04.834716 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   app_iter = self.application(environ, sr_checker)
[Mon Jul 13 12:23:04.834721 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/publisher.py', line 219 in __call__
[Mon Jul 13 12:23:04.834726 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   return self.app(environ, start_response)
[Mon Jul 13 12:23:04.834760 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Mon Jul 13 12:23:04.834826 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = request.get_response(self.app)
[Mon Jul 13 12:23:04.834923 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1320 in send
[Mon Jul 13 12:23:04.834931 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   application, catch_exc_info=False)
[Mon Jul 13 12:23:04.834945 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/webob/request.py', line 1284 in call_application
[Mon Jul 13 12:23:04.835010 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   app_iter = application(self.environ, start_response)
[Mon Jul 13 12:23:04.835058 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 243 in __call__
[Mon Jul 13 12:23:04.835065 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = self.invoke_subrequest(request, use_tweens=True)
[Mon Jul 13 12:23:04.835070 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 218 in invoke_subrequest
[Mon Jul 13 12:23:04.835104 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = handle_request(request)
[Mon Jul 13 12:23:04.835166 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/tweens.py', line 21 in excview_tween
[Mon Jul 13 12:23:04.835232 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = handler(request)
[Mon Jul 13 12:23:04.835385 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 94 in tm_tween
[Mon Jul 13 12:23:04.835516 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   reraise(*exc_info)
[Mon Jul 13 12:23:04.835534 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid_tm/__init__.py', line 75 in tm_tween
[Mon Jul 13 12:23:04.835541 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = handler(request)
[Mon Jul 13 12:23:04.835545 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/router.py', line 164 in handle_request
[Mon Jul 13 12:23:04.835550 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = view_callable(context, request)
[Mon Jul 13 12:23:04.835555 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 353 in rendered_view
[Mon Jul 13 12:23:04.835560 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   result = view(context, request)
[Mon Jul 13 12:23:04.835565 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/pyramid/config/views.py', line 481 in _class_requestonly_view
[Mon Jul 13 12:23:04.835570 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   response = getattr(inst, attr)()
[Mon Jul 13 12:23:04.835574 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] File '/var/www/vhosts/geoportailv3/.build/venv/lib/python2.7/site-packages/c2cgeoportal/views/shortener.py', line 109 in create
[Mon Jul 13 12:23:04.835597 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]   if self.request.user is not None else None
[Mon Jul 13 12:23:04.835662 2015] [:error] [pid 39262] [remote 10.111.80.101:47136] AttributeError: 'O' object has no attribute 'email'
[Mon Jul 13 12:23:04.835766 2015] [:error] [pid 39262] [remote 10.111.80.101:47136]

**Comment by rmichaelis** [comment]
Is it helpful ?

**Comment by sbrunner** [comment]
Yes :-)

**Comment by sbrunner** [comment]
Under this line https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/views/authentication.py#L35 you should add this:
```
user.email = None
```
And it should fix your issue :-)

**Comment by rmichaelis** [comment]
it works thanks
