### ISSUE TITLE
print resolutions

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#634]
the printed maps are not very sharp. this is due to the resolution of the tiles.
We should add a set of x2 or x3 tiles for the background layers and use those in print

**Comment by petzlux** [comment]
@jaykayone 

Will need mapproxy 1.8 for that, as it added necessary mapnik scale_factor

https://github.com/mapproxy/mapproxy/blob/master/CHANGES.txt#L17

**Comment by jaykayone** [comment]
OK, good to know

**Comment by petzlux** [comment]
ideally, we would also update to mapnik 3.0 , some interesting changes to speed up rendering in there. ...

for example, https://github.com/mapnik/mapnik/wiki/PostGIS-Async
