### ISSUE TITLE
travis failed

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#649]
Is it a Travis problem ?

Collecting mccabe<0.4,>=0.2.1 (from flake8->-r CONST_dev-requirements.txt (line 2))
  Could not find any downloads that satisfy the requirement mccabe<0.4,>=0.2.1 (from flake8->-r CONST_dev-requirements.txt (line 2))
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external mccabe to allow).
  No distributions at all found for mccabe<0.4,>=0.2.1 (from flake8->-r CONST_dev-requirements.txt (line 2))
make: *** [.build/dev-requirements.timestamp] Error 1

**Comment by sbrunner** [comment]
=> restart Travis...

**Comment by rmichaelis** [comment]
I've already restarted the job. The problem remains. Maybe I should try later.

**Comment by rmichaelis** [comment]
seems to work now.
