### ISSUE TITLE
travis failed on resizemap.js

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#651]
ERR! compile /home/travis/build/Geoportail-Luxembourg/geoportailv3/node_modules/ngeo/src/directives/resizemap.js:64: ERROR - Property on never defined on angular.$animate
ERR! compile           $animate.on('addClass', element, animationCallback);
ERR! compile                    ^
ERR! compile 
ERR! compile /home/travis/build/Geoportail-Luxembourg/geoportailv3/node_modules/ngeo/src/directives/resizemap.js:65: ERROR - Property on never defined on angular.$animate
ERR! compile           $animate.on('removeClass', element, animationCallback);
ERR! compile                    ^
ERR! compile 
ERR! compile 
ERR! compile 2 error(s), 0 warning(s), 97.3% typed
ERR! compile 
ERR! closure-util Process exited with non-zero status, see log for more detail: 2
make: *** [.build/build.js] Error 1

**Comment by pgiraud** [comment]
An upgrade of angular is required.
See #653.
