### ISSUE TITLE
travis failed on searchdirective.js

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#655]
compile /home/travis/build/Geoportail-Luxembourg/geoportailv3/geoportailv3/static/js/search/searchdirective.js:601: ERROR - Bad type annotation. Unknown type olx.view.FitGeometryOptions
ERR! compile         /** @type {olx.view.FitGeometryOptions} */ ({maxZoom: 17}));

**Comment by elemoine** [comment]
Yep, a recent ol3 change.
