### ISSUE TITLE
print output distorted

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#656]
tested on ipad 
![img_0005](https://cloud.githubusercontent.com/assets/2540428/8486034/2ecafdc2-2102-11e5-8857-131e7574719a.PNG)

**Comment by geoportallux** [comment]
cannot reproduce?


Jeff Konnen

Charg? d'?tudes - informaticien/Chef de projet



LE GOUVERNEMENT DU GRAND-DUCH? DE LUXEMBOURG

Minist?re des Finances

Administration du cadastre et de la topographie

Service informatique & Service g?oportail



54, avenue Gaston Diderich<x-apple-data-detectors://1/0> . L-1420 Luxembourg

T?l. (+352) 44901-261<tel:(+352)%252044901-261> . Fax (+352) 44901-333<tel:(+352)%252044901-333>

E-mail: jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>

www.act.public.lu<http://www.act.public.lu/> www.geoportail.lu<http://www.geoportail.lu/>

On 02.07.2015, at 21:35, Patrick Weber <notifications@github.com<mailto:notifications@github.com>> wrote:


tested on ipad
[img_0005]<https://cloud.githubusercontent.com/assets/2540428/8486034/2ecafdc2-2102-11e5-8857-131e7574719a.PNG>

-

**Comment by jaykayone** [comment]
format and scale?

**Comment by elemoine** [comment]
> cannot reproduce?

Is this a question, or are you just saying that you're not reproducing the problem?

**Comment by jaykayone** [comment]
this is what i am saying. we tried some more afterwards and could not reproduce it a second time.
We'll try harder :)
