### ISSUE TITLE
Print mask issues at two last zoom levels

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#665]
There is a bug related with the print mask when one of the last two zoom levels is used for the map. The print mask is very very large and `1:∞` is displayed for the scale in the print form.

**Comment by elemoine** [comment]
The bug triggers because we don't have appropriate print scales for the last two map zoom levels (zoom levels 11 and 12), at least for my screen size.

At this point I am going to provide a patch that makes the code more robust and select the smallest print map scale when no optimal scale can be found.

**Comment by jaykayone** [comment]
OK
