### ISSUE TITLE
icon text too long

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#669]
solution is probably to call it "My maps" in every language

@petzlux?

**Comment by jaykayone** [comment]
![screen shot 2015-07-07 at 08 47 03](https://cloud.githubusercontent.com/assets/1518019/8540326/e4cf921a-2484-11e5-8287-05bdb264cab4.png)

**Comment by petzlux** [comment]
one for @adonno

**Comment by elemoine** [comment]
And I think this adds a vertical scrollbar to the page.

**Comment by adonno** [comment]
All translationtions changed to "My maps"
