### ISSUE TITLE
 ev.elapsedTime is undefined

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#679]
When navigating on catalog I receive this error : (with ff, seems to work with chrome)

TypeError: ev.elapsedTime is undefined
http://devv3rm.geoportail.lu/node_modules/angular-animate/angular-animate.js
Line 1262

**Comment by jaykayone** [comment]
as this does not seem to blocking, I'll set it to milestone 2

**Comment by elemoine** [comment]
This looks like an Angular bug!

**Comment by hitchcockwill** [comment]
@rmichaelis did you find a fix for that problem? I'm running into the same issue and this is the only reference to it I've found so far.

**Comment by hitchcockwill** [comment]
Thanks for the response @rmichaelis. That's too bad. I'll keep looking for a solution.

**Comment by scastaldi** [comment]
I fixed it by adding the line of code below in function onAnimationProgress(event)
if (ev.elapsedTime === undefined) ev.elapsedTime = maxDuration;
