### ISSUE TITLE
Text in pdf never translated

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#682]
This line lets me think, that this is not only a translation issue :
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/print/printdirective.js#L436

**Comment by jaykayone** [comment]
looks like you might be right here

**Comment by elemoine** [comment]
Good catch @rmichaelis. @sbrunner added this, and I don't remember what it is for.

**Comment by elemoine** [comment]
Ok, the lang parameter that we pass in print requests is related to the legend URLs. See https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/views/luxprintproxy.py#L100-L103. But it's probably not use by MapFish Print currently.

**Comment by jaykayone** [comment]
well legends are language dependend, in this case they are probably always in french ..

**Comment by jaykayone** [comment]
confirmed ..

**Comment by elemoine** [comment]
> well legends are language dependend, in this case they are probably always in french ..

Yes I know. Fixing should be easy. We just need to send the current language in the print request.
