### ISSUE TITLE
tooltips poi

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#684]

**Comment by rmichaelis** [comment]
done for poi as well as for mymaps layers.

@jaykayone could you please check ?

**Comment by jaykayone** [comment]
looks good for POI and my maps 

the detail for mymaps will be done in v2

**Comment by rmichaelis** [comment]
Mymaps uses now only the public category

**Comment by jaykayone** [comment]
what about the other toolips migration? can you create a separate issue please?
