### ISSUE TITLE
Associate a tooltip with each queryable layer 

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#694]

**Comment by rmichaelis** [comment]
Done for poi, mymaps, esri

**Comment by petzlux** [comment]
can this be moved to milestone 2 ?

**Comment by rmichaelis** [comment]
Yes It can. 
The main work has already been done for milestone 1. 
For milestone 2, we have to point out the missing information, and add it in tooltips.
