### ISSUE TITLE
webfonts question

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#706]
@pgiraud, I still don't know what's the best way to know what character code (e018 etc) corresponds to what icon in the webfont. Could you enlighten me please?

**Comment by jaykayone** [comment]
other question: How do you choose matching colors for the 3 colors for a theme?

**Comment by pgiraud** [comment]
I created the font using the https://icomoon.io service. It creates an archive in which one can find the font in different formats as well as HTML files showing how to use the font. I'll send you this archive. Feel free to include it or at least document it somewhere in the project.

**Comment by pgiraud** [comment]
For the colors for themes, if I remember well, I used the one provided in the initial templates by the design company.
Using a tool like https://color.adobe.com/ could help if you need to create colors for new themes.

**Comment by jaykayone** [comment]
great, many thanks
