### ISSUE TITLE
mobile - sharing

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#709]
there's no sharing button on mobile... is that what we want @petzlux ?

**Comment by petzlux** [comment]
Yes, was planned to be available , just as language switcher 

https://github.com/Geoportail-Luxembourg/geoportailv3/issues/43

**Comment by petzlux** [comment]
As far as I can tell, the left bottom info button is useless in mobile, shall we replace with sharing button ?

**Comment by jaykayone** [comment]
+1
