### ISSUE TITLE
Coordinates DMS add one decimal

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#710]

**Comment by petzlux** [comment]
Needs to be fixed in ol3 . At the moment there is no option to have DMS with decimals in seconds

**Comment by jaykayone** [comment]
what about using our own formatter?

It's not a big thing: https://github.com/openlayers/ol3/blob/e62b2e447953c9eb19aa33f77aee1d5c2d98578b/src/ol/coordinate.js#L134
