### ISSUE TITLE
Social Media meta tags issues

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#717]
map_tile => no translation

I'm not sure that the default text is the good one. But in any case it's not translated.

![image](https://cloud.githubusercontent.com/assets/5594996/8667866/6798328a-2a05-11e5-81cf-b44ac44fe994.png)

**Comment by petzlux** [comment]
we need to add meta tags for social sharing,  see details here: 

https://moz.com/blog/meta-data-templates-123

**Comment by petzlux** [comment]
This is a bit more involved, because the social website crawlers that take all that information from websites that users want to share do not evaluate Javascript!! Basically meaning, that for example our translations do not get picked up.

**Comment by petzlux** [comment]
See also this article: http://www.michaelbromley.co.uk/blog/171/enable-rich-social-sharing-in-your-angularjs-app
