### ISSUE TITLE
Sorting  layers does not work.

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#733]
It works only with the id

**Comment by geoportallux** [comment]
have you restarted apache?


Jeff Konnen

Charg? d'?tudes - informaticien/Chef de projet



LE GOUVERNEMENT DU GRAND-DUCH? DE LUXEMBOURG

Minist?re des Finances

Administration du cadastre et de la topographie

Service informatique & Service g?oportail



54, avenue Gaston Diderich<x-apple-data-detectors://1/0> . L-1420 Luxembourg

T?l. (+352) 44901-261<tel:(+352)%252044901-261> . Fax (+352) 44901-333<tel:(+352)%252044901-333>

E-mail: jeff.konnen@act.etat.lu<mailto:jeff.konnen@act.etat.lu>

www.act.public.lu<http://www.act.public.lu/> www.geoportail.lu<http://www.geoportail.lu/>

On 15.07.2015, at 14:30, Renaud Micha?lis <notifications@github.com<mailto:notifications@github.com>> wrote:


It works only with the id

-

**Comment by rmichaelis** [comment]
3 hours ago
