### ISSUE TITLE
how to create a new "UI metadatas" ?

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#736]
Field Name is empty
![image](https://cloud.githubusercontent.com/assets/5594996/8699056/f3471244-2b02-11e5-84f1-17344cc66fa8.png)

**Comment by sbrunner** [comment]
De mémoire il faut ajouter dans le fichier `vars_geoportalv3.yaml`:
```
  admin_interface:
    available_metadata: 
      - option1
      - option2
```
