### ISSUE TITLE
Metadata view 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#741]
![screenshot_2015-07-16-14-53-50](https://cloud.githubusercontent.com/assets/2540428/8723024/c39f5092-2bca-11e5-821d-f6818b6bb335.png)

**Comment by rmichaelis** [comment]
What would be the best solution ?

**Comment by jaykayone** [comment]
@petzlux proposed to change the translation so that it uses two words. He will do so
