### ISSUE TITLE
ortho is not printed

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#744]
http://g-o.lu/v3/hpWI

**Comment by jaykayone** [comment]
print does not take into account the opacity settings of the topo 1:5k map

**Comment by jaykayone** [comment]
it seems to be a general problem with WMTS layers. Their opacity setting is not being sent to the print server

**Comment by jaykayone** [comment]
@rmichaelis is this something that we can fix or is it in ngeo?

**Comment by rmichaelis** [comment]
here in ngeo : https://github.com/camptocamp/ngeo/blob/master/src/services/print.js#L341

**Comment by jaykayone** [comment]
@pgiraud could you make a PR for this please?

**Comment by jaykayone** [comment]
@pgiraud @elemoine any news on this?

**Comment by elemoine** [comment]
I just created https://github.com/camptocamp/ngeo/pull/285.

**Comment by jaykayone** [comment]
OK, looks good, waiting for it to be merged

**Comment by elemoine** [comment]
It's now merged.
