### ISSUE TITLE
User rights

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#753]
Some tables are available through the admin interface when a non admin user is connected.

![image](https://cloud.githubusercontent.com/assets/5594996/8776080/b3c9c07c-2eee-11e5-84e1-2c2804a1ff30.png)

**Comment by sbrunner** [comment]
Those lines are needed in your classes:
https://github.com/camptocamp/c2cgeoportal/blob/master/c2cgeoportal/models.py#L131-L133
