### ISSUE TITLE
print: Zoom to extent

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#759]
when changing the scale in print, the system should zoom out when the extent is bigger than the current map extent so that you can see the extent on screen. this has to be done in ngeo

**Comment by jaykayone** [comment]
@elemoine: Could you comment on this one please? Is this planned in ngeo?

**Comment by jaykayone** [comment]
just re-pinging @elemoine for this one

**Comment by elemoine** [comment]
If we zoom out the map when the user changes the print scale (in the case when the print rectangle is bigger than the map extent) then two things will move at the same time: the map and print mask. I wonder if this may confuse the user.

And if we do that will we also want to automatically change the print scale when the user zooms in the map? Again, two things will move at the same time, which may confuse the user.

I you still think it makes sense to zoom out the map when the print rectangle is bigger than the map extent then I can try to implement it so we can see what the user experience is.

Please comment.

**Comment by jaykayone** [comment]
@petzlux  ?

**Comment by petzlux** [comment]
@elemoine , after talking with @jaykayone , can you please implement as discussed. We just want to give the user a visual hint of what will be printed, and this only works when the whole print extent is in view. 
We should just change the zoom level, not the map center, so that the print extent doesnt move.

**Comment by elemoine** [comment]
> And if we do that will we also want to automatically change the print scale when the user zooms in the map?

What about this question?

**Comment by jaykayone** [comment]
yes that makes sense too

**Comment by elemoine** [comment]
> yes that makes sense too

Ok, I'll start by adjusting the map zoom based on the print scale. And we'll see if we do it in the other direction as well.

**Comment by petzlux** [comment]
In my opinion, as it is now, is sufficient. I dont believe we need to change the print scale on zoom in. We want to stay consistent and only change print scale through the dropdown.

**Comment by elemoine** [comment]
> In my opinion, as it is now, is sufficient. I dont believe we need to change the print scale on zoom in. We want to stay consistent and only change print scale through the dropdown.

Sounds good to me.

**Comment by elemoine** [comment]
Fixed with https://github.com/Geoportail-Luxembourg/geoportailv3/pull/899.
