### ISSUE TITLE
Map performance issue on FF

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#769]
I am observing major map pan performance issues in FF.

For example with http://devv3.geoportail.lu/main/wsgi/theme/main?version=3&zoom=16&X=680704&Y=6376939&lang=lb&layers=373-154-146-151&opacities=1-1-1-1&bgLayer=basemap_2015_global&debug

I just run Profiles test and it seems that `forEachLayerAtPixel` takes a lot of CPU time. So we could probably make map panning a lot faster by checking that the map is not being panned before calling `forEachLayerAtPixel`.

I am considering this a bug.

**Comment by jaykayone** [comment]
can't reproduce with FF on mac

**Comment by elemoine** [comment]
Yep, forgot to say that this is Linux here.
