### ISSUE TITLE
MYMAPS: Layout et design généraux

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#778]

**Comment by jaykayone** [comment]
• Réflexion/discussion design
• Réalisation de mockups

Charge: 4 jours

**Comment by jaykayone** [comment]
Link to #792

**Comment by pgiraud** [comment]
Latest PDF of the mockups available with this link: https://drive.google.com/a/camptocamp.com/file/d/0B3tnRYRfuoYienU0N3hrNC02Rmc/view?usp=sharing

**Comment by jaykayone** [comment]
can this be closed? if not, what has to be done by us for it to be closed?

**Comment by pgiraud** [comment]
There still may be some design work to be done for the mobile/tablet version.
This can be closed anyway.
