### ISSUE TITLE
MYMAPS: Sauvegarde dessin dans permalien

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#781]

**Comment by jaykayone** [comment]
- "Encoding" des géométries dessinées sur la carte dans le permalien.
- Affichage sur la carte des géométries encodées dans le permalien.
Charge: 3 jours

**Comment by jaykayone** [comment]
Link to #792

**Comment by rmichaelis** [comment]
Minify the properties in the url
