### ISSUE TITLE
MYMAPS: Import et Export

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#784]
Il est possible d’importer dans le document des géométries en provenance de fichier
KML ou GPX (par exemple généré par un GPS). Il est aussi possible d’exporter toutes les
géométries, importées ou dessinées, dans un fichier GPX ou KML.
* Import de fichier GPX
*  Import de fichier KML

**Comment by jaykayone** [comment]
IMPORT ET EXPORT
• Fonctions d'export GPX et KML
• Fonctions d'import GPX et KML
Charge : 5 jours
©

**Comment by jaykayone** [comment]
Link to #792

**Comment by elemoine** [comment]
OpenLayers 3 already supports GPX and KML, both for read and write. So I am closing this issue.
