### ISSUE TITLE
Lien entre les objets de la carte et les objets de la liste

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#785]

**Comment by adonno** [comment]
Link to #780

**Comment by jaykayone** [comment]
entre #785 et #786, il y a 5 jours de prévus. 
A voir en détail au moment de l'implémentation

**Comment by jaykayone** [comment]
à faire en 2e lieu

**Comment by jaykayone** [comment]
can this be closed?

**Comment by pgiraud** [comment]
Selection works. A bit of styling needs to be done for the list display.
Aslo work needs to be done to display icons.
Also work needs to be done to distinguish read-only from editable features. User should be able to draw features even when a map owned by someone else is displayed.

**Comment by jaykayone** [comment]
@pgiraud, can this be closed?
