### ISSUE TITLE
"Encoding" des géométries dessinées sur la carte dans le permalien.

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#793]
Link to #781

**Comment by elemoine** [comment]
Nous avons dans CGXP un format OpenLayers permettant d'encoder des features avec leurs attributs et leurs styles: https://github.com/sbrunner/OpenLayers-URLCompressed. Nous proposons de porter ce format dans ngeo.

Pour information, voici un exemple de permalien contant 5 géométries (voir le param `rl_features`) :

http://geomapfish-demo.camptocamp.net/1.6/wsgi/theme/Administration?map_x=537582.56132288&map_y=153208.3786353&map_zoom=5&rl_features=Fp%283b49Ff35y_~name*A%2520title~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27pointRadius*6%27fontColor*%2523000000%29a%28w9VeHJ_J*JBHFHFFHBHBJ*J.L.J!LAHAJEHGFGDIBIBI_K.I-IAIAGCEEEGCIAG-K-I_K_IBIDGFGFEHEJAJ!J-~isCircle*true~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27strokeWidth*1%29a%28rzPe6Gs5-kAh4-yFh2-5LsZyP9WbU7S3YkN71-kIn3-bD95-s_36-r_36-aD95-jIn3-jN71-6S3Y8W9UrZ1Qg2-5Lg4-yFr5-kA66-.r5-jAj4-xFg2-4LpZzP8W8U6S2YmN61-jIm3-8D85-t_26-u_26-9D85-kIm3-nN61-7S2Y9WaUqZxPh2-4Lk4-xFs5-jA~isCircle*true~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27strokeWidth*1%29a%287p3-qqI88Cm3EwQv6IraH9hP~~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27strokeWidth*1%29a%28rbd-v9E.9tDd4D..8tD~isBox*true~fillColor*%2523ff0000%27strokeColor*%2523ff0000%27strokeWidth*1%29l%285c01yFvt!vbScrSdErzLvdH~~strokeColor*%2523ff0000%27strokeWidth*1%29.

**Comment by elemoine** [comment]
Pour information, j'ai commencé à travailler sur ce nouveau format dans ngeo. Ça se passe dans ma branche pla-format: https://github.com/elemoine/ngeo/tree/pla-format.

**Comment by elemoine** [comment]
La PR ngeo https://github.com/camptocamp/ngeo/pull/304 est mergée. L'essentiel est là mais il restera très probablement des petites choses à faire. Par exemple il me semble qu'on aura besoin de pouvoir filtrer les propriétés encodées dans le permalien. Je pressens en effet qu'on aura des espèces de propriétés privées qui ne devront pas être encodées dans le permalien. On aura aussi des manques au niveau des styles. Mais comme je ne connais encore pas la liste des styles réglables par l'utilisateur je me suis limité au minimum. Mais maintenant que la base est là ces modifications seront rapides à faire.

**Comment by rmichaelis** [comment]
@elemoine Ca fonctionne super bien, par contre les url générées deviennent vite assez longues.
Je pense que dans la majorité des cas, nous n'aurons pas de problème. 

J'aimerais avoir ton avis, est-ce qu'on ne pourrait pas gagner en longueur en encodant les propriétés de la feature  de la même manière que l'on encode les géométries ?

**Comment by elemoine** [comment]
> J'aimerais avoir ton avis, est-ce qu'on ne pourrait pas gagner en longueur en encodant les propriétés de la feature de la même manière que l'on encode les géométries ?

À ce stade je ne me suis pas posé la question, parce que notre objectif, pour GMF 2, était de maintenir la compatibilité avec les permaliens actuels (de GMF 1.x).

À noter qu'il est est possible de passer une option `properties` au format `ngeo.format.FeatureHash`. Cette option est une fonction qui reçoit une feature et retourne les propriétés à encoder pour cette feature. On l'utilise déjà dans le projet, pour exclure certaines propriétés de la feature. On pourrait aussi l'utiliser pour changer les clés des propriétés et utiliser des clés à un caractère. On pourrait aussi tronquer les valeurs décimales. Ensuite, évidemment, il faudrait être capable de faire l'opération inverse au moment du decoding des features.
