### ISSUE TITLE
UI création carte

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#795]
Link to #779

**Comment by geoportallux** [comment]
Nous proposons de commencer les travaux par ce point

**Comment by jaykayone** [comment]
celà correspond aux mockups page 16, 23, 13,14

**Comment by jaykayone** [comment]
attention, temps prévu dans l'offre: 2j
Concentre - toi donc sur le CSS et le workflow, l'interaction avec le serveur, ce sera fait par nous

**Comment by pgiraud** [comment]
À mon avis, il n'y a pas vraiment de UI pour la création de carte mis à part un bouton "Create new map".

Les mockups en pages 13 et 14 sont réalité liés à la modification du titre et de la description d'une carte. Cette fenêtre doit apparaître automatiquement lors de la création d'une nouvelle carte. Mais, à ce moment, la carte a déjà été créée sur le serveur et a été chargée.

Je pense donc que le travail est en réalité davantage à faire dans l'issue qui concerne la modification #796 .

**Comment by jaykayone** [comment]
je vois ce que tu veux dire. comme c'est le premier popup, je préfère quand même que tu l'implémentes toi même si le #796 ne t'est pas assigné

**Comment by pgiraud** [comment]
See #859.
