### ISSUE TITLE
UI liste carte

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#797]
Link to #779

**Comment by jaykayone** [comment]
changement par rapport à la version existante: faire une arborescence par catégorie

**Comment by jaykayone** [comment]
voir mockups, on voudrait en plus avoir une table triable et filtrable

**Comment by jaykayone** [comment]
slide 18

**Comment by rmichaelis** [comment]
Il manque l’arborescence par catégorie

**Comment by jaykayone** [comment]
recherche et tri suffisent

**Comment by petzlux** [comment]
okay so this is implemented now ? can we close
