### ISSUE TITLE
Mise en place des outils dans l'application (avec choix des styles)

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#806]
Link to #780

**Comment by jaykayone** [comment]
à faire ensemble avec #785

**Comment by jaykayone** [comment]
je propose que tu te coordonnes avec @rmichaelis et le #807

**Comment by jaykayone** [comment]
can this be closed? if not, what has to be done by us for it to be closed?

**Comment by pgiraud** [comment]
Work needs to be done to add interaction for drawing text and circle.
Interactions should be modified to handle measure display while drawing.
About styling, the symbols for point features still needs work.

**Comment by rmichaelis** [comment]
@pgiraud  can you please explain why the "display while drawing" cannot be reused from the measure tools in ngeo?
