### ISSUE TITLE
Outils pour dessiner des cercles (il n'y a rien dans OpenLayers 3 actuellement)

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#808]
Link to #780

**Comment by elemoine** [comment]
OpenLayers 3 permet maintenant de dessiner des cercles. Voir http://openlayers.org/en/master/examples/draw-features.html. On peut soit dessiner de véritables cercles (`ol.geom.Circle`), soit dessiner des polygones en forme de cercle. Sachant que les véritables cercles ne sont pas sérialisables en GeoJSON, ce qui peut nous poser des problèmes.

**Comment by petzlux** [comment]
:+1:
