### ISSUE TITLE
Modification des géométries (L'interaction modify ne permet pas de déplacer des lignes et polygones)

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#811]
Link to #780

**Comment by elemoine** [comment]
A `Translate` interaction was developed for OpenLayers. I just created a PR with this work: https://github.com/openlayers/ol3/pull/4008. I'll merge it.

While testing this new interaction I noticed that it doesn't play well with the Modify interaction. This is related to https://github.com/openlayers/ol3/issues/3927 – the Modify interaction has a segments cache that should be modified when the geometry is changed from an external source.

**Comment by elemoine** [comment]
New PR created for that issue: https://github.com/openlayers/ol3/pull/4011.

**Comment by elemoine** [comment]
openlayers/ol3#4011 is closed.
