### ISSUE TITLE
Popup et édition des attributs - ajout d'image

### ISSUE THREAD

**Issue by adonno** [Geoportail-Luxembourg/geoportailv3#813]
Link to #780

**Comment by jaykayone** [comment]
slide 7,8, 20

**Comment by jaykayone** [comment]
slide 22

**Comment by pgiraud** [comment]
See #866.

**Comment by jaykayone** [comment]
can this be closed? if not, what has to be done by us for it to be closed?

**Comment by pgiraud** [comment]
Work needs to be done to allow user to add a picture when editing a feature from a mymap.
