### ISSUE TITLE
travis fails

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#834]
Has something changed ?

ERR! compile /home/travis/build/Geoportail-Luxembourg/geoportailv3/geoportailv3/static/js/search/searchdirective.js:528: ERROR - actual parameter 2 of ngeoCreateGeoJSONBloodhound does not match formal parameter
ERR! compile found   : (null|ol.proj.Projection)
ERR! compile required: (function ((GeoJSONFeature|null)): boolean|undefined)
ERR! compile   var bloodhound = ngeoCreateGeoJSONBloodhound(url, ol.proj.get('EPSG:3857'));
ERR! compile                                                     ^
ERR! compile 
ERR! compile 
ERR! compile 1 error(s), 0 warning(s), 97.3% typed
ERR! compile 
ERR! closure-util Process exited with non-zero status, see log for more detail: 1

**Comment by petzlux** [comment]
I think @elemoine changed search in ngeo  , maybe try with update-node-modules ?

**Comment by petzlux** [comment]
https://github.com/Geoportail-Luxembourg/geoportailv3/pull/817 ?

**Comment by rmichaelis** [comment]
Are node modules not automatically updated in Travis ?

**Comment by petzlux** [comment]
dont know about travis, did it work in your build?

**Comment by rmichaelis** [comment]
I don't know...  I don't want to break my build :-)

**Comment by petzlux** [comment]
im trying with your branch as we speak ...

**Comment by petzlux** [comment]
Unfortunately, yes get the same problem :-(

````
./node_modules/openlayers/node_modules/.bin/closure-util build build.json .build/build.js
info closure-util Reading build config
info closure-util Getting Closure dependencies
info closure-util Compiling 431 sources
ERR! compile /home/wepa/geoportailv3/geoportailv3/static/js/search/searchdirective.js:531: ERROR - actual parameter 2 of ngeoCreateGeoJSONBloodhound does not match formal parameter
ERR! compile found   : (null|ol.proj.Projection)
ERR! compile required: (function ((GeoJSONFeature|null)): boolean|undefined)
ERR! compile   var bloodhound = ngeoCreateGeoJSONBloodhound(url, ol.proj.get('EPSG:3857'));
ERR! compile                                                     ^
ERR! compile
ERR! compile 1 error(s), 0 warning(s),
ERR! compile 97.3% typed
ERR! compile
ERR! closure-util Process exited with non-zero status, see log for more detail: 1
make: *** [.build/build.js] Error 1
`````

**Comment by petzlux** [comment]
I think I found the issue , ngeo bloodhound function changed 
https://github.com/camptocamp/ngeo/blob/master/src/services/creategeojsonbloodhound.js#L10

Will create pull request to change!

**Comment by petzlux** [comment]
@rmichaelis use #835 to fix problem.

**Comment by petzlux** [comment]
okay @rmichaelis , if you rebase from master , then problem should be gone at next build

**Comment by rmichaelis** [comment]
It works. Thanks.
