### ISSUE TITLE
Deprecating Powerful Features on Insecure Origins

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#838]
Chromium, onto which Chrome is based, is deprecating "powerful features", such as Geolocation, on pages with non-secure origins (HTTP vs HTTPS).

See  https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins.

Wondering if this is a problem for the project.

**Comment by elemoine** [comment]
> We have planned to switch to https anyway, but first tests did not work.

So more effort on this may be a good idea.

**Comment by petzlux** [comment]
see #512
