### ISSUE TITLE
Search: does not work anymore

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#839]
(Firefox on Mac): You cannot choose a result from the search anymore by hitting enter or clicking the result

Might be a build problem ... we'll see

**Comment by jaykayone** [comment]
@elemoine might this be a regression coming from ngeo?
As @petzlux has not changed anything this week, I wonder where this regression might come from

**Comment by elemoine** [comment]
This is probably a regression introduced by https://github.com/Geoportail-Luxembourg/geoportailv3/pull/817.

**Comment by jaykayone** [comment]
I get an Error: Pattern length is too long in debug mode (console).

**Comment by elemoine** [comment]
I don't know what this means…

**Comment by elemoine** [comment]
Ok, we're fixing a regression introduced in typeahead 0.11.1. The regression is tracked by https://github.com/twitter/typeahead.js/issues/1313. And there is an (unmerged) PR here: https://github.com/twitter/typeahead.js/pull/1207.

One workaround would involve storing the dataset in the suggestion object, but this would require some work, as we handle different suggestion types.

Another option is to try to revert #817. This may just require adding a custom extern type for `TypeaheadDataset`. Not so bad I think.

It took me 1h to investigate the issue. I'll take me another hour or so to revert #817 and introduce the extern type override.

**Comment by elemoine** [comment]
I finally decided to make the revert PR. See #849. And it actually took me less than 1h.
