### ISSUE TITLE
build does not work anymore ...

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#840]
just did a cleanall and build and it does not work anymore ..
I'll try to get an old version online again

2015-09-01 17:21:37 (2.33 MB/s) - ‘.build/externs/jquery-1.9.js’ saved [51584/51584]

touch .build/externs/jquery-1.9.js
./node_modules/openlayers/node_modules/.bin/closure-util build build.json .build/build.js
info closure-util Reading build config
info closure-util Getting Closure dependencies
info closure-util Compiling 431 sources
ERR! compile .build/externs/angular-1.4.js:2234: ERROR - Bad type annotation. missing closing )
ERR! compile  * @typedef {function(Function, number=, boolean=, ...*=):!angular.$q.Promise}
ERR! compile                                                        ^
ERR! compile
ERR! compile
ERR! compile 1 error(s),
ERR! compile 0 warning(s)
ERR! compile
ERR! closure-util Process exited with non-zero status, see log for more detail: 1
make: *** [.build/build.js] Error 1
[root@workshop3-local geoportailv3]#

**Comment by elemoine** [comment]
Saw that. See https://github.com/camptocamp/ngeo/issues/306. I am on it.

**Comment by jaykayone** [comment]
ok, thanks
