### ISSUE TITLE
Generalize the use of `@export` for controller instance properties

### ISSUE THREAD

**Issue by elemoine** [Geoportail-Luxembourg/geoportailv3#865]
Recent versions of Closure Compiler have the `--export_local_property_definitions` flag that can be used to "export" instance properties using the `@export` annotation. We [use](https://github.com/camptocamp/ngeo/pull/216) that annotation in ngeo, and we've started to use it in the project as well, for example in the [app-mymaps directive](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/mymaps/mymapsdirective.js). Using this annotation instead of the square bracket notation makes the code easier to read, so we should generalize it.

**Comment by jaykayone** [comment]
@elemoine is this something you wanna do retroactively?

**Comment by elemoine** [comment]
> @elemoine is this something you wanna do retroactively?

We could. It would be good to make the code consistent. But this is not mandatory.

**Comment by petzlux** [comment]
:+1:
