### ISSUE TITLE
How to exclude partials ?

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#872]
The partials located in the query directive are cached, but this cache is never used. 
The partials are included here https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/query/info.html#L3

Then I would like to exlude these partials of the cache process.

To do that I would like to add something like this:
```APP_CHECHED_PARTIALS_FILES := $(shell find $(PACKAGE)/static/js -type f -name '*.html'  -not -path '$(PACKAGE)/static/js/query/*') $(PACKAGE)/static/js/query/info.html```
here :
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/CONST_Makefile#L82

and like this :
```$(VENV_BIN)/mako-render --var "partials=$(APP_CHECHED_PARTIALS_FILES)" $< > $@```

here :
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/CONST_Makefile#L513

How to do that without modifying the CONST_Makefile ??

**Comment by elemoine** [comment]
> The partials located in the query directive are cached, but this cache is never used.

Why are these partials not read from the cache? What makes them different from other partials?

**Comment by rmichaelis** [comment]
Actually, the partial name is defined in the database and is dynamically sent to the query controller.
When I want to use the cache, that means each time I define a new partial in the database, I should add a new entry into index.html
As during a normal use of the geoportal, only a very minor part of partial is used, I thought it was easier to only add a new entry into the database and to create a new file and additionally not to modify  the index.html. 
In my mind this mechanism was more dynamic, but maybe I was wrong ?

**Comment by elemoine** [comment]
I understand.

Option 1:

What if you change

```
APP_PARTIALS_FILES := $(shell find $(PACKAGE)/static/js -type f -name '*.html')
```

to

```
APP_PARTIALS_FILES ?= $(shell find $(PACKAGE)/static/js -type f -name '*.html')
```

in `CONST_Makefile`, and define your own `APP_PARTIALS_FILES` in `geoportailv3.mk`?

Option 2:

What if you use `.html_` instead of `.html` as the suffix for the "special" partials?

**Comment by rmichaelis** [comment]
I prefer do not touch the CONST_makefile. 
Option 2 is a good idea.
Thanks.

**Comment by elemoine** [comment]
So try it and tell if it works for you!

**Comment by jaykayone** [comment]
@rmichaelis is this still open?

**Comment by rmichaelis** [comment]
Yes still open. This is no more a question, but a task that could be assigned to me.

**Comment by rmichaelis** [comment]
Do not forget to adapt the tool to extract the translations. It should also extract keys ftom .html_
