### ISSUE TITLE
null value cannot be encoded

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#881]
I'm trying to encode some features received from mymaps, and some attributes have null value.
NULL value cannot be encoded due to the following :
https://github.com/camptocamp/ngeo/blob/master/src/ol-ext/format/featurehash.js#L901

Is this behavior wanted ? 

To bypass this, I will set a default value other than null.

**Comment by elemoine** [comment]
This is a bug (somewhere).

Do you think `null` values should be encoded?

**Comment by rmichaelis** [comment]
In fact, the features having null values comming from mymaps should not be encoded in the url. only the mapid has to be in the url. I'm working on it.

Instead of encoding null values, I will just remove the properties having null values from the feature.

Thanks,

**Comment by elemoine** [comment]
This can probably be done in the `properties` function [passed](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/draw/drawdirective.js#L139-L145) to the `FeatureHash` function.

**Comment by elemoine** [comment]
We should think about the decoding as well.

**Comment by rmichaelis** [comment]
I did it in that way. 
Thanks.
