### ISSUE TITLE
Print query information results

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#884]
When feature information is available, then it would be helpful to allow to print it together with the map.

**Comment by jaykayone** [comment]
I totally agree, but I have no idea about the how at the moment

**Comment by petzlux** [comment]
:+1: depends on length of information (depends on layers) . if we can keep it short, than an optional box on printout? also depends on number of features selected.

**Comment by petzlux** [comment]
Or other way around ? Separate Print feature information with small map box showing location

**Comment by jaykayone** [comment]
possibility to add second page to print with tooltip info,
nice to have
