### ISSUE TITLE
Modal window small screens

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#885]
Hi @pgiraud ,

When you open the list of maps in mymaps. 
A modal window appears. 
This modal window is not clickable when the screen size is under 768 px and the modal seems to be under the banner.

Do you know why ?

This is ok :
![image](https://cloud.githubusercontent.com/assets/5594996/10485887/b4c85da8-728c-11e5-98c8-4ff34f09af33.png)

This is not ok :

![image](https://cloud.githubusercontent.com/assets/5594996/10485903/c97cc8b0-728c-11e5-8ff8-404e76eb1307.png)

**Comment by pgiraud** [comment]
This seems to be due to the fact that we change the `position` style for `#sidebar`.
Do you want me to try to find a way to fix this issue?

**Comment by jaykayone** [comment]
yes please

**Comment by pgiraud** [comment]
https://github.com/camptocamp/ngeo/pull/368 should do the job.

**Comment by pgiraud** [comment]
@rmichaelis Can you please update ngeo in your instance and confirm that the issue is fixed?

**Comment by rmichaelis** [comment]
It works fine. Thanks.
