### ISSUE TITLE
usability

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#888]
I fear that nobody will find how to edit the title and description of a map.

@pgiraud 

http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=13&X=686645&Y=6397626&lang=lb&layers=305&opacities=1&bgLayer=basemap_2015_global&map_id=864a60f9ad7c48799f5a6a0d3117397f&crosshair=false

**Comment by jaykayone** [comment]
@pgiraud could you generally do some polishing on the UI now that everything is functional?

- position of the popup (It positions over the geometries one wants to edit),
- design of the element list (bullet representation not intuitive -> striped table ?)
- ..

**Comment by pgiraud** [comment]
I think that the user should be invited to change the title and description just right after the map creation.

**Comment by jaykayone** [comment]
+1 @petzlux aren't you already working on that point?

**Comment by petzlux** [comment]
yes its in PR #912

**Comment by pgiraud** [comment]
With the code from https://github.com/Geoportail-Luxembourg/geoportailv3/pull/928, I made some tests with users to see if it's easy for them to find the way to change the title and description of the map. It looks like it works well.
