### ISSUE TITLE
mymaps vs drawings

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#890]
Here is another use case where I am not sure our concept is good:

http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=15&X=682507&Y=6379895&lang=lb&layers=305&opacities=1&bgLayer=basemap_2015_global&map_id=864a60f9ad7c48799f5a6a0d3117397f&crosshair=false&features=Fl(u8na-qta6HnMzLnJhK~name*element%25201%27color*%2523ed1c24%27opacity*0.2%27stroke*1.25%27size*10%27angle*0%27is_label*false%27linestyle*plain%27symbol_id*circle)

So this is one of my maps where another user added a line on top (it resides in the permalink).

Now he sends me that link. When I now edit that geom it gets integrated into my map without me noticing. That cannot be it.

I THINK that the two lists should be visibly separate and that we should NOT automagically transfer anything from list a to list b.

@petzlux @pgiraud @rmichaelis ?

**Comment by rmichaelis** [comment]
I agree.

**Comment by elemoine** [comment]
I think I agree too. The automagical transfer would confuse users.

**Comment by petzlux** [comment]
I agree, we should have a separate list with 'unsaved' map elements, that can be saved into the mymaps.

**Comment by jaykayone** [comment]
OK so have an agreement here, @pgiraud can you implement this please?

**Comment by pgiraud** [comment]
@rmichaelis Is https://github.com/Geoportail-Luxembourg/geoportailv3/pull/924 related to the current issue?

**Comment by rmichaelis** [comment]
Yes it's part of #924

**Comment by petzlux** [comment]
@jaykayone Can we close this, it seems that the proposed solution is implemented .
