### ISSUE TITLE
create new map does not work (anymore)

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#894]
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=16&X=682404&Y=6377851&lang=lb&layers&opacities&bgLayer=basemap_2015_global&crosshair=false&features=Fl%289cna-hs86HwL7CdKuA~name*element%25201%27color*%2523ed1c24%27opacity*0.2%27stroke*1.25%27size*10%27angle*0%27is_label*false%27linestyle*plain%27symbol_id*circle%29

**Comment by rmichaelis** [comment]
fixed
