### ISSUE TITLE
License for MyMaps maps 

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#906]

**Comment by grischard** [comment]
How flickr does it: http://www.wikihow.com/Apply-the-Creative-Commons-License-to-Flickr-Photographs

The license can be used as a filter criteria:

https://www.flickr.com/creativecommons/

**Comment by petzlux** [comment]
would an open data license only apply for public maps?

**Comment by jaykayone** [comment]
probably

**Comment by grischard** [comment]
I think it would apply to any map. A license applies to anything you distribute, even if distribution only happens in a restricted group. Anything uploaded or created on mymaps is distributed with at least the Cadastre, and it can be a legal requirement to ShareAlike.

Example case:

A mushroom picking club creates secret trails based on OpenStreetMap and uploads it to MyMaps. One year later, another member of the club creates a new version of the map with improved routes.

Expected functionality:

Attribution to OpenStreetMap and the hiking mapper should be preserved. Data can be shared within the group. The Cadastre and everyone in the group should get the data under a ShareAlike license.
