### ISSUE TITLE
public maps

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#913]
Up to now, we don't have the ability to choose a public map.
Shouldn't we have a button "open a public map" that is working just like the button "open a map" but with public maps.?

**Comment by petzlux** [comment]
In the old geoportail, public mymaps were displayed as a separate category in the catalogue. For example, in the tourism portal . Do we want to keep this way to publish MyMaps ?

**Comment by jaykayone** [comment]
we want to keep that way, we could add another way to open them with a list but let's keep that for later.

**Comment by petzlux** [comment]
Simply pushing Mymaps marked as public to a separate category in the catalogue would have the benefit of:

- Keeping the interaction consistent to find layers of information (through catalogue or search)
- Make the public feel that MyMaps are geodata just like any other information, ie not second class data
- Make life easier for us to develop

**Comment by jaykayone** [comment]
It's the way it works today or have I misunderstood sthg?

**Comment by petzlux** [comment]
No that is indeed the way, just listed the benefits in my view :-)
