### ISSUE TITLE
Circular reference crashing

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#916]
In the user manager, the following causes a circular reference error. 

https://github.com/Geoportail-Luxembourg/geoportailv3/commit/9d203f1fe65c9941e4de1d081ddb606d06187f8b#diff-3ea6f846403c9b02ff2ee1b7ed3214a9R213

@rmichaelis can you please check ?

**Comment by rmichaelis** [comment]
How did you solve it?

**Comment by petzlux** [comment]
my fault, i did a rebase of my changes from a pull request and missed a conflict
