### ISSUE TITLE
Give the drawn features a relevant title

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#921]
Currently, the drawn features are automatically given "element xx" as title.
It would be better in terms of usability to give them a more concrete name such as "Line 1" or "Point xx".

Also the counter should take the already drawn features in case of a loaded map. Currently, the counter starts from "0" even if features are already in the map. It may results in two features having the same title ( "element 1" for example).

**Comment by jaykayone** [comment]
+1
