### ISSUE TITLE
Circle type Object not serializable to GeoJSON

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#923]
In PR #914 , I have to transform OL Circle object to a vector, as GeoJSON doesnt support Circle as a feature class. This is potentially a problem for later editing the circle (change location or radius)

**Comment by elemoine** [comment]
Yes, I think we should not use `ol.geom.Circle` in the project.

**Comment by petzlux** [comment]
@jaykayone can I close this for now and accept PR #914 as is ?

**Comment by jaykayone** [comment]
yes, we have to write a modify interaction later on, like we did in geoportalv2
