### ISSUE TITLE
proj4 is loaded twice in debug mode

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#933]
See
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/templates/index.html#L240

and

https://github.com/Geoportail-Luxembourg/geoportailv3/commit/424a744e8bf3c1c5f2145b73a7b92d44ac0c14b8

**Comment by petzlux** [comment]
ups :-1:
