### ISSUE TITLE
Editus POI not correctly displayed

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#935]
Since the last rebase, the editus pois are misplaced ... It works fine on old versions.
Here wrong : 
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=10&X=662973&Y=6411594&lang=fr&bgLayer=basemap_2015_global&layers=561&opacities=0.9

here fine : 
http://devv3.geoportail.lu/main/theme/main?version=3&zoom=10&X=662973&Y=6411594&lang=fr&bgLayer=basemap_2015_global&layers=561&opacities=0.9

**Comment by jaykayone** [comment]
height and width in ogc request are wrong:

bad: 
http://devv3.geoportail.lu/renaud/wsgi/ogcproxywms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=png&TRANSPARENT=true&LAYERS=561&CRS=EPSG%3A3857&STYLES=&WIDTH=1401&HEIGHT=1016&BBOX=595387.1225703091%2C6330056.060408587%2C756019.5375116072%2C6446546.091515195
good:
http://devv3.geoportail.lu/main/wsgi/ogcproxywms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=png&TRANSPARENT=true&LAYERS=561&CRS=EPSG%3A3857&STYLES=&WIDTH=2101&HEIGHT=1523&BBOX=595406.2318273805%2C6330170.715951014%2C756000.4282545358%2C6446584.310029337

**Comment by rmichaelis** [comment]
Solved with latest ngeo and ol libraries
