### ISSUE TITLE
freeze versions OL and NGEO

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#941]

**Comment by petzlux** [comment]
Questions for @pgiraud : 

Before we go to prod, we want to version pin ngeo and openlayers , to exclude problems like we had multiple times in the past #937 #946 #917  ....

Is there any downside to doing this, except for the fact that we will then for an update of ngeo explicitely create a pull request? 

PS: I noticed that ngeo is on angular 1.4.7  vs us on 1.4.1 , which seems to win. We will have to watch any version drift in the future ...

**Comment by pgiraud** [comment]
I think freezing the OpenLayers and ngeo versions before going to prod is a good idea too.
We should do this as soon as we know that we don't need new features. I think that we should freeze OpenLayers already.
I'm not sure about ngeo though.

Creating a pull request any time we need a library update is the right way to go I think.

I'm less afraid about angular versions but I can't tell why.

**Comment by jaykayone** [comment]
YES. Can you do this please?

**Comment by rmichaelis** [comment]
Don't we need to have the latest version of c2cgeoportal before freezing anything ?

**Comment by jaykayone** [comment]
that's correct.
what's the status here @pgiraud @sbrunner ?

**Comment by sbrunner** [comment]
No direct relation between version of c2cgeoportal end version of ol3/ngeo...

**Comment by rmichaelis** [comment]
Has ngeo no relation with this ? https://github.com/camptocamp/c2cgeoportal/pull/1758

**Comment by petzlux** [comment]
do this after #962
