### ISSUE TITLE
Drawn elements cannot be selected on the map

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#942]
If the user tries to click on drawn elements, they are not selected anymore.

**Comment by rmichaelis** [comment]
Probably due to this commit : https://github.com/openlayers/ol3/commit/d968f324560b39aba28524022516c8c53661c562

**Comment by pgiraud** [comment]
It looks like the regression has already been fixed in OL3.
See https://github.com/openlayers/ol3/pull/4450.

I wanted to make sure that the given commit is the right one, but I can't seem to use OL3 with an npm link in Geoportailv3.

**Comment by pgiraud** [comment]
Can you confirm that this is fixed for you too by updating node modules?

**Comment by jaykayone** [comment]
@rmichaelis can you check this please?

**Comment by petzlux** [comment]
works for me !

**Comment by rmichaelis** [comment]
Works for me too.
If needed, last version of the master is available here : http://devv3.geoportail.lu/renaud/
