### ISSUE TITLE
mymaps: modify cercle

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#944]
cf geoportailv2 πr2

**Comment by petzlux** [comment]
A Circle then is a Point Geometry with a radius , and will be serialized as a point ...

**Comment by jaykayone** [comment]
in geoportail v2 it was serialized as a polygon and only the modify action was specific

**Comment by petzlux** [comment]
Okay will do the same!

**Comment by rmichaelis** [comment]
I think that in GeoportailV2 Mymaps does not allow to modify the circle as a circle. Only the drawing tool allows that.
