### ISSUE TITLE
Feature Idea : allow to link to external geojson for display

### ISSUE THREAD

**Issue by petzlux** [Geoportail-Luxembourg/geoportailv3#948]

**Comment by petzlux** [comment]
This would also be a relevant functionality in the context of the GeoAPI, and integration into the future Luxembourg OpenData Portal for preview of geo datasets (extents and/or data)

**Comment by jaykayone** [comment]
yes and it should also cover kml and gpx

**Comment by jaykayone** [comment]
also add geojson to api
