### ISSUE TITLE
Label for public value should be changed

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#949]
A checkbox label should not be an action (ie. a verb).
It's confusing for the user.

![screenshot from 2015-11-27 13 50 41](https://cloud.githubusercontent.com/assets/319774/11441584/eb2c4c3a-950d-11e5-8deb-fa89c0deadb0.png)
![screenshot from 2015-11-27 13 50 53](https://cloud.githubusercontent.com/assets/319774/11441585/ec9d87a0-950d-11e5-8848-c86e34cb7b71.png)

**Comment by jaykayone** [comment]
I agree.
Can you make a proposition?

**Comment by jaykayone** [comment]
simply "public*
