### ISSUE TITLE
measure tools don't work any more

### ISSUE THREAD

**Issue by pgiraud** [Geoportail-Luxembourg/geoportailv3#951]
Looks like there's a mix between the measure interactions and the select interaction.

**Comment by pgiraud** [comment]
I'll address this issue in priority.

**Comment by petzlux** [comment]
urghh yeah just noticed !

**Comment by pgiraud** [comment]
This is due to the fact that the filter function in the select interaction is not called any more thus features drawn with the measure tools are selected.
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/static/js/draw/drawdirective.js#L255

Probably an OL3 regression. Digging into it.
But I have to `npm link` openlayers which I'm not able to do at the moment.

**Comment by pgiraud** [comment]
FYI, I got the `npm link` working.
The node module `slimerjs-edge` needs to be removed. Also `ol-debug.js` needs to be removed if OL3 has already been built.

**Comment by pgiraud** [comment]
OL3 bug tracked here: https://github.com/openlayers/ol3/issues/4504

**Comment by pgiraud** [comment]
Fixed via https://github.com/openlayers/ol3/pull/4472
