### ISSUE TITLE
add layer trough search box

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/geoportailv3#988]
I cannot add a layer anymore by selecting in the search box

**Comment by rmichaelis** [comment]
I have juste a quick look, and it appears that a new version of ngeo introduced this error. 

* A new version of typehead should be used.
* Listener event is no more ```selected``` but ```select```
* Css class name changed
* Probably other side effects

**Comment by petzlux** [comment]
okay thanks @rmichaelis !
