### ISSUE TITLE
travis failure

### ISSUE THREAD

**Issue by rmichaelis** [Geoportail-Luxembourg/geoportailv3#990]
@pgiraud @sbrunner Has something been changed ? 

 Hash of the package http://pypi.camptocamp.net/pypi/python-gflags/python-gflags-2.0.tar.gz#md5=23c9a793959a54971b1f094b0c6d03b1 (from http://pypi.camptocamp.net/pypi/python-gflags/) (c3ab70218dbf945cc32c0cd64c51d162) doesn't match the expected hash 23c9a793959a54971b1f094b0c6d03b1!
Bad md5 hash for package http://pypi.camptocamp.net/pypi/python-gflags/python-gflags-2.0.tar.gz#md5=23c9a793959a54971b1f094b0c6d03b1 (from http://pypi.camptocamp.net/pypi/python-gflags/)

**Comment by sbrunner** [comment]
I just remove the wrong file from the proxy, does it works now?

**Comment by rmichaelis** [comment]
Thanks, it works now.

**Comment by sbrunner** [comment]
Excellent, thanks for the feedback :-)
